# Generated by egg v0.0.1

# Build the Frontend
### If you are not using a JS framework you can comment out this section
FROM node:22-alpine AS node_builder
WORKDIR /usr/src/web
COPY web/package.json ./
### use pnpm
RUN npm install -g pnpm && pnpm install
COPY web/ ./
RUN pnpm run build


# Golang Build
FROM golang:1.24-alpine AS go_builder
WORKDIR /usr/src
COPY go.* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o mindscape .
RUN go install github.com/pressly/goose/v3/cmd/goose@latest
RUN go install github.com/adamkali/egg_cli@latest

# Final image 
FROM alpine:latest AS app

RUN apk add --no-cache ffmpeg
### If you are not using React or any other frontend you can comment out this section
COPY --from=node_builder /usr/src/web/dist /app/web/dist
COPY --from=go_builder /usr/src/mindscape /app/
## Get goose and egg_cli
COPY --from=go_builder /go/bin/goose /app/
COPY --from=go_builder /go/bin/egg_cli /app/

## Set permissions
RUN chmod +x /app/egg_cli
RUN chmod +x /app/goose
## Add those executables to the path and user
ENV PATH="/app:${PATH}"

EXPOSE 60000

WORKDIR /app

# Generate production.yaml from environment variables using egg_cli
RUN ./egg_cli env -e production
RUN if [ -f ./config/production.yaml ]; then echo "config/production.yaml generated successfully"; else echo "config/production.yaml generation failed"; exit 32; fi

## Run Migrations
RUN ./mindscape db up -e production 

## Run the server
CMD ["./mindscape", "-e", "production"]
