# Generated by egg v0.0.1

## Build the Frontend with Node.js
### If you are not using React you can comment out this section
FROM node:22-alpine AS node_builder
WORKDIR /usr/src/web
COPY web/package.json ./
### use pnpm
RUN npm install -g pnpm && pnpm install
COPY web/ ./
RUN pnpm run build


FROM golang:1.24-alpine AS go_builder
WORKDIR /usr/src
COPY go.* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o mindscape .

# Final image 
FROM alpine:latest AS app

## install ffmpeg for image processing
RUN apk add --no-cache ffmpeg

## 
### If you are not using React or any other frontend you can comment out this section
COPY --from=node_builder /usr/src/web/dist /app/web/dist
COPY --from=go_builder /usr/src/mindscape /app/
## Run Migrations
# RUN /app/mindscape db up -e production # Do not know why this is not woking :(
CMD ["/app/mindscape", "-e", "production"]
