services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindscape
    environment:
      - EGG_CACHE_DB=${EGG_CACHE_DB}
      - EGG_CACHE_HOST=${EGG_CACHE_HOST}
      - EGG_CACHE_PASSWORD=${EGG_CACHE_PASSWORD}
      - EGG_CACHE_PORT=${EGG_CACHE_PORT}  
      - EGG_CACHE_USERNAME=""
      - EGG_COPYRIGHT_AUTHOR=${EGG_COPYRIGHT_AUTHOR}
      - EGG_COPYRIGHT_YEAR=${EGG_COPYRIGHT_YEAR}
      - EGG_DATABASE_DBNAME=${EGG_DATABASE_DBNAME}
      - EGG_DATABASE_HOST=${EGG_DATABASE_HOST}
      - EGG_DATABASE_MIGRATION_DESTINATION=${EGG_DATABASE_MIGRATION_DESTINATION}
      - EGG_DATABASE_MIGRATION_PROTOCOL=${EGG_DATABASE_MIGRATION_PROTOCOL}
      - EGG_DATABASE_PASSWORD=${EGG_DATABASE_PASSWORD}
      - EGG_DATABASE_PORT=5432
      - EGG_DATABASE_QUERIES_LOCATION=${EGG_DATABASE_QUERIES_LOCATION}
      - EGG_DATABASE_SQLC_REPOSITORY_LOCATION=${EGG_DATABASE_SQLC_REPOSITORY_LOCATION}
      - EGG_DATABASE_SQLC_SCHEMA=${EGG_DATABASE_SQLC_SCHEMA}
      - EGG_DATABASE_SQLC_SQL_OR_GO=${EGG_DATABASE_SQLC_SQL_OR_GO}
      - EGG_DATABASE_USERNAME=${EGG_DATABASE_USERNAME}
      - EGG_LICENSE=${EGG_LICENSE}
      - EGG_NAME=${EGG_NAME}
      - EGG_NAMESPACE=${EGG_NAMESPACE}
      - EGG_S3_ACCESS=${EGG_S3_ACCESS}
      - EGG_S3_SECRET=${EGG_S3_SECRET}
      - EGG_S3_URL=${EGG_S3_URL}
      - EGG_SEMVER=${EGG_SEMVER}
      - EGG_SERVER_FRONTEND_API=${EGG_SERVER_FRONTEND_API}
      - EGG_SERVER_FRONTEND_DIR=${EGG_SERVER_FRONTEND_DIR}
      - EGG_SERVER_JWT=${EGG_SERVER_JWT}
      - EGG_SERVER_PORT=${EGG_SERVER_PORT}

    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://127.0.0.1:60000/_health
      interval: 5s
      timeout: 20s
      retries: 10
