version: '3.8'

services:
  mindscape:
    build:
      context: .
      dockerfile: Local.Dockerfile
      target: dev
    container_name: mindscape-local
    ports:
      - "60000:60000"
    volumes:
      - ./config:/usr/src/config:ro
      - .:/usr/src
      - /usr/src/web/node_modules
      - /usr/src/web/
    restart: unless-stopped
