/* Generated by egg v0.0.1

Copyright © 2025 Adam Kali  

This is made by the Full Stack Template
*/
package main

import (
    _ "github.com/adamkali/mindscape/docs"
	"github.com/adamkali/mindscape/cmd"
)

// @Title mindscape 
// @Schemes http
// @Version 0.0.1
// @Description This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
// @Contact.name Adam Kalinowski 
// @Contact.url https://github.com/adamkali/mindscape
// @License.name MIT
// @BasePath /api
func main() {
	cmd.Execute()
}
