# Generated by egg v0.0.1

# Makefile for mindscape project
.PHONY: help build dev test clean install docker swagger

.DEFAULT_GOAL := help

# Variables
APP_NAME := mindscape 
PORT := 60000
BINARY_DIR := ./tmp
BINARY_PATH := $(BINARY_DIR)/$(APP_NAME)
DOCKER_IMAGE := $(APP_NAME):latest
VERSIONED_IMAGE := $(DOCKER_IMAGE)-$(shell git rev-parse --short HEAD)

# Colors for output
RED := \033[0;31m
GREEN := \033[0;32m
YELLOW := \033[0;33m
BLUE := \033[0;34m
NC := \033[0m # No Color

help: ## Show this help message
	@echo "$(BLUE)$(APP_NAME) - Available Commands$(NC)"
	@echo ""
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  $(GREEN)%-20s$(NC) %s\n", $$1, $$2}' $(MAKEFILE_LIST)

# Setup
install: ## Install all dependencies
	@echo "$(YELLOW)Installing Go dependencies...$(NC)"
	go mod download
	go mod tidy
	@if [ -d "./frontend" ]; then \
		echo "$(YELLOW)Installing frontend dependencies...$(NC)"; \
		cd ./frontend && pnpm install; \
	fi

setup: install ## Setup development environment
	@echo "$(YELLOW)Setting up development environment...$(NC)"
	@mkdir -p $(BINARY_DIR)
	@mkdir -p ./logs
	@echo "$(GREEN)Development environment ready!$(NC)"

# Build
build-backend: ## Build backend binary
	@echo "$(YELLOW)Building backend...$(NC)"
	@mkdir -p $(BINARY_DIR)
	go build -ldflags="-s -w" -o $(BINARY_PATH) .
	@echo "$(GREEN)Backend built successfully: $(BINARY_PATH)$(NC)"

build-frontend: ## Build frontend
	@if [ -d "./frontend" ]; then \
		echo "$(YELLOW)Building frontend...$(NC)"; \
		cd ./frontend && pnpm format && pnpm build; \
		echo "$(GREEN)Frontend built successfully$(NC)"; \
	else \
		echo "$(YELLOW)No frontend directory found, skipping...$(NC)"; \
	fi

build: build-backend build-frontend ## Build all components

swagger: ## Generate Swagger documentation
	@echo "$(YELLOW)Generating Swagger documentation...$(NC)"
	@if [ -f "$(BINARY_PATH)" ]; then \
		$(BINARY_PATH) swag; \
		echo "$(GREEN)Swagger documentation generated$(NC)"; \
	else \
		echo "$(RED)Binary not found. Run 'make build-backend' first$(NC)"; \
		exit 1; \
	fi

# Development Servers
dev: ## Start development server with hot reload
	@echo "$(YELLOW)Starting development server with hot reload...$(NC)"
	air

dev-backend: build-backend ## Start backend development server
	@echo "$(YELLOW)Starting backend server...$(NC)"
	$(BINARY_PATH) up


# Testing
test: ## Run all tests
	@echo "$(YELLOW)Running tests...$(NC)"
	go test -v ./...
	@echo "$(GREEN)All tests passed!$(NC)"

test-coverage: ## Run tests with coverage report
	@echo "$(YELLOW)Running tests with coverage...$(NC)"
	go test -coverprofile=coverage.out ./...
	go tool cover -html=coverage.out -o coverage.html
	@echo "$(GREEN)Coverage report generated: coverage.html$(NC)"

test-race: ## Run tests with race detection
	@echo "$(YELLOW)Running tests with race detection...$(NC)"
	go test -race -v ./...

benchmark: ## Run benchmark tests
	@echo "$(YELLOW)Running benchmarks...$(NC)"
	go test -bench=. -benchmem ./...

# Docker Operations
docker-build: ## Build Docker image
	@echo "$(YELLOW)Building Docker image...$(NC)"
	docker build -t $(DOCKER_IMAGE) .
	@echo "$(GREEN)Docker image built: $(DOCKER_IMAGE)$(NC)"

docker-run: docker-build ## Run application in Docker
	@echo "$(YELLOW)Running application in Docker...$(NC)"
	docker run -p $(PORT):$(PORT) $(DOCKER_IMAGE)

docker-compose-up: ## Start services with docker-compose
	@echo "$(YELLOW)Starting services with docker-compose...$(NC)"
	docker-compose up -d

docker-compose-down: ## Stop services with docker-compose
	@echo "$(YELLOW)Stopping services with docker-compose...$(NC)"
	docker-compose down

docker-logs: ## View Docker container logs
	docker-compose logs -f

clean: ## Clean build artifacts
	@echo "$(YELLOW)Cleaning build artifacts...$(NC)"
	@rm -rf $(BINARY_DIR)
	@rm -f coverage.out coverage.html
	@echo "$(GREEN)Clean complete$(NC)"

