# Generated by egg v0.0.1
# Makefile for mindscape project
.PHONY: help build dev test clean install docker swagger

.DEFAULT_GOAL := help

# Variables
APP_NAME := mindscape 
PORT := 60000
BINARY_DIR := ./tmp
BINARY_PATH := $(BINARY_DIR)/$(APP_NAME)
DOCKER_IMAGE := $(APP_NAME):latest
VERSIONED_IMAGE := $(DOCKER_IMAGE)-$(shell git rev-parse --short HEAD)

# Colors for output
RED := \033[0;31m
GREEN := \033[0;32m
YELLOW := \033[0;33m
BLUE := \033[0;34m
NC := \033[0m # No Color

help: ## Show this help message
	@echo "$(BLUE)$(APP_NAME) - Available Commands$(NC)"
	@echo ""
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  $(GREEN)%-20s$(NC) %s\n", $$1, $$2}' $(MAKEFILE_LIST)

# Setup
install: ## Install all dependencies
	@echo "$(YELLOW)Installing Go dependencies...$(NC)"
	go mod download
	go mod tidy
	@if [ -d "./web" ]; then \
		echo "$(YELLOW)Installing frontend dependencies...$(NC)"; \
		cd ./web && pnpm install; \
	fi

setup: install ## Setup development environment
	@echo "$(YELLOW)Setting up development environment...$(NC)"
	@mkdir -p $(BINARY_DIR)
	@mkdir -p ./logs
	@echo "$(GREEN)Development environment ready!$(NC)"

# Build
build-backend: build-frontend ## Build backend binary
	@echo "$(YELLOW)Building backend...$(NC)"
	@mkdir -p $(BINARY_DIR)
	go build -buildvcs=false -ldflags="-s -w" -o $(BINARY_PATH) .
	@echo "$(GREEN)Backend built successfully: $(BINARY_PATH)$(NC)"

build-debug: build-frontend ## Build backend binary with debug symbols for delve
	@echo "$(YELLOW)Building backend with debug symbols...$(NC)"
	@mkdir -p $(BINARY_DIR)
	go build -buildvcs=false -gcflags="all=-N -l" -o $(BINARY_PATH) .
	@echo "$(GREEN)Debug backend built successfully: $(BINARY_PATH)$(NC)"

build-frontend: ## Build frontend
	@if [ -d "./web" ]; then \
		if command -v pnpm > /dev/null 2>&1; then \
			echo "$(YELLOW)Building frontend...$(NC)"; \
			cd ./web && pnpm build; \
			echo "$(GREEN)Frontend built successfully$(NC)"; \
		else \
			echo "$(YELLOW)pnpm not found, skipping frontend build (Docker uses separate container)$(NC)"; \
		fi \
	else \
		echo "$(YELLOW)No web directory found, skipping...$(NC)"; \
	fi

build: build-backend build-frontend ## Build all components

swagger: ## Generate Swagger documentation
	@echo "$(YELLOW)Generating Swagger documentation...$(NC)"
	@if [ -f $(BINARY_PATH) ]; then \
		$(BINARY_PATH) swag; \
		echo "$(GREEN)Swagger documentation generated$(NC)"; \
	else \
		echo "$(RED)Binary not found. Run 'make build-backend' first$(NC)"; \
		exit 1; \
	fi

swag: build-backend swagger

gen: 
	@echo "$(YELLOW)Generating Sql Client from schema...$(NC)"
	@if [ -f $(BINARY_PATH) ]; then \
		$(BINARY_PATH) db gen; \
		echo "$(GREEN)Sqlc Succesfully Generated Database Client$(NC)"; \
	else \
		echo "$(RED)Binary not found. Run 'make build-backend' first$(NC)"; \
		exit 1; \
	fi

# Development Servers
dev: ## Start development server with hot reload
	@echo "$(YELLOW)Starting development server with hot reload...$(NC)"
	air

dev-backend: build-backend ## Start backend development server
	@echo "$(YELLOW)Starting backend server...$(NC)"
	$(BINARY_PATH)

run:
	@echo "$(YELLOW)Running script...$(NC)"
	bash ./scripts/run.sh

# Testing
test: ## Run all tests
	@echo "$(YELLOW)Running tests...$(NC)"
	go test -v ./...
	@echo "$(GREEN)All tests passed!$(NC)"

test-coverage: ## Run tests with coverage report
	@echo "$(YELLOW)Running tests with coverage...$(NC)"
	go test -coverprofile=coverage.out ./...
	go tool cover -html=coverage.out -o coverage.html
	@echo "$(GREEN)Coverage report generated: coverage.html$(NC)"

test-race: ## Run tests with race detection
	@echo "$(YELLOW)Running tests with race detection...$(NC)"
	go test -race -v ./...

benchmark: ## Run benchmark tests
	@echo "$(YELLOW)Running benchmarks...$(NC)"
	go test -bench=. -benchmem ./...

# Docker Operations
docker-build: ## Build Docker image
	@echo "$(YELLOW)Building Docker image...$(NC)"
	docker build -t $(DOCKER_IMAGE) .
	@echo "$(GREEN)Docker image built: $(DOCKER_IMAGE)$(NC)"

docker-run: docker-build ## Run application in Docker
	@echo "$(YELLOW)Running application in Docker...$(NC)"
	docker run -p $(PORT):$(PORT) $(DOCKER_IMAGE)

docker-compose-up: ## Start services with docker-compose
	@echo "$(YELLOW)Starting services with docker-compose...$(NC)"
	docker-compose up -d

docker-compose-down: ## Stop services with docker-compose
	@echo "$(YELLOW)Stopping services with docker-compose...$(NC)"
	docker-compose down

docker-logs: ## View Docker container logs
	docker-compose logs -f

dev-docker: ## Start development environment with Docker (hot reload + debugging)
	@echo "$(YELLOW)Building swagger documentation...$(NC)"
	$(BINARY_PATH) swag
	@echo "$(YELLOW)Starting development Docker environment...$(NC)"
	@echo "$(BLUE)Backend will be available at http://localhost:60000$(NC)"
	@echo "$(BLUE)Frontend will be available at http://localhost:5173$(NC)"
	@echo "$(BLUE)Delve debugger will be available at localhost:2345$(NC)"
	@echo "$(YELLOW)Tip: Use 'make dev-docker-logs-backend' or 'make dev-docker-logs-frontend' to view individual logs$(NC)"
	docker-compose -f dev.docker-compose.yml up --build

dev-docker-down: ## Stop development Docker environment
	@echo "$(YELLOW)Stopping development Docker environment...$(NC)"
	docker-compose -f dev.docker-compose.yml down

dev-docker-logs: ## View all Docker container logs
	docker-compose -f dev.docker-compose.yml logs -f

dev-docker-logs-backend: ## View backend container logs only
	@echo "$(BLUE)Viewing backend logs (Ctrl+C to exit)...$(NC)"
	docker-compose -f dev.docker-compose.yml logs -f backend

dev-docker-logs-frontend: ## View frontend container logs only
	@echo "$(BLUE)Viewing frontend logs (Ctrl+C to exit)...$(NC)"
	docker-compose -f dev.docker-compose.yml logs -f frontend

dev-docker-restart-backend: ## Restart only the backend container
	@echo "$(YELLOW)Restarting backend container...$(NC)"
	docker-compose -f dev.docker-compose.yml restart backend

dev-docker-restart-frontend: ## Restart only the frontend container
	@echo "$(YELLOW)Restarting frontend container...$(NC)"
	docker-compose -f dev.docker-compose.yml restart frontend

dev-docker-rebuild: ## Rebuild and restart development Docker environment
	@echo "$(YELLOW)Rebuilding development Docker environment...$(NC)"
	docker-compose -f dev.docker-compose.yml up --build --force-recreate

prod-setup: ## Setup production environment and start server
	@echo "$(YELLOW)Setting up production environment...$(NC)"
	@if [ -f ./config/production.yaml ]; then \
		echo "$(GREEN)config/production.yaml generated successfully$(NC)"; \
	else \
		echo "$(RED)config/production.yaml generation failed$(NC)"; \
		exit 32; \
	fi
	@echo "$(YELLOW)Running database migrations...$(NC)"
# ./mindscape db up -e production
	@echo "$(YELLOW)Starting production server...$(NC)"
	./mindscape -e production

dev-setup: ## Setup development environment and start server
	@echo "$(YELLOW)Setting up development environment...$(NC)"
	@if [ -f ./config/development.yaml ]; then \
		echo "$(GREEN)config/development.yaml generated successfully$(NC)"; \
	else \
		echo "$(RED)config/development.yaml generation failed$(NC)"; \
		exit 32; \
	fi
	@echo "$(YELLOW)Running database migrations...$(NC)"
	./mindscape db up -e development
	@echo "$(YELLOW)Starting development server...$(NC)"
	./mindscape

clean: ## Clean build artifacts
	@echo "$(YELLOW)Cleaning build artifacts...$(NC)"
	@rm -rf $(BINARY_DIR)
	@rm -f coverage.out coverage.html
	@echo "$(GREEN)Clean complete$(NC)"

