/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BookmarkResponse,
  BookmarksResponse,
  MoveBookmarkRequest,
  RepositoryCreateBookmarkParams,
} from '../models/index';
import {
    BookmarkResponseFromJSON,
    BookmarkResponseToJSON,
    BookmarksResponseFromJSON,
    BookmarksResponseToJSON,
    MoveBookmarkRequestFromJSON,
    MoveBookmarkRequestToJSON,
    RepositoryCreateBookmarkParamsFromJSON,
    RepositoryCreateBookmarkParamsToJSON,
} from '../models/index';

export interface CreateBookmarkRequest {
    authorization: string;
    createBookmarkRequest: RepositoryCreateBookmarkParams;
}

export interface DeleteBookmarkRequest {
    authorization: string;
    bookmarkId: string;
}

export interface GetBookmarksRequest {
    authorization: string;
    parentId: string;
}

export interface MoveBookmarkOperationRequest {
    authorization: string;
    moveBookmarkRequest: MoveBookmarkRequest;
}

/**
 * 
 */
export class BookmarksApi extends runtime.BaseAPI {

    /**
     * Create a new Bookmark by Authorization Header
     * Create a new Bookmark
     */
    async createBookmarkRaw(requestParameters: CreateBookmarkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookmarkResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling createBookmark().'
            );
        }

        if (requestParameters['createBookmarkRequest'] == null) {
            throw new runtime.RequiredError(
                'createBookmarkRequest',
                'Required parameter "createBookmarkRequest" was null or undefined when calling createBookmark().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/bookmarks`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RepositoryCreateBookmarkParamsToJSON(requestParameters['createBookmarkRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookmarkResponseFromJSON(jsonValue));
    }

    /**
     * Create a new Bookmark by Authorization Header
     * Create a new Bookmark
     */
    async createBookmark(requestParameters: CreateBookmarkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookmarkResponse> {
        const response = await this.createBookmarkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a Bookmark by Authorization Header, and my a ParentFolderId [parent_id].
     * Delete a Bookmark
     */
    async deleteBookmarkRaw(requestParameters: DeleteBookmarkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookmarksResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling deleteBookmark().'
            );
        }

        if (requestParameters['bookmarkId'] == null) {
            throw new runtime.RequiredError(
                'bookmarkId',
                'Required parameter "bookmarkId" was null or undefined when calling deleteBookmark().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/bookmarks/folder/{bookmark_id}`.replace(`{${"bookmark_id"}}`, encodeURIComponent(String(requestParameters['bookmarkId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookmarksResponseFromJSON(jsonValue));
    }

    /**
     * Delete a Bookmark by Authorization Header, and my a ParentFolderId [parent_id].
     * Delete a Bookmark
     */
    async deleteBookmark(requestParameters: DeleteBookmarkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookmarksResponse> {
        const response = await this.deleteBookmarkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all Bookmarks by Authorization Header and by the ParentFolderId [parent_id]
     * Get Bookmarks By Folder ID
     */
    async getBookmarksRaw(requestParameters: GetBookmarksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookmarksResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling getBookmarks().'
            );
        }

        if (requestParameters['parentId'] == null) {
            throw new runtime.RequiredError(
                'parentId',
                'Required parameter "parentId" was null or undefined when calling getBookmarks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/bookmarks/folder/{parent_id}`.replace(`{${"parent_id"}}`, encodeURIComponent(String(requestParameters['parentId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookmarksResponseFromJSON(jsonValue));
    }

    /**
     * Get all Bookmarks by Authorization Header and by the ParentFolderId [parent_id]
     * Get Bookmarks By Folder ID
     */
    async getBookmarks(requestParameters: GetBookmarksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookmarksResponse> {
        const response = await this.getBookmarksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Move a Bookmark by Authorization Header, and my a ParentFolderId [parent_id].
     * Move a Bookmark
     */
    async moveBookmarkRaw(requestParameters: MoveBookmarkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookmarksResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling moveBookmark().'
            );
        }

        if (requestParameters['moveBookmarkRequest'] == null) {
            throw new runtime.RequiredError(
                'moveBookmarkRequest',
                'Required parameter "moveBookmarkRequest" was null or undefined when calling moveBookmark().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/bookmarks`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MoveBookmarkRequestToJSON(requestParameters['moveBookmarkRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookmarksResponseFromJSON(jsonValue));
    }

    /**
     * Move a Bookmark by Authorization Header, and my a ParentFolderId [parent_id].
     * Move a Bookmark
     */
    async moveBookmark(requestParameters: MoveBookmarkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookmarksResponse> {
        const response = await this.moveBookmarkRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
