/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RepositoryCreateFolderParams,
  ResponsesFolderResponse,
  ResponsesFoldersResponse,
} from '../models/index';
import {
    RepositoryCreateFolderParamsFromJSON,
    RepositoryCreateFolderParamsToJSON,
    ResponsesFolderResponseFromJSON,
    ResponsesFolderResponseToJSON,
    ResponsesFoldersResponseFromJSON,
    ResponsesFoldersResponseToJSON,
} from '../models/index';

export interface CreateFolderRequest {
    authorization: string;
    createFolderRequest: RepositoryCreateFolderParams;
}

export interface DeleteFolderRequest {
    folderId: string;
    authorization: string;
}

export interface GetFoldersRequest {
    folderId: string;
    authorization: string;
}

export interface GetRootFoldersRequest {
    authorization: string;
}

/**
 * 
 */
export class FoldersApi extends runtime.BaseAPI {

    /**
     * Create a new Folder by Authorization Header
     * Create a new Folder
     */
    async createFolderRaw(requestParameters: CreateFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponsesFolderResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling createFolder().'
            );
        }

        if (requestParameters['createFolderRequest'] == null) {
            throw new runtime.RequiredError(
                'createFolderRequest',
                'Required parameter "createFolderRequest" was null or undefined when calling createFolder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/folders`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RepositoryCreateFolderParamsToJSON(requestParameters['createFolderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponsesFolderResponseFromJSON(jsonValue));
    }

    /**
     * Create a new Folder by Authorization Header
     * Create a new Folder
     */
    async createFolder(requestParameters: CreateFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponsesFolderResponse> {
        const response = await this.createFolderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a Folder by Authorization Header and tries to cascade delete
     * Delete a Folder
     */
    async deleteFolderRaw(requestParameters: DeleteFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponsesFolderResponse>> {
        if (requestParameters['folderId'] == null) {
            throw new runtime.RequiredError(
                'folderId',
                'Required parameter "folderId" was null or undefined when calling deleteFolder().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling deleteFolder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/folders/{folder_id}`.replace(`{${"folder_id"}}`, encodeURIComponent(String(requestParameters['folderId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponsesFolderResponseFromJSON(jsonValue));
    }

    /**
     * Delete a Folder by Authorization Header and tries to cascade delete
     * Delete a Folder
     */
    async deleteFolder(requestParameters: DeleteFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponsesFolderResponse> {
        const response = await this.deleteFolderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the Folders associated with the user under A Parent Folder by Authorization Header and will also try to get the children of the folder as well
     * Get the Folders associated with the user under A Parent Folder
     */
    async getFoldersRaw(requestParameters: GetFoldersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponsesFoldersResponse>> {
        if (requestParameters['folderId'] == null) {
            throw new runtime.RequiredError(
                'folderId',
                'Required parameter "folderId" was null or undefined when calling getFolders().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling getFolders().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/folders/{folder_id}`.replace(`{${"folder_id"}}`, encodeURIComponent(String(requestParameters['folderId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponsesFoldersResponseFromJSON(jsonValue));
    }

    /**
     * Get the Folders associated with the user under A Parent Folder by Authorization Header and will also try to get the children of the folder as well
     * Get the Folders associated with the user under A Parent Folder
     */
    async getFolders(requestParameters: GetFoldersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponsesFoldersResponse> {
        const response = await this.getFoldersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the Root Folders associated with the user by Authorization Header and will also try to get the children of the folder as well
     * Get the Root Folders associated with the user
     */
    async getRootFoldersRaw(requestParameters: GetRootFoldersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponsesFoldersResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling getRootFolders().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/folders`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponsesFoldersResponseFromJSON(jsonValue));
    }

    /**
     * Get the Root Folders associated with the user by Authorization Header and will also try to get the children of the folder as well
     * Get the Root Folders associated with the user
     */
    async getRootFolders(requestParameters: GetRootFoldersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponsesFoldersResponse> {
        const response = await this.getRootFoldersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
