/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateHouseholdRequest,
  CreateInviteRequest,
  HouseholdResponse,
  HouseholdsResponse,
  InvitesResponse,
  MembersResponse,
  StringResponse,
} from '../models/index';
import {
    CreateHouseholdRequestFromJSON,
    CreateHouseholdRequestToJSON,
    CreateInviteRequestFromJSON,
    CreateInviteRequestToJSON,
    HouseholdResponseFromJSON,
    HouseholdResponseToJSON,
    HouseholdsResponseFromJSON,
    HouseholdsResponseToJSON,
    InvitesResponseFromJSON,
    InvitesResponseToJSON,
    MembersResponseFromJSON,
    MembersResponseToJSON,
    StringResponseFromJSON,
    StringResponseToJSON,
} from '../models/index';

export interface AcceptInviteRequest {
    code: string;
}

export interface CreateHouseholdOperationRequest {
    createHouseholdRequest: CreateHouseholdRequest;
}

export interface CreateInviteOperationRequest {
    householdId: string;
    createInviteRequest: CreateInviteRequest;
}

export interface DeleteHouseholdRequest {
    householdId: string;
}

export interface GetHouseholdMembersRequest {
    householdId: string;
}

export interface LeaveHouseholdRequest {
    householdId: string;
}

export interface RejectInviteRequest {
    code: string;
}

export interface RemoveMemberRequest {
    householdId: string;
    userId: string;
}

/**
 * 
 */
export class HouseholdsApi extends runtime.BaseAPI {

    /**
     * Accept a pending invite by its code.
     * Accept an Invite
     */
    async acceptInviteRaw(requestParameters: AcceptInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HouseholdResponse>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling acceptInvite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/households/invites/{code}/accept`.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HouseholdResponseFromJSON(jsonValue));
    }

    /**
     * Accept a pending invite by its code.
     * Accept an Invite
     */
    async acceptInvite(requestParameters: AcceptInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HouseholdResponse> {
        const response = await this.acceptInviteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a Household; the caller becomes its owner and admin.
     * Create a new Household
     */
    async createHouseholdRaw(requestParameters: CreateHouseholdOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HouseholdResponse>> {
        if (requestParameters['createHouseholdRequest'] == null) {
            throw new runtime.RequiredError(
                'createHouseholdRequest',
                'Required parameter "createHouseholdRequest" was null or undefined when calling createHousehold().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/households`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateHouseholdRequestToJSON(requestParameters['createHouseholdRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HouseholdResponseFromJSON(jsonValue));
    }

    /**
     * Create a Household; the caller becomes its owner and admin.
     * Create a new Household
     */
    async createHousehold(requestParameters: CreateHouseholdOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HouseholdResponse> {
        const response = await this.createHouseholdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Invite a user to a household (admin only).
     * Create an Invite
     */
    async createInviteRaw(requestParameters: CreateInviteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringResponse>> {
        if (requestParameters['householdId'] == null) {
            throw new runtime.RequiredError(
                'householdId',
                'Required parameter "householdId" was null or undefined when calling createInvite().'
            );
        }

        if (requestParameters['createInviteRequest'] == null) {
            throw new runtime.RequiredError(
                'createInviteRequest',
                'Required parameter "createInviteRequest" was null or undefined when calling createInvite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/households/{household_id}/invites`.replace(`{${"household_id"}}`, encodeURIComponent(String(requestParameters['householdId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateInviteRequestToJSON(requestParameters['createInviteRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringResponseFromJSON(jsonValue));
    }

    /**
     * Invite a user to a household (admin only).
     * Create an Invite
     */
    async createInvite(requestParameters: CreateInviteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringResponse> {
        const response = await this.createInviteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a household (owner only). Cascades members and invites.
     * Delete a Household
     */
    async deleteHouseholdRaw(requestParameters: DeleteHouseholdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringResponse>> {
        if (requestParameters['householdId'] == null) {
            throw new runtime.RequiredError(
                'householdId',
                'Required parameter "householdId" was null or undefined when calling deleteHousehold().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/households/{household_id}`.replace(`{${"household_id"}}`, encodeURIComponent(String(requestParameters['householdId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringResponseFromJSON(jsonValue));
    }

    /**
     * Delete a household (owner only). Cascades members and invites.
     * Delete a Household
     */
    async deleteHousehold(requestParameters: DeleteHouseholdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringResponse> {
        const response = await this.deleteHouseholdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a household\'s members. Returns 404 to non-members.
     * Get Household Members
     */
    async getHouseholdMembersRaw(requestParameters: GetHouseholdMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MembersResponse>> {
        if (requestParameters['householdId'] == null) {
            throw new runtime.RequiredError(
                'householdId',
                'Required parameter "householdId" was null or undefined when calling getHouseholdMembers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/households/{household_id}/members`.replace(`{${"household_id"}}`, encodeURIComponent(String(requestParameters['householdId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MembersResponseFromJSON(jsonValue));
    }

    /**
     * Get a household\'s members. Returns 404 to non-members.
     * Get Household Members
     */
    async getHouseholdMembers(requestParameters: GetHouseholdMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MembersResponse> {
        const response = await this.getHouseholdMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all households the caller is a member of.
     * Get My Households
     */
    async getMyHouseholdsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HouseholdsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/households`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HouseholdsResponseFromJSON(jsonValue));
    }

    /**
     * Get all households the caller is a member of.
     * Get My Households
     */
    async getMyHouseholds(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HouseholdsResponse> {
        const response = await this.getMyHouseholdsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get the caller\'s pending, unexpired household invites.
     * Get My Pending Invites
     */
    async getMyInvitesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvitesResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/households/invites`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvitesResponseFromJSON(jsonValue));
    }

    /**
     * Get the caller\'s pending, unexpired household invites.
     * Get My Pending Invites
     */
    async getMyInvites(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvitesResponse> {
        const response = await this.getMyInvitesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Leave a household. The owner cannot leave — they must delete it.
     * Leave a Household
     */
    async leaveHouseholdRaw(requestParameters: LeaveHouseholdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringResponse>> {
        if (requestParameters['householdId'] == null) {
            throw new runtime.RequiredError(
                'householdId',
                'Required parameter "householdId" was null or undefined when calling leaveHousehold().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/households/{household_id}/leave`.replace(`{${"household_id"}}`, encodeURIComponent(String(requestParameters['householdId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringResponseFromJSON(jsonValue));
    }

    /**
     * Leave a household. The owner cannot leave — they must delete it.
     * Leave a Household
     */
    async leaveHousehold(requestParameters: LeaveHouseholdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringResponse> {
        const response = await this.leaveHouseholdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reject (and delete) a pending invite by its code.
     * Reject an Invite
     */
    async rejectInviteRaw(requestParameters: RejectInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringResponse>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling rejectInvite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/households/invites/{code}/reject`.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringResponseFromJSON(jsonValue));
    }

    /**
     * Reject (and delete) a pending invite by its code.
     * Reject an Invite
     */
    async rejectInvite(requestParameters: RejectInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringResponse> {
        const response = await this.rejectInviteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a member from a household (admin only; not the owner).
     * Remove a Member
     */
    async removeMemberRaw(requestParameters: RemoveMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringResponse>> {
        if (requestParameters['householdId'] == null) {
            throw new runtime.RequiredError(
                'householdId',
                'Required parameter "householdId" was null or undefined when calling removeMember().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling removeMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/households/{household_id}/members/{user_id}`.replace(`{${"household_id"}}`, encodeURIComponent(String(requestParameters['householdId']))).replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringResponseFromJSON(jsonValue));
    }

    /**
     * Remove a member from a household (admin only; not the owner).
     * Remove a Member
     */
    async removeMember(requestParameters: RemoveMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringResponse> {
        const response = await this.removeMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
