/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BackgroundResponse,
  DeleteUserResponse,
  LoginRequest,
  LoginResponse,
  NewUserRequest,
  StringResponse,
  UpdateCredentialsRequest,
  UpdateUserResponse,
  UserResponse,
  UsersResponse,
  UsersSearchResponse,
} from '../models/index';
import {
    BackgroundResponseFromJSON,
    BackgroundResponseToJSON,
    DeleteUserResponseFromJSON,
    DeleteUserResponseToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    LoginResponseFromJSON,
    LoginResponseToJSON,
    NewUserRequestFromJSON,
    NewUserRequestToJSON,
    StringResponseFromJSON,
    StringResponseToJSON,
    UpdateCredentialsRequestFromJSON,
    UpdateCredentialsRequestToJSON,
    UpdateUserResponseFromJSON,
    UpdateUserResponseToJSON,
    UserResponseFromJSON,
    UserResponseToJSON,
    UsersResponseFromJSON,
    UsersResponseToJSON,
    UsersSearchResponseFromJSON,
    UsersSearchResponseToJSON,
} from '../models/index';

export interface DeleteUserByUUIDRequest {
    userId: string;
}

export interface GetUserBackgroundRequest {
    background: string;
}

export interface LoginOperationRequest {
    loginRequest: LoginRequest;
}

export interface SearchUsersRequest {
    q: string;
}

export interface SetUserBackgroundRequest {
    background: string;
}

export interface SignupRequest {
    signupRequest: NewUserRequest;
}

export interface UpdateUserRequest {
    updateCredentialsRequest: UpdateCredentialsRequest;
}

export interface UploadBackgroundRequest {
    file: Blob;
}

export interface UploadProfilePictureRequest {
    file: Blob;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * get string by ID
     * Delete User by their UUID
     */
    async deleteUserByUUIDRaw(requestParameters: DeleteUserByUUIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteUserResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteUserByUUID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/users/{user_id}`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteUserResponseFromJSON(jsonValue));
    }

    /**
     * get string by ID
     * Delete User by their UUID
     */
    async deleteUserByUUID(requestParameters: DeleteUserByUUIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteUserResponse> {
        const response = await this.deleteUserByUUIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the Current User by the uuid storred in the Claims header
     * Get Current User
     */
    async getCurrentLoggedInUserRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/users/current`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Get the Current User by the uuid storred in the Claims header
     * Get Current User
     */
    async getCurrentLoggedInUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.getCurrentLoggedInUserRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get User Profile by Authorization Header
     * Get User Profile by Authorization Header
     */
    async getProfilePictureRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/users/profile`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringResponseFromJSON(jsonValue));
    }

    /**
     * Get User Profile by Authorization Header
     * Get User Profile by Authorization Header
     */
    async getProfilePicture(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringResponse> {
        const response = await this.getProfilePictureRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get User Background Choice
     * Get User Background Choice
     */
    async getUserBackgroundRaw(requestParameters: GetUserBackgroundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringResponse>> {
        if (requestParameters['background'] == null) {
            throw new runtime.RequiredError(
                'background',
                'Required parameter "background" was null or undefined when calling getUserBackground().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['background'] != null) {
            queryParameters['background'] = requestParameters['background'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/users/background`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringResponseFromJSON(jsonValue));
    }

    /**
     * Get User Background Choice
     * Get User Background Choice
     */
    async getUserBackground(requestParameters: GetUserBackgroundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringResponse> {
        const response = await this.getUserBackgroundRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get User Backgrounds Uploaded to the server
     * Get User Background Choices
     */
    async getUserBackgroundChoicesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackgroundResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/users/background/choices`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackgroundResponseFromJSON(jsonValue));
    }

    /**
     * Get User Backgrounds Uploaded to the server
     * Get User Background Choices
     */
    async getUserBackgroundChoices(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackgroundResponse> {
        const response = await this.getUserBackgroundChoicesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get All Users. Must be Admin using the new mediator pattern
     * Get All Users
     */
    async getUsersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/users/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersResponseFromJSON(jsonValue));
    }

    /**
     * Get All Users. Must be Admin using the new mediator pattern
     * Get All Users
     */
    async getUsers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersResponse> {
        const response = await this.getUsersRaw(initOverrides);
        return await response.value();
    }

    /**
     * to a user account with either email or username
     * Login
     */
    async loginRaw(requestParameters: LoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResponse>> {
        if (requestParameters['loginRequest'] == null) {
            throw new runtime.RequiredError(
                'loginRequest',
                'Required parameter "loginRequest" was null or undefined when calling login().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseFromJSON(jsonValue));
    }

    /**
     * to a user account with either email or username
     * Login
     */
    async login(requestParameters: LoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResponse> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke the session belonging to the refresh-token cookie and clear it. Other browsers/devices stay logged in.
     * Logout this device
     */
    async logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/refresh`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringResponseFromJSON(jsonValue));
    }

    /**
     * Revoke the session belonging to the refresh-token cookie and clear it. Other browsers/devices stay logged in.
     * Logout this device
     */
    async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringResponse> {
        const response = await this.logoutRaw(initOverrides);
        return await response.value();
    }

    /**
     * Exchange the httpOnly refresh-token cookie for a new access JWT and a rotated refresh cookie. Unauthenticated by design: the refresh cookie is the credential.
     * Refresh the access token
     */
    async refreshRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/refresh`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseFromJSON(jsonValue));
    }

    /**
     * Exchange the httpOnly refresh-token cookie for a new access JWT and a rotated refresh cookie. Unauthenticated by design: the refresh cookie is the credential.
     * Refresh the access token
     */
    async refresh(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResponse> {
        const response = await this.refreshRaw(initOverrides);
        return await response.value();
    }

    /**
     * Autocomplete usernames (max 10, excludes caller, no PII).
     * Search Users by username
     */
    async searchUsersRaw(requestParameters: SearchUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersSearchResponse>> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling searchUsers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/users/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersSearchResponseFromJSON(jsonValue));
    }

    /**
     * Autocomplete usernames (max 10, excludes caller, no PII).
     * Search Users by username
     */
    async searchUsers(requestParameters: SearchUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersSearchResponse> {
        const response = await this.searchUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set User Background Choice by background name by query param.
     * Set User Background
     */
    async setUserBackgroundRaw(requestParameters: SetUserBackgroundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringResponse>> {
        if (requestParameters['background'] == null) {
            throw new runtime.RequiredError(
                'background',
                'Required parameter "background" was null or undefined when calling setUserBackground().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['background'] != null) {
            queryParameters['background'] = requestParameters['background'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/users/background`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringResponseFromJSON(jsonValue));
    }

    /**
     * Set User Background Choice by background name by query param.
     * Set User Background
     */
    async setUserBackground(requestParameters: SetUserBackgroundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringResponse> {
        const response = await this.setUserBackgroundRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Signup using the requests.NewUserRequest
     * Signup to the app
     */
    async signupRaw(requestParameters: SignupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResponse>> {
        if (requestParameters['signupRequest'] == null) {
            throw new runtime.RequiredError(
                'signupRequest',
                'Required parameter "signupRequest" was null or undefined when calling signup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/signup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewUserRequestToJSON(requestParameters['signupRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseFromJSON(jsonValue));
    }

    /**
     * Signup using the requests.NewUserRequest
     * Signup to the app
     */
    async signup(requestParameters: SignupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResponse> {
        const response = await this.signupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update User Credentials by id, Must be the same user in the jwt that is being updated
     * Update User Credentials
     */
    async updateUserRaw(requestParameters: UpdateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateUserResponse>> {
        if (requestParameters['updateCredentialsRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCredentialsRequest',
                'Required parameter "updateCredentialsRequest" was null or undefined when calling updateUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/users/creds`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCredentialsRequestToJSON(requestParameters['updateCredentialsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateUserResponseFromJSON(jsonValue));
    }

    /**
     * Update User Credentials by id, Must be the same user in the jwt that is being updated
     * Update User Credentials
     */
    async updateUser(requestParameters: UpdateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateUserResponse> {
        const response = await this.updateUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload a Background and set the User.Background  to be the uploaded background
     * Upload Background
     */
    async uploadBackgroundRaw(requestParameters: UploadBackgroundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringResponse>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadBackground().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/users/background`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringResponseFromJSON(jsonValue));
    }

    /**
     * Upload a Background and set the User.Background  to be the uploaded background
     * Upload Background
     */
    async uploadBackground(requestParameters: UploadBackgroundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringResponse> {
        const response = await this.uploadBackgroundRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload file
     * Upload file
     */
    async uploadProfilePictureRaw(requestParameters: UploadProfilePictureRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadProfilePicture().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/users/profile`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Upload file
     * Upload file
     */
    async uploadProfilePicture(requestParameters: UploadProfilePictureRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.uploadProfilePictureRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
