/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
	AddUserWidgetRequest,
	CoolifyActionResponse,
	CoolifyWidgetApplicationResponse,
	CoolifyWidgetServiceResponse,
	GithubCommitsResponse,
	GithubProfileResponse,
	GithubResponse,
	ResponsesUserWidgetResponse,
	ResponsesUserWidgetsResponse,
	ResponsesWidgetsResponse,
	WidgetResponse,
} from '../models/index';
import {
	AddUserWidgetRequestFromJSON,
	AddUserWidgetRequestToJSON,
	CoolifyActionResponseFromJSON,
	CoolifyActionResponseToJSON,
	CoolifyWidgetApplicationResponseFromJSON,
	CoolifyWidgetApplicationResponseToJSON,
	CoolifyWidgetServiceResponseFromJSON,
	CoolifyWidgetServiceResponseToJSON,
	GithubCommitsResponseFromJSON,
	GithubCommitsResponseToJSON,
	GithubProfileResponseFromJSON,
	GithubProfileResponseToJSON,
	GithubResponseFromJSON,
	GithubResponseToJSON,
	ResponsesUserWidgetResponseFromJSON,
	ResponsesUserWidgetResponseToJSON,
	ResponsesUserWidgetsResponseFromJSON,
	ResponsesUserWidgetsResponseToJSON,
	ResponsesWidgetsResponseFromJSON,
	ResponsesWidgetsResponseToJSON,
	WidgetResponseFromJSON,
	WidgetResponseToJSON,
} from '../models/index';
import * as runtime from '../runtime';

export interface AddUserWidgetOperationRequest {
	authorization: string;
	addUserWidgetRequest: AddUserWidgetRequest;
}

export interface GetGithubCommitsWidgetDataRequest {
	authorization: string;
	userWidgetId: string;
}

export interface GetGithubProfileWidgetDataRequest {
	authorization: string;
	userWidgetId: string;
}

export interface GetGithubWidgetDataRequest {
	authorization: string;
	userWidgetId: string;
}

export interface GetUserCoolifyApplicationsRequest {
	authorization: string;
	userWidgetId: string;
}

export interface GetUserCoolifyServicesRequest {
	authorization: string;
	userWidgetId: string;
}

export interface GetUserWidgetRequest {
	authorization: string;
	userWidgetId: string;
}

export interface GetUserWidgetsRequest {
	authorization: string;
}

export interface GetWidgetSchemaByIDRequest {
	schemaId: string;
}

export interface RestartCoolifyApplicationRequest {
	authorization: string;
	userWidgetId: string;
	appUuid: string;
}

export interface StartCoolifyApplicationRequest {
	authorization: string;
	userWidgetId: string;
	appUuid: string;
}

export interface StopCoolifyApplicationRequest {
	authorization: string;
	userWidgetId: string;
	appUuid: string;
}

/**
 *
 */
export class WidgetsApi extends runtime.BaseAPI {
	/**
	 * Add a Users Widget by their auth token. The config is defined by the configuration parameters as defined by the user and the schema.
	 * Add a Users Widget
	 */
	async addUserWidgetRaw(
		requestParameters: AddUserWidgetOperationRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<ResponsesUserWidgetResponse>> {
		if (requestParameters['authorization'] == null) {
			throw new runtime.RequiredError(
				'authorization',
				'Required parameter "authorization" was null or undefined when calling addUserWidget().',
			);
		}

		if (requestParameters['addUserWidgetRequest'] == null) {
			throw new runtime.RequiredError(
				'addUserWidgetRequest',
				'Required parameter "addUserWidgetRequest" was null or undefined when calling addUserWidget().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'application/json';

		if (requestParameters['authorization'] != null) {
			headerParameters['Authorization'] = String(
				requestParameters['authorization'],
			);
		}

		const response = await this.request(
			{
				path: `/widgets`,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: AddUserWidgetRequestToJSON(
					requestParameters['addUserWidgetRequest'],
				),
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			ResponsesUserWidgetResponseFromJSON(jsonValue),
		);
	}

	/**
	 * Add a Users Widget by their auth token. The config is defined by the configuration parameters as defined by the user and the schema.
	 * Add a Users Widget
	 */
	async addUserWidget(
		requestParameters: AddUserWidgetOperationRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<ResponsesUserWidgetResponse> {
		const response = await this.addUserWidgetRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Get a Users Github Commits Widget by their auth token and a path parameter to return only the commits data. This endpoint fetches commit history and may take longer.
	 * Get a Users Github Commits Widget Data
	 */
	async getGithubCommitsWidgetDataRaw(
		requestParameters: GetGithubCommitsWidgetDataRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<GithubCommitsResponse>> {
		if (requestParameters['authorization'] == null) {
			throw new runtime.RequiredError(
				'authorization',
				'Required parameter "authorization" was null or undefined when calling getGithubCommitsWidgetData().',
			);
		}

		if (requestParameters['userWidgetId'] == null) {
			throw new runtime.RequiredError(
				'userWidgetId',
				'Required parameter "userWidgetId" was null or undefined when calling getGithubCommitsWidgetData().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters['authorization'] != null) {
			headerParameters['Authorization'] = String(
				requestParameters['authorization'],
			);
		}

		const response = await this.request(
			{
				path: `/widgets/{user_widget_id}/github/commits`.replace(
					`{${'user_widget_id'}}`,
					encodeURIComponent(String(requestParameters['userWidgetId'])),
				),
				method: 'GET',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			GithubCommitsResponseFromJSON(jsonValue),
		);
	}

	/**
	 * Get a Users Github Commits Widget by their auth token and a path parameter to return only the commits data. This endpoint fetches commit history and may take longer.
	 * Get a Users Github Commits Widget Data
	 */
	async getGithubCommitsWidgetData(
		requestParameters: GetGithubCommitsWidgetDataRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<GithubCommitsResponse> {
		const response = await this.getGithubCommitsWidgetDataRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Get a Users Github Profile Widget by their auth token and a path parameter to return only the profile data. This is a fast endpoint that returns profile info quickly.
	 * Get a Users Github Profile Widget Data
	 */
	async getGithubProfileWidgetDataRaw(
		requestParameters: GetGithubProfileWidgetDataRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<GithubProfileResponse>> {
		if (requestParameters['authorization'] == null) {
			throw new runtime.RequiredError(
				'authorization',
				'Required parameter "authorization" was null or undefined when calling getGithubProfileWidgetData().',
			);
		}

		if (requestParameters['userWidgetId'] == null) {
			throw new runtime.RequiredError(
				'userWidgetId',
				'Required parameter "userWidgetId" was null or undefined when calling getGithubProfileWidgetData().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters['authorization'] != null) {
			headerParameters['Authorization'] = String(
				requestParameters['authorization'],
			);
		}

		const response = await this.request(
			{
				path: `/widgets/{user_widget_id}/github/profile`.replace(
					`{${'user_widget_id'}}`,
					encodeURIComponent(String(requestParameters['userWidgetId'])),
				),
				method: 'GET',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			GithubProfileResponseFromJSON(jsonValue),
		);
	}

	/**
	 * Get a Users Github Profile Widget by their auth token and a path parameter to return only the profile data. This is a fast endpoint that returns profile info quickly.
	 * Get a Users Github Profile Widget Data
	 */
	async getGithubProfileWidgetData(
		requestParameters: GetGithubProfileWidgetDataRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<GithubProfileResponse> {
		const response = await this.getGithubProfileWidgetDataRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Get a Users Github Widget by their auth token and a path parameter to return the GithubWidgetData This is a special widget that needs authorization outside of the mindscape so we use the github api to get the data.
	 * Get a Users Github Widget
	 */
	async getGithubWidgetDataRaw(
		requestParameters: GetGithubWidgetDataRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<GithubResponse>> {
		if (requestParameters['authorization'] == null) {
			throw new runtime.RequiredError(
				'authorization',
				'Required parameter "authorization" was null or undefined when calling getGithubWidgetData().',
			);
		}

		if (requestParameters['userWidgetId'] == null) {
			throw new runtime.RequiredError(
				'userWidgetId',
				'Required parameter "userWidgetId" was null or undefined when calling getGithubWidgetData().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters['authorization'] != null) {
			headerParameters['Authorization'] = String(
				requestParameters['authorization'],
			);
		}

		const response = await this.request(
			{
				path: `/widgets/github/{user_widget_id}`.replace(
					`{${'user_widget_id'}}`,
					encodeURIComponent(String(requestParameters['userWidgetId'])),
				),
				method: 'GET',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			GithubResponseFromJSON(jsonValue),
		);
	}

	/**
	 * Get a Users Github Widget by their auth token and a path parameter to return the GithubWidgetData This is a special widget that needs authorization outside of the mindscape so we use the github api to get the data.
	 * Get a Users Github Widget
	 */
	async getGithubWidgetData(
		requestParameters: GetGithubWidgetDataRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<GithubResponse> {
		const response = await this.getGithubWidgetDataRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Get a Users Coolify Applications by their auth token
	 * Get a Users Coolify Applications
	 */
	async getUserCoolifyApplicationsRaw(
		requestParameters: GetUserCoolifyApplicationsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<CoolifyWidgetApplicationResponse>> {
		if (requestParameters['authorization'] == null) {
			throw new runtime.RequiredError(
				'authorization',
				'Required parameter "authorization" was null or undefined when calling getUserCoolifyApplications().',
			);
		}

		if (requestParameters['userWidgetId'] == null) {
			throw new runtime.RequiredError(
				'userWidgetId',
				'Required parameter "userWidgetId" was null or undefined when calling getUserCoolifyApplications().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters['authorization'] != null) {
			headerParameters['Authorization'] = String(
				requestParameters['authorization'],
			);
		}

		const response = await this.request(
			{
				path: `/widgets/{user_widget_id}/coolify/applications`.replace(
					`{${'user_widget_id'}}`,
					encodeURIComponent(String(requestParameters['userWidgetId'])),
				),
				method: 'GET',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			CoolifyWidgetApplicationResponseFromJSON(jsonValue),
		);
	}

	/**
	 * Get a Users Coolify Applications by their auth token
	 * Get a Users Coolify Applications
	 */
	async getUserCoolifyApplications(
		requestParameters: GetUserCoolifyApplicationsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<CoolifyWidgetApplicationResponse> {
		const response = await this.getUserCoolifyApplicationsRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Get a Users Coolify Services by their auth token
	 * Get a Users Coolify Services
	 */
	async getUserCoolifyServicesRaw(
		requestParameters: GetUserCoolifyServicesRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<CoolifyWidgetServiceResponse>> {
		if (requestParameters['authorization'] == null) {
			throw new runtime.RequiredError(
				'authorization',
				'Required parameter "authorization" was null or undefined when calling getUserCoolifyServices().',
			);
		}

		if (requestParameters['userWidgetId'] == null) {
			throw new runtime.RequiredError(
				'userWidgetId',
				'Required parameter "userWidgetId" was null or undefined when calling getUserCoolifyServices().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters['authorization'] != null) {
			headerParameters['Authorization'] = String(
				requestParameters['authorization'],
			);
		}

		const response = await this.request(
			{
				path: `/widgets/{user_widget_id}/coolify/services`.replace(
					`{${'user_widget_id'}}`,
					encodeURIComponent(String(requestParameters['userWidgetId'])),
				),
				method: 'GET',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			CoolifyWidgetServiceResponseFromJSON(jsonValue),
		);
	}

	/**
	 * Get a Users Coolify Services by their auth token
	 * Get a Users Coolify Services
	 */
	async getUserCoolifyServices(
		requestParameters: GetUserCoolifyServicesRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<CoolifyWidgetServiceResponse> {
		const response = await this.getUserCoolifyServicesRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Get a Users Widget by their auth token and a path parameter and return the widget from the database.
	 * Get a Users Widget
	 */
	async getUserWidgetRaw(
		requestParameters: GetUserWidgetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<ResponsesUserWidgetResponse>> {
		if (requestParameters['authorization'] == null) {
			throw new runtime.RequiredError(
				'authorization',
				'Required parameter "authorization" was null or undefined when calling getUserWidget().',
			);
		}

		if (requestParameters['userWidgetId'] == null) {
			throw new runtime.RequiredError(
				'userWidgetId',
				'Required parameter "userWidgetId" was null or undefined when calling getUserWidget().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters['authorization'] != null) {
			headerParameters['Authorization'] = String(
				requestParameters['authorization'],
			);
		}

		const response = await this.request(
			{
				path: `/widgets/{user_widget_id}`.replace(
					`{${'user_widget_id'}}`,
					encodeURIComponent(String(requestParameters['userWidgetId'])),
				),
				method: 'GET',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			ResponsesUserWidgetResponseFromJSON(jsonValue),
		);
	}

	/**
	 * Get a Users Widget by their auth token and a path parameter and return the widget from the database.
	 * Get a Users Widget
	 */
	async getUserWidget(
		requestParameters: GetUserWidgetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<ResponsesUserWidgetResponse> {
		const response = await this.getUserWidgetRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Get a Users Widgets by their auth token and return the list of widgets associated with the user account in the request params.
	 * Get a Users Widgets
	 */
	async getUserWidgetsRaw(
		requestParameters: GetUserWidgetsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<ResponsesUserWidgetsResponse>> {
		if (requestParameters['authorization'] == null) {
			throw new runtime.RequiredError(
				'authorization',
				'Required parameter "authorization" was null or undefined when calling getUserWidgets().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters['authorization'] != null) {
			headerParameters['Authorization'] = String(
				requestParameters['authorization'],
			);
		}

		const response = await this.request(
			{
				path: `/widgets`,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			ResponsesUserWidgetsResponseFromJSON(jsonValue),
		);
	}

	/**
	 * Get a Users Widgets by their auth token and return the list of widgets associated with the user account in the request params.
	 * Get a Users Widgets
	 */
	async getUserWidgets(
		requestParameters: GetUserWidgetsRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<ResponsesUserWidgetsResponse> {
		const response = await this.getUserWidgetsRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Get embeded widget schema from the Schema Storage by its identifier
	 * Get Widget Schema by ID
	 */
	async getWidgetSchemaByIDRaw(
		requestParameters: GetWidgetSchemaByIDRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<WidgetResponse>> {
		if (requestParameters['schemaId'] == null) {
			throw new runtime.RequiredError(
				'schemaId',
				'Required parameter "schemaId" was null or undefined when calling getWidgetSchemaByID().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		const response = await this.request(
			{
				path: `/widgets/schemas/{schema_id}`.replace(
					`{${'schema_id'}}`,
					encodeURIComponent(String(requestParameters['schemaId'])),
				),
				method: 'GET',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			WidgetResponseFromJSON(jsonValue),
		);
	}

	/**
	 * Get embeded widget schema from the Schema Storage by its identifier
	 * Get Widget Schema by ID
	 */
	async getWidgetSchemaByID(
		requestParameters: GetWidgetSchemaByIDRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<WidgetResponse> {
		const response = await this.getWidgetSchemaByIDRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Get all embeded widget schemas from the Schema Storage
	 * Get Widget Schemas
	 */
	async getWidgetSchemasRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<ResponsesWidgetsResponse>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		const response = await this.request(
			{
				path: `/widgets/schemas`,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			ResponsesWidgetsResponseFromJSON(jsonValue),
		);
	}

	/**
	 * Get all embeded widget schemas from the Schema Storage
	 * Get Widget Schemas
	 */
	async getWidgetSchemas(
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<ResponsesWidgetsResponse> {
		const response = await this.getWidgetSchemasRaw(initOverrides);
		return await response.value();
	}

	/**
	 * Restart a Coolify Application by app UUID
	 * Restart a Coolify Application
	 */
	async restartCoolifyApplicationRaw(
		requestParameters: RestartCoolifyApplicationRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<CoolifyActionResponse>> {
		if (requestParameters['authorization'] == null) {
			throw new runtime.RequiredError(
				'authorization',
				'Required parameter "authorization" was null or undefined when calling restartCoolifyApplication().',
			);
		}

		if (requestParameters['userWidgetId'] == null) {
			throw new runtime.RequiredError(
				'userWidgetId',
				'Required parameter "userWidgetId" was null or undefined when calling restartCoolifyApplication().',
			);
		}

		if (requestParameters['appUuid'] == null) {
			throw new runtime.RequiredError(
				'appUuid',
				'Required parameter "appUuid" was null or undefined when calling restartCoolifyApplication().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters['authorization'] != null) {
			headerParameters['Authorization'] = String(
				requestParameters['authorization'],
			);
		}

		const response = await this.request(
			{
				path: `/widgets/{user_widget_id}/coolify/applications/{app_uuid}/restart`
					.replace(
						`{${'user_widget_id'}}`,
						encodeURIComponent(String(requestParameters['userWidgetId'])),
					)
					.replace(
						`{${'app_uuid'}}`,
						encodeURIComponent(String(requestParameters['appUuid'])),
					),
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			CoolifyActionResponseFromJSON(jsonValue),
		);
	}

	/**
	 * Restart a Coolify Application by app UUID
	 * Restart a Coolify Application
	 */
	async restartCoolifyApplication(
		requestParameters: RestartCoolifyApplicationRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<CoolifyActionResponse> {
		const response = await this.restartCoolifyApplicationRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Start a Coolify Application by app UUID
	 * Start a Coolify Application
	 */
	async startCoolifyApplicationRaw(
		requestParameters: StartCoolifyApplicationRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<CoolifyActionResponse>> {
		if (requestParameters['authorization'] == null) {
			throw new runtime.RequiredError(
				'authorization',
				'Required parameter "authorization" was null or undefined when calling startCoolifyApplication().',
			);
		}

		if (requestParameters['userWidgetId'] == null) {
			throw new runtime.RequiredError(
				'userWidgetId',
				'Required parameter "userWidgetId" was null or undefined when calling startCoolifyApplication().',
			);
		}

		if (requestParameters['appUuid'] == null) {
			throw new runtime.RequiredError(
				'appUuid',
				'Required parameter "appUuid" was null or undefined when calling startCoolifyApplication().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters['authorization'] != null) {
			headerParameters['Authorization'] = String(
				requestParameters['authorization'],
			);
		}

		const response = await this.request(
			{
				path: `/widgets/{user_widget_id}/coolify/applications/{app_uuid}/start`
					.replace(
						`{${'user_widget_id'}}`,
						encodeURIComponent(String(requestParameters['userWidgetId'])),
					)
					.replace(
						`{${'app_uuid'}}`,
						encodeURIComponent(String(requestParameters['appUuid'])),
					),
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			CoolifyActionResponseFromJSON(jsonValue),
		);
	}

	/**
	 * Start a Coolify Application by app UUID
	 * Start a Coolify Application
	 */
	async startCoolifyApplication(
		requestParameters: StartCoolifyApplicationRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<CoolifyActionResponse> {
		const response = await this.startCoolifyApplicationRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Stop a Coolify Application by app UUID
	 * Stop a Coolify Application
	 */
	async stopCoolifyApplicationRaw(
		requestParameters: StopCoolifyApplicationRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<CoolifyActionResponse>> {
		if (requestParameters['authorization'] == null) {
			throw new runtime.RequiredError(
				'authorization',
				'Required parameter "authorization" was null or undefined when calling stopCoolifyApplication().',
			);
		}

		if (requestParameters['userWidgetId'] == null) {
			throw new runtime.RequiredError(
				'userWidgetId',
				'Required parameter "userWidgetId" was null or undefined when calling stopCoolifyApplication().',
			);
		}

		if (requestParameters['appUuid'] == null) {
			throw new runtime.RequiredError(
				'appUuid',
				'Required parameter "appUuid" was null or undefined when calling stopCoolifyApplication().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (requestParameters['authorization'] != null) {
			headerParameters['Authorization'] = String(
				requestParameters['authorization'],
			);
		}

		const response = await this.request(
			{
				path: `/widgets/{user_widget_id}/coolify/applications/{app_uuid}/stop`
					.replace(
						`{${'user_widget_id'}}`,
						encodeURIComponent(String(requestParameters['userWidgetId'])),
					)
					.replace(
						`{${'app_uuid'}}`,
						encodeURIComponent(String(requestParameters['appUuid'])),
					),
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			CoolifyActionResponseFromJSON(jsonValue),
		);
	}

	/**
	 * Stop a Coolify Application by app UUID
	 * Stop a Coolify Application
	 */
	async stopCoolifyApplication(
		requestParameters: StopCoolifyApplicationRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<CoolifyActionResponse> {
		const response = await this.stopCoolifyApplicationRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}
}
