/* Generated by egg v0.0.1 */

package controllers

import (
	"context"

	"github.com/adamkali/mindscape/cmd/configuration"
	"github.com/adamkali/mindscape/middlewares/configs"
	"github.com/adamkali/mindscape/services"
	"github.com/jackc/pgx/v5/pgxpool"
	echojwt "github.com/labstack/echo-jwt/v4"
	"github.com/labstack/echo/v4"
)

type Registrar struct {
	Config           *configuration.Configuration
	AuthService      services.IAuthService
	BookmarkService  services.IBookmarkService
	FolderService    services.IFolderService
	MinioService     services.IMinioService
	NoteService      services.INoteService
	RedisService     services.IRedisService
	UserService      services.IUserService
	ValidatorService *services.ValidatorService
}

type IController interface {
	Attatch(e *echo.Echo, authMiddleware echo.MiddlewareFunc)
	ControllerName() string
}

func createControllerParams(config *configuration.Configuration) (*Registrar, error) {
	ctx := context.Background()
	db, err := pgxpool.New(ctx, config.Database.URL)
	if err != nil {
		return nil, err
	}

	return &Registrar{
		Config:           config,
		AuthService:      services.CreateAuthService(ctx, db, config),
		BookmarkService:  services.CreateBookmarkService(ctx, db),
		FolderService:    services.CreateFolderService(ctx, db),
		MinioService:     services.CreateMinioService(ctx, config),
		NoteService:      services.CreateNoteService(ctx, db),
		RedisService:     services.CreateRedisService(ctx, config),
		UserService:      services.CreateUserService(ctx, db),
		ValidatorService: &services.ValidatorService{},
	}, nil
}

func AttatchControllers(e *echo.Echo, config *configuration.Configuration, conts ...IController) {
	// configure middlewares here right now it is just an authentication
	for _, v := range conts {
		v.Attatch(e, echojwt.WithConfig(configs.AuthMiddlewareConfig(config)))
	}
}
