/* Generated by egg v0.0.1 */

package services

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"time"

	"github.com/adamkali/mindscape/cmd/configuration"
	"github.com/adamkali/mindscape/db/repository"
	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
)

// CustomJwt represents a JWT token with user-specific information.
type CustomJwt struct {
	UserId               uuid.UUID `json:"user_id"`
	User				 string   `json:"user"`
	IsAdmin              bool      `json:"is_admin"`
	ProfilePic           string   `json:"profile_pic"`
	jwt.RegisteredClaims `json:"claims"`
}

// AuthService provides authentication services, including creating and checking tokens.
type AuthService struct {
	ctx    context.Context
	conn   *pgxpool.Pool
	config *configuration.Configuration
}

// jwtFromUser creates short-lived access-token claims from a user object.
//
// The expiration is driven by server.access_token_ttl (default 15 minutes);
// long-lived auth is handled by the refresh-token session, not the JWT.
func jwtFromUser(user *repository.User, ttl time.Duration) *CustomJwt {
	ProfilePicUrl := "NULL"
	if user.ProfilePicUrl != nil { ProfilePicUrl = *user.ProfilePicUrl }
	return &CustomJwt{
		UserId: user.ID,
		ProfilePic: ProfilePicUrl,
		User: user.Username,
		IsAdmin: user.Admin,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(ttl)),
			IssuedAt:  jwt.NewNumericDate(time.Now()),
			ID: user.ID.String(),
			Subject: user.ID.String(),
		},
	}
}

// mintAccessJWT signs a short-lived access JWT for the user.
func (a *AuthService) mintAccessJWT(user *repository.User) (string, error) {
	claims := jwtFromUser(user, a.config.AccessTokenDuration())
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	return token.SignedString([]byte(a.config.Server.JWT))
}

// MintAccessToken signs a fresh short-lived access JWT for the user without
// touching any session. Used when claims change mid-session (e.g. credential
// updates) — the existing refresh session keeps working.
func (a *AuthService) MintAccessToken(user *repository.User) (string, error) {
	return a.mintAccessJWT(user)
}

// generateRefreshToken returns a high-entropy opaque refresh token and the
// SHA-256 hash that is stored at rest. Only the hash ever touches the database,
// so a leaked sessions table does not leak usable tokens.
func generateRefreshToken() (raw string, hash string, err error) {
	buf := make([]byte, 32)
	if _, err = rand.Read(buf); err != nil {
		return "", "", err
	}
	raw = base64.RawURLEncoding.EncodeToString(buf)
	return raw, hashRefreshToken(raw), nil
}

// hashRefreshToken hashes a raw refresh token for storage/lookup.
func hashRefreshToken(raw string) string {
	sum := sha256.Sum256([]byte(raw))
	return base64.RawURLEncoding.EncodeToString(sum[:])
}

// CreateAuthService creates a new instance of AuthService.
//
// This function takes the context, PostgreSQL connection, and configuration as
// arguments and returns a new AuthService instance.
func CreateAuthService(ctx context.Context, pgPool *pgxpool.Pool, config *configuration.Configuration) *AuthService {
	return &AuthService{ctx, pgPool, config}
}

// IssueSession mints a short-lived access JWT and creates a new session row
// holding the hash of a fresh refresh token. Each call creates an independent
// session, so multiple browsers/devices can stay logged in concurrently.
//
// This is the single entry point for anything that establishes a session:
// login, signup, and (in the future) passkey/WebAuthn login should all end
// here after verifying their respective credentials.
func (a *AuthService) IssueSession(user *repository.User, userAgent string) (access string, refreshRaw string, err error) {
	access, err = a.mintAccessJWT(user)
	if err != nil {
		return "", "", err
	}
	refreshRaw, refreshHash, err := generateRefreshToken()
	if err != nil {
		return "", "", err
	}

	tx, err := a.conn.Begin(a.ctx)
	if err != nil {
		return "", "", err
	}
	defer tx.Rollback(a.ctx)

	expiresAt := time.Now().Add(a.config.RefreshTokenDuration())
	repo := repository.New(tx)
	_, err = repo.CreateSession(a.ctx, repository.CreateSessionParams{
		UserID:           user.ID,
		RefreshTokenHash: &refreshHash,
		UserAgent:        &userAgent,
		ExpiresAt:        &expiresAt,
	})
	if err != nil {
		return "", "", err
	}
	if err = tx.Commit(a.ctx); err != nil {
		return "", "", err
	}
	return access, refreshRaw, nil
}

// RefreshSession exchanges a valid refresh token for a new access JWT and a
// rotated refresh token. Rotation is a single atomic UPDATE keyed on the old
// token's hash: if the row was already rotated (or expired), zero rows match
// and an error is returned — concurrent refreshes are deterministic, exactly
// one wins.
func (a *AuthService) RefreshSession(refreshRaw string) (access string, newRefreshRaw string, user *repository.User, err error) {
	oldHash := hashRefreshToken(refreshRaw)
	newRefreshRaw, newHash, err := generateRefreshToken()
	if err != nil {
		return "", "", nil, err
	}

	tx, err := a.conn.Begin(a.ctx)
	if err != nil {
		return "", "", nil, err
	}
	defer tx.Rollback(a.ctx)
	repo := repository.New(tx)

	expiresAt := time.Now().Add(a.config.RefreshTokenDuration())
	session, err := repo.RotateSession(a.ctx, repository.RotateSessionParams{
		RefreshTokenHash:   &newHash,
		ExpiresAt:          &expiresAt,
		RefreshTokenHash_2: &oldHash,
	})
	if err != nil {
		return "", "", nil, fmt.Errorf("invalid or expired refresh token: %w", err)
	}

	found, err := repo.FindUserByID(a.ctx, session.UserID)
	if err != nil {
		return "", "", nil, err
	}
	if err = tx.Commit(a.ctx); err != nil {
		return "", "", nil, err
	}

	access, err = a.mintAccessJWT(&found)
	if err != nil {
		return "", "", nil, err
	}
	return access, newRefreshRaw, &found, nil
}

// RevokeSession deletes the session matching the given refresh token (logout
// for this device only; other sessions for the same user are untouched).
func (a *AuthService) RevokeSession(refreshRaw string) error {
	hash := hashRefreshToken(refreshRaw)
	tx, err := a.conn.Begin(a.ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(a.ctx)
	repo := repository.New(tx)
	if err = repo.DeleteSessionByHash(a.ctx, &hash); err != nil {
		return err
	}
	return tx.Commit(a.ctx)
}

// CheckToken validates an access JWT statelessly: signature and expiry only,
// no database lookup. The echo-jwt middleware has already verified the
// signature, but handlers pass the raw token here as a final gate. Revocation
// is handled at the refresh layer — deleting a session row stops new access
// tokens from being minted, so a revoked user is out within one access-token
// TTL at most.
func (a *AuthService) CheckToken(token string) error {
	// API key authenticated requests use a synthetic token with Raw="apikey".
	// The key has already been validated by the API key middleware.
	if token == "apikey" {
		return nil
	}

	claims := &CustomJwt{}
	_, err := jwt.ParseWithClaims(token, claims, func(token *jwt.Token) (interface{}, error) {
		return []byte(a.config.Server.JWT), nil
	})
	if err != nil {
		return err
	}
	if claims.ExpiresAt == nil || claims.ExpiresAt.Before(time.Now()) {
		return fmt.Errorf("token expired")
	}
	return nil
}
