/* Generated by egg v0.0.1 */

package services

import (
	"github.com/adamkali/mindscape/db/repository"
)


type IAuthService interface {
	Create(user *repository.User) (*string, error)
 	Update(user repository.User) (*string, error)
	CheckToken(token string) error
}
