/* Generated by egg v0.0.1 */

package services

import (
	"io"

	"github.com/google/uuid"
)

type BackgroundInternal struct {
	Name string
	URL  string
}

type IMinioService interface {
	Upload(uploaderID uuid.UUID, uploadName string, uploadFile io.Reader, size int64, prefix string) error
	Get(uploaderID uuid.UUID, prefix string, uploadName string) ([]byte, error)
	GetPresigned(uploaderID uuid.UUID, prefix string, uploadName string) (string, error)
	GetUserBackgroundChoices(user uuid.UUID) ([]BackgroundInternal, error)
	GetBackgroundChoices() ([]BackgroundInternal, error)
	GetDefault() (string, error)
	GetDefaultChoice(choice string) (string, error)
}
