/* Generated by egg v0.0.1 */

package services

import "time"

type IRedisService interface {
	SetWithExpiration(key string, value string, expiration time.Duration) error
	GetWithExpiration(key string, expiration time.Duration) (string, error)
	Set(key string, value string) error
	Get(key string) (string, error)
	Delete(key string) error
	LPush(key string, values ...string) error
	LRange(key string, start, stop int64) ([]string, error)
	LRem(key string, count int64, value string) error
}
