/* Generated by egg v0.0.1 */

package services

import (
	"context"
	"fmt"
	"io"
	"net/url"
	"time"

	"github.com/adamkali/mindscape/cmd/configuration"
	"github.com/google/uuid"
	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

type MinioService struct {
	ctx    context.Context
	client *minio.Client
}

// Returns a refrence to a new UserService to be used in the controller
func CreateMinioService(ctx context.Context, config *configuration.Configuration) *MinioService {
	// Initialize minio client object.
	minioClient, err := minio.New(config.S3.URL, &minio.Options{
		Creds:  credentials.NewStaticV4(config.S3.Access, config.S3.Secret, ""),
		Secure: config.S3.Secure,
	})
	if err != nil {
		panic(err.Error())
	}
	return &MinioService{ctx, minioClient}
}

// Upload
//
// params:
//
//	uploaderID: uuid.UUID
//	uploadName: string
//	uploadFile: io.Reader
//	size: int64
//
// returns:
//
//	error
//
// Uploads a file to S3 compatible storage. If the bucket does not exist, it will be created.
// If the file already exists, it will be overwritten.
//
// The function should return an error only if there is a problem uploading the file, or if
// when creating the bucket something went wrong.
func (MinioService *MinioService) Upload(
	uploaderID uuid.UUID,
	uploadName string,
	uploadFile io.Reader,
	size int64,
	prefix string,
) error {
	bucketName := uploaderID.String()
	exists, err := MinioService.client.BucketExists(
		MinioService.ctx,
		bucketName,
	)
	if err != nil {
		return err
	} else if !exists {
		opts := minio.MakeBucketOptions{}
		errMakeBucket := MinioService.client.MakeBucket(
			MinioService.ctx,
			bucketName,
			opts,
		)
		if errMakeBucket != nil {
			return err
		}
	}

	// Construct object key (path within bucket)
	var objectKey string
	if prefix != "" {
		objectKey = fmt.Sprintf("%s/%s", prefix, uploadName)
	} else {
		objectKey = uploadName
	}

	_, err = MinioService.client.PutObject(
		MinioService.ctx,
		bucketName,
		objectKey,
		uploadFile,
		size,
		minio.PutObjectOptions{},
	)
	if err != nil {
		return err
	}
	return nil
}

// Get
//
// params:
//
//	uploaderID: uuid.UUID
//	uploadName: string
//
// returns:
//
//	[]byte
//	error
//
// Gets a file from S3 compatible storage. If the file does not exist, it will return an error.
func (MinioService *MinioService) Get(uploaderID uuid.UUID, prefix string, uploadName string) ([]byte, error) {
	opts := minio.GetObjectOptions{}
	bucketName := uploaderID.String()

	// Construct object key (path within bucket)
	var objectKey string
	if prefix != "" {
		objectKey = fmt.Sprintf("%s/%s", prefix, uploadName)
	} else {
		objectKey = uploadName
	}

	object, err := MinioService.client.GetObject(MinioService.ctx, bucketName, objectKey, opts)
	if err != nil {
		return nil, err
	}
	defer object.Close()
	data, err := io.ReadAll(object)
	if err != nil {
		return nil, err
	}
	return data, err
}

// GetPresigned
//
// params:
//
//	uploaderID: uuid.UUID
//	uploadName: string
//
// returns:
//
//	string
//	error
//
// Gets a presigned url from S3 compatible storage. If the file does not exist, it will return an error.
func (m *MinioService) GetPresigned(uploaderID uuid.UUID, prefix string, uploadName string) (string, error) {
	reqParams := make(url.Values)
	reqParams.Set("response-content-disposition", "attachment; filename=\""+uploadName+"\"")
	bucketName := uploaderID.String()

	// Construct object key (path within bucket)
	var objectKey string
	if prefix != "" {
		objectKey = fmt.Sprintf("%s/%s", prefix, uploadName)
	} else {
		objectKey = uploadName
	}

	// Check if the object actually exists before generating presigned URL
	_, err := m.client.StatObject(m.ctx, bucketName, objectKey, minio.StatObjectOptions{})
	if err != nil {
		return "", err
	}

	presigedUrl, err := m.client.PresignedGetObject(m.ctx, bucketName, objectKey, time.Hour*72, reqParams)
	if err != nil {
		return "", err
	}
	return presigedUrl.String(), nil
}

// GetDefault
//
// params:
//
//	uploaderID: uuid.UUID
//	uploadName: string
//
// returns:
//
//	string
//	error
//
// Gets the default background image url from S3 compatible storage. If the file does not exist, it will return an error.
func (m *MinioService) GetDefault() (string, error) {
	reqParams := make(url.Values)
	reqParams.Set("response-content-disposition", "attachment; filename=\"beach.jpeg\"")
	presigedUrl, err := m.client.PresignedGetObject(m.ctx, "mindspace", "beach.jpeg", time.Hour*24*7, reqParams)
	if err != nil {
		return "", err
	}
	return presigedUrl.String(), nil
}

func (m *MinioService) GetBackgroundChoices() ([]BackgroundInternal, error) {
	reqParams := make(url.Values)
	backgrounds := make([]minio.ObjectInfo, 0)
	for objects := range m.client.ListObjects(m.ctx, "mindspace", minio.ListObjectsOptions{ Recursive: false }) {
		if err := objects.Err; err != nil {
			return nil, err
		}
		backgrounds = append(backgrounds, objects)
	}
	bakcgroundUrls := make([]BackgroundInternal, len(backgrounds))
	for i, background := range backgrounds {
		reqParams.Set("response-content-disposition", "attachment; filename=\""+background.Key+"\"")
		presigedUrl, err := m.client.PresignedGetObject(m.ctx, "mindspace", background.Key, time.Hour*24*7, reqParams)
		if err != nil {
			return nil, err
		}
		bakcgroundUrls[i] = BackgroundInternal{Name: background.Key, URL: presigedUrl.String()}
	}

	return bakcgroundUrls, nil
}

func (m *MinioService) GetUserBackgroundChoices(user uuid.UUID) ([]BackgroundInternal, error) {
	reqParams := make(url.Values)
	backgrounds := make([]minio.ObjectInfo, 0)
	bucketName := user.String()

	listObjectsOptions := minio.ListObjectsOptions{
		Recursive: true,
		Prefix:    "backgrounds/",
	}
	for objects := range m.client.ListObjects(m.ctx, bucketName, listObjectsOptions) {
		if err := objects.Err; err != nil {
			return nil, err
		}
		backgrounds = append(backgrounds, objects)
	}

	backgroundEntities := make([]BackgroundInternal, len(backgrounds))
	for i, background := range backgrounds {
		// Strip the "backgrounds/" prefix from the filename
		filename := background.Key
		if len(filename) > 12 && filename[:12] == "backgrounds/" {
			filename = filename[12:]
		}

		reqParams.Set("response-content-disposition", fmt.Sprintf("attachment; filename=\"%s\"", filename))
		presigedUrl, err := m.client.PresignedGetObject(m.ctx, bucketName, background.Key, time.Hour*24*7, reqParams)
		if err != nil {
			return nil, err
		}
		backgroundEntities[i] = BackgroundInternal{Name: filename, URL: presigedUrl.String()}
	}
	return backgroundEntities, nil
}

func (m *MinioService) GetDefaultChoice(choice string) (string, error) {
	reqParams := make(url.Values)
	reqParams.Set("response-content-disposition", fmt.Sprintf("attachment; filename=\"%s\"", choice))
	presigedUrl, err := m.client.PresignedGetObject(m.ctx, "mindspace", choice, time.Hour*24*7, reqParams)
	if err != nil {
		return "", err
	}
	return presigedUrl.String(), nil
}
