/* Generated by egg v0.0.1 */

package services

import (
	"context"
	"errors"
	"sync"
	"time"

	"github.com/adamkali/mindscape/db/repository"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Seeded identifiers used across household tests.
var (
	MockHouseholdOwnerID    = uuid.MustParse("a1111111-1111-1111-1111-111111111111")
	MockHouseholdMemberID   = uuid.MustParse("b2222222-2222-2222-2222-222222222222")
	MockHouseholdOutsiderID = uuid.MustParse("c3333333-3333-3333-3333-333333333333")
	MockHouseholdID         = uuid.MustParse("d4444444-4444-4444-4444-444444444444")
)

// MockHouseholdService is an in-memory implementation of IHouseholdService for testing.
type MockHouseholdService struct {
	ctx           context.Context
	pool          *pgxpool.Pool
	households    map[uuid.UUID]*repository.Household
	members       map[uuid.UUID][]*repository.HouseholdMember // keyed by household ID
	invitesByCode map[string]*repository.HouseholdInvite
	usernames     map[uuid.UUID]string
	mutex         sync.RWMutex

	// Failure injection
	ShouldFailCreate       bool
	ShouldFailGetByUser    bool
	ShouldFailCreateInvite bool
	ShouldFailAccept       bool

	// Call tracking
	CreateCallCount       int
	CreateInviteCallCount int
	AcceptCallCount       int
	RemoveMemberCallCount int
}

func CreateMockHouseholdService(ctx context.Context, pool *pgxpool.Pool) *MockHouseholdService {
	m := &MockHouseholdService{
		ctx:           ctx,
		pool:          pool,
		households:    make(map[uuid.UUID]*repository.Household),
		members:       make(map[uuid.UUID][]*repository.HouseholdMember),
		invitesByCode: make(map[string]*repository.HouseholdInvite),
		usernames:     make(map[uuid.UUID]string),
	}
	m.seedTestData()
	return m
}

func (m *MockHouseholdService) seedTestData() {
	now := time.Now()
	m.usernames[MockHouseholdOwnerID] = "owner"
	m.usernames[MockHouseholdMemberID] = "member"
	m.usernames[MockHouseholdOutsiderID] = "outsider"

	household := &repository.Household{
		ID:        MockHouseholdID,
		Name:      "Test Household",
		OwnerID:   MockHouseholdOwnerID,
		CreatedAt: &now,
	}
	m.households[household.ID] = household
	m.members[household.ID] = []*repository.HouseholdMember{
		{ID: uuid.New(), HouseholdID: household.ID, UserID: MockHouseholdOwnerID, Role: "admin", JoinedAt: &now},
	}

	future := now.Add(7 * 24 * time.Hour)
	past := now.Add(-1 * time.Hour)

	// A valid pending invite for the member user.
	m.invitesByCode["valid-code"] = &repository.HouseholdInvite{
		ID: uuid.New(), HouseholdID: household.ID, InvitedUserID: MockHouseholdMemberID,
		Code: "valid-code", ExpiresAt: &future, AcceptedAt: pgtype.Timestamp{Valid: false},
		CreatedBy: MockHouseholdOwnerID, CreatedAt: &now,
	}
	// An expired invite for the member user.
	m.invitesByCode["expired-code"] = &repository.HouseholdInvite{
		ID: uuid.New(), HouseholdID: household.ID, InvitedUserID: MockHouseholdMemberID,
		Code: "expired-code", ExpiresAt: &past, AcceptedAt: pgtype.Timestamp{Valid: false},
		CreatedBy: MockHouseholdOwnerID, CreatedAt: &now,
	}
	// An already-accepted invite for the member user.
	m.invitesByCode["accepted-code"] = &repository.HouseholdInvite{
		ID: uuid.New(), HouseholdID: household.ID, InvitedUserID: MockHouseholdMemberID,
		Code: "accepted-code", ExpiresAt: &future, AcceptedAt: pgtype.Timestamp{Time: now, Valid: true},
		CreatedBy: MockHouseholdOwnerID, CreatedAt: &now,
	}
}

func (m *MockHouseholdService) Reset() {
	m.mutex.Lock()
	defer m.mutex.Unlock()
	m.CreateCallCount = 0
	m.CreateInviteCallCount = 0
	m.AcceptCallCount = 0
	m.RemoveMemberCallCount = 0
	m.ShouldFailCreate = false
	m.ShouldFailGetByUser = false
	m.ShouldFailCreateInvite = false
	m.ShouldFailAccept = false
	m.households = make(map[uuid.UUID]*repository.Household)
	m.members = make(map[uuid.UUID][]*repository.HouseholdMember)
	m.invitesByCode = make(map[string]*repository.HouseholdInvite)
	m.usernames = make(map[uuid.UUID]string)
	m.seedTestData()
}

func (m *MockHouseholdService) CreateHousehold(name string, ownerID uuid.UUID) (*repository.Household, error) {
	m.mutex.Lock()
	m.CreateCallCount++
	m.mutex.Unlock()
	if m.ShouldFailCreate {
		return nil, errors.New("mock create household failure")
	}
	if name == "" {
		return nil, errors.New("household name cannot be empty")
	}
	now := time.Now()
	household := &repository.Household{ID: uuid.New(), Name: name, OwnerID: ownerID, CreatedAt: &now}
	m.mutex.Lock()
	defer m.mutex.Unlock()
	m.households[household.ID] = household
	// Owner is seeded as an admin member, mirroring the real service.
	m.members[household.ID] = []*repository.HouseholdMember{
		{ID: uuid.New(), HouseholdID: household.ID, UserID: ownerID, Role: "admin", JoinedAt: &now},
	}
	return household, nil
}

func (m *MockHouseholdService) GetByUser(userID uuid.UUID) ([]repository.Household, error) {
	if m.ShouldFailGetByUser {
		return nil, errors.New("mock get households failure")
	}
	m.mutex.RLock()
	defer m.mutex.RUnlock()
	out := make([]repository.Household, 0)
	for hid, members := range m.members {
		for _, mem := range members {
			if mem.UserID == userID {
				if h, ok := m.households[hid]; ok {
					out = append(out, *h)
				}
				break
			}
		}
	}
	return out, nil
}

func (m *MockHouseholdService) Get(id uuid.UUID) (*repository.Household, error) {
	m.mutex.RLock()
	defer m.mutex.RUnlock()
	h, ok := m.households[id]
	if !ok {
		return nil, errors.New("household not found")
	}
	return h, nil
}

func (m *MockHouseholdService) Delete(id uuid.UUID) error {
	m.mutex.Lock()
	defer m.mutex.Unlock()
	if _, ok := m.households[id]; !ok {
		return errors.New("household not found")
	}
	delete(m.households, id)
	delete(m.members, id)
	return nil
}

func (m *MockHouseholdService) GetMembers(householdID uuid.UUID) ([]repository.GetMembersByHouseholdIDRow, error) {
	m.mutex.RLock()
	defer m.mutex.RUnlock()
	out := make([]repository.GetMembersByHouseholdIDRow, 0)
	for _, mem := range m.members[householdID] {
		out = append(out, repository.GetMembersByHouseholdIDRow{
			ID: mem.ID, HouseholdID: mem.HouseholdID, UserID: mem.UserID,
			Role: mem.Role, JoinedAt: mem.JoinedAt, Username: m.usernames[mem.UserID],
		})
	}
	return out, nil
}

func (m *MockHouseholdService) GetMember(householdID uuid.UUID, userID uuid.UUID) (*repository.HouseholdMember, error) {
	m.mutex.RLock()
	defer m.mutex.RUnlock()
	for _, mem := range m.members[householdID] {
		if mem.UserID == userID {
			return mem, nil
		}
	}
	return nil, errors.New("member not found")
}

func (m *MockHouseholdService) RemoveMember(householdID uuid.UUID, userID uuid.UUID) error {
	m.mutex.Lock()
	defer m.mutex.Unlock()
	m.RemoveMemberCallCount++
	members := m.members[householdID]
	for i, mem := range members {
		if mem.UserID == userID {
			m.members[householdID] = append(members[:i], members[i+1:]...)
			return nil
		}
	}
	return errors.New("member not found")
}

func (m *MockHouseholdService) CreateInvite(householdID uuid.UUID, invitedUserID uuid.UUID, createdBy uuid.UUID, ttl time.Duration) (*repository.HouseholdInvite, error) {
	m.mutex.Lock()
	m.CreateInviteCallCount++
	m.mutex.Unlock()
	if m.ShouldFailCreateInvite {
		return nil, errors.New("mock create invite failure")
	}
	now := time.Now()
	expires := now.Add(ttl)
	invite := &repository.HouseholdInvite{
		ID: uuid.New(), HouseholdID: householdID, InvitedUserID: invitedUserID,
		Code: uuid.NewString(), ExpiresAt: &expires, AcceptedAt: pgtype.Timestamp{Valid: false},
		CreatedBy: createdBy, CreatedAt: &now,
	}
	m.mutex.Lock()
	defer m.mutex.Unlock()
	m.invitesByCode[invite.Code] = invite
	return invite, nil
}

func (m *MockHouseholdService) GetInvites(userID uuid.UUID) ([]repository.GetInvitesByUserIDRow, error) {
	m.mutex.RLock()
	defer m.mutex.RUnlock()
	now := time.Now()
	out := make([]repository.GetInvitesByUserIDRow, 0)
	for _, inv := range m.invitesByCode {
		if inv.InvitedUserID == userID && !inv.AcceptedAt.Valid && inv.ExpiresAt != nil && inv.ExpiresAt.After(now) {
			name := ""
			if h, ok := m.households[inv.HouseholdID]; ok {
				name = h.Name
			}
			out = append(out, repository.GetInvitesByUserIDRow{
				ID: inv.ID, HouseholdID: inv.HouseholdID, InvitedUserID: inv.InvitedUserID,
				Code: inv.Code, ExpiresAt: inv.ExpiresAt,
				CreatedBy: inv.CreatedBy, CreatedAt: inv.CreatedAt, HouseholdName: name,
			})
		}
	}
	return out, nil
}

func (m *MockHouseholdService) AcceptInvite(code string, userID uuid.UUID) (*repository.Household, error) {
	m.mutex.Lock()
	m.AcceptCallCount++
	m.mutex.Unlock()
	if m.ShouldFailAccept {
		return nil, errors.New("mock accept failure")
	}
	m.mutex.Lock()
	defer m.mutex.Unlock()
	invite, ok := m.invitesByCode[code]
	if !ok {
		return nil, errors.New("invite not found")
	}
	if invite.InvitedUserID != userID {
		return nil, errors.New("invite does not belong to this user")
	}
	if invite.AcceptedAt.Valid {
		return nil, errors.New("invite already accepted")
	}
	if invite.ExpiresAt != nil && invite.ExpiresAt.Before(time.Now()) {
		return nil, errors.New("invite expired")
	}
	now := time.Now()
	invite.AcceptedAt = pgtype.Timestamp{Time: now, Valid: true}
	m.members[invite.HouseholdID] = append(m.members[invite.HouseholdID], &repository.HouseholdMember{
		ID: uuid.New(), HouseholdID: invite.HouseholdID, UserID: userID, Role: "member", JoinedAt: &now,
	})
	h, ok := m.households[invite.HouseholdID]
	if !ok {
		return nil, errors.New("household not found")
	}
	return h, nil
}

func (m *MockHouseholdService) RejectInvite(code string, userID uuid.UUID) error {
	m.mutex.Lock()
	defer m.mutex.Unlock()
	invite, ok := m.invitesByCode[code]
	if !ok {
		return errors.New("invite not found")
	}
	if invite.InvitedUserID != userID {
		return errors.New("invite does not belong to this user")
	}
	delete(m.invitesByCode, code)
	return nil
}
