/* Generated by egg v0.0.1 */

package services

import (
	"context"
	"errors"
	"sync"
	"time"

	"github.com/adamkali/mindscape/db/repository"
	"github.com/adamkali/mindscape/models/requests"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
	"golang.org/x/crypto/bcrypt"
)

// MockUserService provides an in-memory implementation of IUserService for testing
type MockUserService struct {
	ctx          context.Context
	pool         *pgxpool.Pool
	users        map[uuid.UUID]*repository.User
	usersByEmail map[string]*repository.User
	usersByUsername map[string]*repository.User
	mutex        sync.RWMutex
	
	// Test behavior controls
	ShouldFailCreate         bool
	ShouldFailLogin          bool
	ShouldFailGet            bool
	ShouldFailRemove         bool
	ShouldFailGetAll         bool
	ShouldFailUpdate         bool
	ShouldFailUpdateCreds    bool
	ShouldFailUpdateBg       bool
	CreateErrorMessage       string
	LoginErrorMessage        string
	GetErrorMessage          string
	RemoveErrorMessage       string
	GetAllErrorMessage       string
	UpdateErrorMessage       string
	UpdateCredsErrorMessage  string
	UpdateBgErrorMessage     string
	
	// Test data tracking
	CreateCallCount      int
	LoginCallCount       int
	GetCallCount         int
	RemoveCallCount      int
	GetAllCallCount      int
	UpdateCallCount      int
	UpdateCredsCallCount int
	UpdateBgCallCount    int
	LastCreateParams     *requests.NewUserRequest
	LastLoginParams      *requests.LoginRequest
	LastGetID            uuid.UUID
	LastRemoveID         uuid.UUID
	LastUpdateID         uuid.UUID
	LastUpdateProfile    string
	LastUpdateCredsParams *requests.UpdateCredentialsRequest
	LastUpdateBgParams   *repository.UpdateUserBacgroundParams
}

// CreateMockUserService returns a reference to a new MockUserService for testing
func CreateMockUserService(ctx context.Context, pool *pgxpool.Pool) *MockUserService {
	service := &MockUserService{
		ctx:             ctx,
		pool:            pool,
		users:           make(map[uuid.UUID]*repository.User),
		usersByEmail:    make(map[string]*repository.User),
		usersByUsername: make(map[string]*repository.User),
		CreateErrorMessage:      "Mock create error",
		LoginErrorMessage:       "Mock login error", 
		GetErrorMessage:         "Mock get error",
		RemoveErrorMessage:      "Mock remove error",
		GetAllErrorMessage:      "Mock getall error",
		UpdateErrorMessage:      "Mock update error",
		UpdateCredsErrorMessage: "Mock update credentials error",
		UpdateBgErrorMessage:    "Mock update background error",
	}
	
	// Seed with some default test data
	service.seedTestData()
	return service
}

// Reset clears all data and resets counters for fresh test runs
func (service *MockUserService) Reset() {
	service.mutex.Lock()
	defer service.mutex.Unlock()
	
	service.users = make(map[uuid.UUID]*repository.User)
	service.usersByEmail = make(map[string]*repository.User)
	service.usersByUsername = make(map[string]*repository.User)
	
	// Reset behavior flags
	service.ShouldFailCreate = false
	service.ShouldFailLogin = false
	service.ShouldFailGet = false
	service.ShouldFailRemove = false
	service.ShouldFailGetAll = false
	service.ShouldFailUpdate = false
	service.ShouldFailUpdateCreds = false
	service.ShouldFailUpdateBg = false
	
	// Reset counters
	service.CreateCallCount = 0
	service.LoginCallCount = 0
	service.GetCallCount = 0
	service.RemoveCallCount = 0
	service.GetAllCallCount = 0
	service.UpdateCallCount = 0
	service.UpdateCredsCallCount = 0
	service.UpdateBgCallCount = 0
	
	// Re-seed test data
	service.seedTestData()
}

// seedTestData populates the mock with realistic test users
func (service *MockUserService) seedTestData() {
	now := time.Now()
	defaultProfilePic := "default-avatar.png"
	
	// Regular test user - using password123 for service layer tests
	testUser := &repository.User{
		ID:              uuid.MustParse("11111111-1111-1111-1111-111111111111"),
		Email:           "test@example.com",
		Username:        "testuser",
		CreatedDatetime: &now,
		UpdatedDatetime: &now,
		ProfilePicUrl:   &defaultProfilePic,
		BCryptHash:      "$2a$12$Vyfp6zWRLnsX/veqmlgfP.x/oekdfCgGc3DNpTBaqPku0MafUztNu", // "password123"
		Admin:           false,
	}
	
	// Admin test user - using password123 for service layer tests
	adminUser := &repository.User{
		ID:              uuid.MustParse("22222222-2222-2222-2222-222222222222"),
		Email:           "admin@example.com", 
		Username:        "adminuser",
		CreatedDatetime: &now,
		UpdatedDatetime: &now,
		ProfilePicUrl:   &defaultProfilePic,
		BCryptHash:      "$2a$12$Vyfp6zWRLnsX/veqmlgfP.x/oekdfCgGc3DNpTBaqPku0MafUztNu", // "password123"
		Admin:           true,
	}
	
	// Additional test users for handler layer tests that require complex passwords
	handlerTestUser := &repository.User{
		ID:              uuid.MustParse("33333333-3333-3333-3333-333333333333"),
		Email:           "handler@example.com",
		Username:        "handleruser",
		CreatedDatetime: &now,
		UpdatedDatetime: &now,
		ProfilePicUrl:   &defaultProfilePic,
		BCryptHash:      "$2a$12$d00DdQWMlqBhNOwJH6afwOXDe2vwq0Z6eLvI6NG89ZR0GkB1mnUDm", // "passwordABC123!"
		Admin:           false,
	}
	
	handlerAdminUser := &repository.User{
		ID:              uuid.MustParse("44444444-4444-4444-4444-444444444444"),
		Email:           "handleradmin@example.com",
		Username:        "handleradmin",
		CreatedDatetime: &now,
		UpdatedDatetime: &now,
		ProfilePicUrl:   &defaultProfilePic,
		BCryptHash:      "$2a$12$d00DdQWMlqBhNOwJH6afwOXDe2vwq0Z6eLvI6NG89ZR0GkB1mnUDm", // "passwordABC123!"
		Admin:           true,
	}
	
	// Delete test users
	deleteAdminUser := &repository.User{
		ID:              uuid.MustParse("66666666-6666-6666-6666-666666666666"),
		Email:           "deleteadmin@example.com",
		Username:        "deleteadmin",
		CreatedDatetime: &now,
		UpdatedDatetime: &now,
		ProfilePicUrl:   &defaultProfilePic,
		BCryptHash:      "$2a$12$d00DdQWMlqBhNOwJH6afwOXDe2vwq0Z6eLvI6NG89ZR0GkB1mnUDm", // "passwordABC123!"
		Admin:           true,
	}
	
	deleteRegularUser := &repository.User{
		ID:              uuid.MustParse("77777777-7777-7777-7777-777777777777"),
		Email:           "deleteuser@example.com",
		Username:        "deleteuser",
		CreatedDatetime: &now,
		UpdatedDatetime: &now,
		ProfilePicUrl:   &defaultProfilePic,
		BCryptHash:      "$2a$12$d00DdQWMlqBhNOwJH6afwOXDe2vwq0Z6eLvI6NG89ZR0GkB1mnUDm", // "passwordABC123!"
		Admin:           false,
	}
	
	deleteTargetUser := &repository.User{
		ID:              uuid.MustParse("88888888-8888-8888-8888-888888888888"),
		Email:           "target@example.com",
		Username:        "targettodelete",
		CreatedDatetime: &now,
		UpdatedDatetime: &now,
		ProfilePicUrl:   &defaultProfilePic,
		BCryptHash:      "$2a$12$d00DdQWMlqBhNOwJH6afwOXDe2vwq0Z6eLvI6NG89ZR0GkB1mnUDm", // "passwordABC123!"
		Admin:           false,
	}
	
	service.users[testUser.ID] = testUser
	service.users[adminUser.ID] = adminUser
	service.users[handlerTestUser.ID] = handlerTestUser
	service.users[handlerAdminUser.ID] = handlerAdminUser
	service.users[deleteAdminUser.ID] = deleteAdminUser
	service.users[deleteRegularUser.ID] = deleteRegularUser
	service.users[deleteTargetUser.ID] = deleteTargetUser
	service.usersByEmail[testUser.Email] = testUser
	service.usersByEmail[adminUser.Email] = adminUser
	service.usersByEmail[handlerTestUser.Email] = handlerTestUser
	service.usersByEmail[handlerAdminUser.Email] = handlerAdminUser
	service.usersByEmail[deleteAdminUser.Email] = deleteAdminUser
	service.usersByEmail[deleteRegularUser.Email] = deleteRegularUser
	service.usersByEmail[deleteTargetUser.Email] = deleteTargetUser
	service.usersByUsername[testUser.Username] = testUser
	service.usersByUsername[adminUser.Username] = adminUser
	service.usersByUsername[handlerTestUser.Username] = handlerTestUser
	service.usersByUsername[handlerAdminUser.Username] = handlerAdminUser
	service.usersByUsername[deleteAdminUser.Username] = deleteAdminUser
	service.usersByUsername[deleteRegularUser.Username] = deleteRegularUser
	service.usersByUsername[deleteTargetUser.Username] = deleteTargetUser
}

// GetUserByEmail retrieves a user by email for testing
func (service *MockUserService) GetUserByEmail(email string) (*repository.User, bool) {
	service.mutex.RLock()
	defer service.mutex.RUnlock()
	user, exists := service.usersByEmail[email]
	return user, exists
}

// GetUserByUsername retrieves a user by username for testing  
func (service *MockUserService) GetUserByUsername(username string) (*repository.User, bool) {
	service.mutex.RLock()
	defer service.mutex.RUnlock()
	user, exists := service.usersByUsername[username]
	return user, exists
}

// GetUserCount returns the total number of users
func (service *MockUserService) GetUserCount() int {
	service.mutex.RLock()
	defer service.mutex.RUnlock()
	return len(service.users)
}

// Create implements IUserService.Create
func (service *MockUserService) Create(params *requests.NewUserRequest) (*repository.User, error) {
	service.mutex.Lock()
	defer service.mutex.Unlock()
	
	service.CreateCallCount++
	service.LastCreateParams = params
	
	if service.ShouldFailCreate {
		return nil, errors.New(service.CreateErrorMessage)
	}
	
	// Basic validation
	if params.Username == "" {
		return nil, errors.New("username cannot be empty")
	}
	if params.Email == "" {
		return nil, errors.New("email cannot be empty")
	}
	if params.Password == "" {
		return nil, errors.New("password cannot be empty")
	}
	
	// Check for duplicate email
	if _, exists := service.usersByEmail[params.Email]; exists {
		return nil, errors.New("user with this email already exists")
	}
	
	// Check for duplicate username
	if _, exists := service.usersByUsername[params.Username]; exists {
		return nil, errors.New("user with this username already exists")
	}
	
	// Hash the password
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(params.Password), 12)
	if err != nil {
		return nil, errors.New("failed to hash password")
	}
	
	// Create new user
	userID := uuid.New()
	now := time.Now()
	defaultProfilePic := "default-avatar.png"
	
	user := &repository.User{
		ID:              userID,
		Email:           params.Email,
		Username:        params.Username,
		CreatedDatetime: &now,
		UpdatedDatetime: &now,
		ProfilePicUrl:   &defaultProfilePic,
		BCryptHash:      string(hashedPassword),
		Admin:           params.IsAdmin,
	}
	
	// Store in all lookup maps
	service.users[userID] = user
	service.usersByEmail[params.Email] = user
	service.usersByUsername[params.Username] = user
	
	return user, nil
}

// Login implements IUserService.Login
func (service *MockUserService) Login(params *requests.LoginRequest) (*repository.User, error) {
	service.mutex.RLock()
	defer service.mutex.RUnlock()
	
	service.LoginCallCount++
	service.LastLoginParams = params
	
	if service.ShouldFailLogin {
		return nil, errors.New(service.LoginErrorMessage)
	}
	
	var user *repository.User
	var exists bool
	
	// Find user by email or username
	if params.Email != "" {
		user, exists = service.usersByEmail[params.Email]
	} else if params.Username != "" {
		user, exists = service.usersByUsername[params.Username]
	} else {
		return nil, errors.New("email or username required")
	}
	
	if !exists {
		return nil, errors.New("user not found")
	}
	
	// Verify password
	err := bcrypt.CompareHashAndPassword([]byte(user.BCryptHash), []byte(params.Password))
	if err != nil {
		return nil, errors.New("invalid password")
	}
	
	return user, nil
}

// Get implements IUserService.Get
func (service *MockUserService) Get(id uuid.UUID) (*repository.User, error) {
	service.mutex.RLock()
	defer service.mutex.RUnlock()
	
	service.GetCallCount++
	service.LastGetID = id
	
	if service.ShouldFailGet {
		return nil, errors.New(service.GetErrorMessage)
	}
	
	user, exists := service.users[id]
	if !exists {
		return nil, errors.New("user not found")
	}
	
	return user, nil
}

// Remove implements IUserService.Remove
func (service *MockUserService) Remove(id uuid.UUID) error {
	service.mutex.Lock()
	defer service.mutex.Unlock()
	
	service.RemoveCallCount++
	service.LastRemoveID = id
	
	if service.ShouldFailRemove {
		return errors.New(service.RemoveErrorMessage)
	}
	
	user, exists := service.users[id]
	if !exists {
		return errors.New("user not found")
	}
	
	// Remove from all lookup maps
	delete(service.users, id)
	delete(service.usersByEmail, user.Email)
	delete(service.usersByUsername, user.Username)
	
	return nil
}

// GetAll implements IUserService.GetAll
func (service *MockUserService) GetAll() ([]repository.User, error) {
	service.mutex.RLock()
	defer service.mutex.RUnlock()
	
	service.GetAllCallCount++
	
	if service.ShouldFailGetAll {
		return nil, errors.New(service.GetAllErrorMessage)
	}
	
	users := make([]repository.User, 0, len(service.users))
	for _, user := range service.users {
		users = append(users, *user)
	}
	
	return users, nil
}

// Update implements IUserService.Update
func (service *MockUserService) Update(user_id uuid.UUID, profile_name string) (*repository.User, error) {
	service.mutex.Lock()
	defer service.mutex.Unlock()
	
	service.UpdateCallCount++
	service.LastUpdateID = user_id
	service.LastUpdateProfile = profile_name
	
	if service.ShouldFailUpdate {
		return nil, errors.New(service.UpdateErrorMessage)
	}
	
	user, exists := service.users[user_id]
	if !exists {
		return nil, errors.New("user not found")
	}
	
	// Update profile picture URL
	now := time.Now()
	user.ProfilePicUrl = &profile_name
	user.UpdatedDatetime = &now
	
	return user, nil
}

// UpdateUserCredentials implements IUserService.UpdateUserCredentials
func (service *MockUserService) UpdateUserCredentials(params *requests.UpdateCredentialsRequest) (*repository.User, error) {
	service.mutex.Lock()
	defer service.mutex.Unlock()
	
	service.UpdateCredsCallCount++
	service.LastUpdateCredsParams = params
	
	if service.ShouldFailUpdateCreds {
		return nil, errors.New(service.UpdateCredsErrorMessage)
	}
	
	user, exists := service.users[params.ID]
	if !exists {
		return nil, errors.New("user not found")
	}
	
	// Check for duplicate email (if changing)
	if params.Email != user.Email {
		if _, emailExists := service.usersByEmail[params.Email]; emailExists {
			return nil, errors.New("email already in use")
		}
	}
	
	// Check for duplicate username (if changing)
	if params.Username != user.Username {
		if _, usernameExists := service.usersByUsername[params.Username]; usernameExists {
			return nil, errors.New("username already in use")
		}
	}
	
	// Update lookup maps if email or username changed
	if params.Email != user.Email {
		delete(service.usersByEmail, user.Email)
		service.usersByEmail[params.Email] = user
	}
	
	if params.Username != user.Username {
		delete(service.usersByUsername, user.Username)
		service.usersByUsername[params.Username] = user
	}
	
	// Update user fields
	now := time.Now()
	user.Email = params.Email
	user.Username = params.Username
	user.UpdatedDatetime = &now
	
	// Update password if provided
	if params.Password != "" {
		if params.OldPassword != "" {
			// Verify old password
			err := bcrypt.CompareHashAndPassword([]byte(user.BCryptHash), []byte(params.OldPassword))
			if err != nil {
				return nil, errors.New("old password is incorrect")
			}
		}
		
		// Hash new password
		hashedPassword, err := bcrypt.GenerateFromPassword([]byte(params.Password), 12)
		if err != nil {
			return nil, errors.New("failed to hash new password")
		}
		user.BCryptHash = string(hashedPassword)
	}
	
	return user, nil
}

// UpdateUserBackgroundImage implements IUserService.UpdateUserBackgroundImage
func (service *MockUserService) UpdateUserBackgroundImage(params *repository.UpdateUserBacgroundParams) (*repository.User, error) {
	service.mutex.Lock()
	defer service.mutex.Unlock()
	
	service.UpdateBgCallCount++
	service.LastUpdateBgParams = params
	
	if service.ShouldFailUpdateBg {
		return nil, errors.New(service.UpdateBgErrorMessage)
	}
	
	user, exists := service.users[params.ID]
	if !exists {
		return nil, errors.New("user not found")
	}
	
	// Update background image
	now := time.Now()
	user.Background = params.Background
	user.UpdatedDatetime = &now
	
	return user, nil
}
