/* Generated by egg v0.0.1 */

package services

import (
	"context"

	"github.com/adamkali/mindscape/db/repository"
	"github.com/adamkali/mindscape/models/requests"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
)

type MockUserService struct {
	ctx  context.Context		
	pool *pgxpool.Pool
}
var EmptyUUID = uuid.MustParse("00000000-0000-0000-0000-000000000000")

// CreateMockUserService returns a reference to a new MockUserService to be used in the controller
func CreateMockUserService(ctx context.Context, pool *pgxpool.Pool) *MockUserService {
	return &MockUserService{
		ctx:  ctx,
		pool: pool,
	}
}

func (service *MockUserService) Create(params *requests.NewUserRequest) (*repository.User, error) {
	BCryptHash, err := hashPassword(params.Password)
	if err != nil {
		return nil, err
	}

	userID := uuid.New()
	user := repository.User{
		ID:       userID,
		Username: params.Username,
		Email:    params.Email,
		BCryptHash: BCryptHash,
		Admin:  params.IsAdmin,
	}
	return &user, nil
}
func (service *MockUserService) Get(id uuid.UUID) (*repository.User, error) {
	user := repository.User{
		ID:       id,
		Username: "testuser",
		Email:    "@example.com",
		BCryptHash: "----------------",
		Admin:  true,
	}
	return &user, nil
}
func (servic *MockUserService) Login(params *requests.LoginRequest) (*repository.User, error) {
	user := &repository.User{
		ID:       EmptyUUID,
		Username: params.Username,
		Email: params.Email,
		BCryptHash: "----------------",
		Admin:  true,
	}
	return user, nil
}
func (service *MockUserService) GetAll() ([]repository.User, error) {
	var users []repository.User = make([]repository.User, 2)
	
	user := repository.User{
		ID:       EmptyUUID,
		Username: "testuser",
		Email:    "@example.com",
		BCryptHash: "----------------",
		Admin:  true,
	}
	users = append(users, user)
	user.ID = EmptyUUID
	users = append(users, user)
	
	return users, nil
}

func (service *MockUserService) Update(user_id uuid.UUID, profile_name string) (*repository.User, error) {
	user := repository.User{
		ID:       user_id,
		Username: profile_name,
		Email:    "@example.com",
		BCryptHash: "----------------",
		Admin:  true,
	}
	return &user, nil
}

func (service *MockUserService) Remove(id uuid.UUID) error {
	return nil
}
