/* Generated by egg v0.0.1 */

package services

import (
	"context"
	//"time"

	"github.com/adamkali/mindscape/db/repository"
)

// AuthService provides authentication services, including creating and checking tokens.
// the MockAuthService struct implements the IAuthService interface. And provides dummy functions
// to obfuscate the connections to the database, as well as the creation of tokens.
// this allows us to test the authentication services without having to connect to a real database.
//
// type IAuthService interface {
// 	Create(user *repository.User) (*string, error)
//  	Update(user repository.User) (*string, error)
// 	CheckToken(token string) error
// }

type MockAuthService struct {
	ctx  context.Context
}

func (MockAuthService *MockAuthService) Create(user *repository.User) (*string, error) {
	// create a dummy token that is 64 characters long
	token := "a============================================================//a"
	return &token, nil
}

func (MockAuthService *MockAuthService) Update(user repository.User) (*string, error) {
	// create a dummy token that is 64 characters long
	token := "a============================================================//a"
	return &token, nil
}

func (MockAuthService *MockAuthService) CheckToken(token string) error {
	return nil
}
