/* Generated by egg v0.0.1 */

package services

import (
	"context"
	"errors"
	"fmt"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"unicode"

	"github.com/adamkali/mindscape/cmd/configuration"
	"github.com/adamkali/mindscape/db/repository"
	"github.com/adamkali/mindscape/models/requests"
	"github.com/adamkali/mindscape/schemas"
	"github.com/google/uuid"
	"github.com/labstack/echo/v4"
)

// ValidatorService struct
//
// This is a static struct that is used to validate the request body
type ValidatorService struct{}

func (ValidatorService *ValidatorService) Promote(ctx context.Context, config *configuration.Configuration) *ValidatorService {
	return ValidatorService
}

func validateUsername(username string) bool {
	trimmed := strings.TrimSpace(username)
	if trimmed == "" {
		return false
	}
	pattern := `^[a-zA-Z0-9]+$`
	_, err := regexp.MatchString(pattern, trimmed)
	if err != nil {
		return false
	}
	return true
}

func validatePassword(s string) (sevenOrMore, number, upper, special bool) {
	for _, c := range s {
		switch {
		case unicode.IsNumber(c):
			number = true
		case unicode.IsUpper(c):
			upper = true
		case unicode.IsPunct(c) || unicode.IsSymbol(c):
			special = true
		}
	}
	sevenOrMore = len(s) >= 8
	return
}

// ValidateNewUserRequest
//
// ValidateNewUserRequest validates the Body by using the echo.Context.Bind(requsts.NewUserRequest)
// and the returns the marshalled object
func (ValidatorService ValidatorService) ValidateNewUserRequest(e echo.Context) (*requests.NewUserRequest, error) {
	validRequest := new(requests.NewUserRequest)
	if err := e.Bind(&validRequest); err != nil {
		return nil, errors.New("Invalid request body. Please check your input and try again")
	}

	if !validateUsername(validRequest.Username) {
		return nil, fmt.Errorf("Validation failed (%s) is not a valid username", validRequest.Username)
	}

	_, err := mail.ParseAddress(validRequest.Email)
	if err != nil {
		return nil, fmt.Errorf("Validation failed (%s) is not a valid email address", validRequest.Email)
	}

	sevenOrMore, number, upper, special := validatePassword(validRequest.Password)
	if !(sevenOrMore && number && upper && special) {
		return nil, fmt.Errorf(
			"Validation failed. Seven Or More (%t), Number (%t), Upper (%t), Special (%t)",
			sevenOrMore,
			number,
			upper,
			special)
	}

	return validRequest, nil
}

// ValidateLoginRequest validates the Body by using the echo.Context.Bind(requsts.LoginRequest)
// and the returns then last part
func (ValidatorService ValidatorService) ValidateLoginRequest(e echo.Context) (*requests.LoginRequest, error) {
	validRequest := new(requests.LoginRequest)
	if err := e.Bind(&validRequest); err != nil {
		return nil, err
	}
	if validRequest.Email == "" && validRequest.Username == "" {
		err := errors.New("Email and Username cannot be null")
		return nil, err
	}
	// validRequest.Username can be sql injection, but only validate if username is provided
	if validRequest.Username != "" && !validateUsername(validRequest.Username) {
		return nil, fmt.Errorf("Validation failed (%s) is not a valid username", validRequest.Username)
	}
	if validRequest.Password == "" {
		err := errors.New("You must send a password")
		return nil, err
	}
	sevenOrMore, number, upper, special := validatePassword(validRequest.Password)
	if !(sevenOrMore && number && upper && special) {
		return nil, fmt.Errorf(
			"Validation failed. Seven Or More (%t), Number (%t), Upper (%t), Special (%t)",
			sevenOrMore,
			number,
			upper,
			special)
	}
	return validRequest, nil
}

// Validate LoginFormRequest ()
func (vs ValidatorService) ValidateLoginFormRequest(e echo.Context) (*requests.LoginRequest, error) {
	req := &requests.LoginRequest{
		Username: e.FormValue("username"),
		Email:    e.FormValue("email"),
		Password: e.FormValue("password"),
	}

	if req.Email == "" && req.Username == "" {
		err := errors.New("Email and Username cannot be null")
		return nil, err
	}
	if req.Password == "" {
		err := errors.New("You must send a password")
		return nil, err
	}
	return req, nil
}

func (vs ValidatorService) ValidateUpdateUserCredentialRequest(e echo.Context) (*requests.UpdateCredentialsRequest, error) {
	validRequest := new(requests.UpdateCredentialsRequest)
	if err := e.Bind(&validRequest); err != nil {
		return nil, err
	}
	if validRequest.ID == uuid.Nil {
		err := errors.New("ID cannot be null")
		return nil, err
	}
	if !validateUsername(validRequest.Username) {
		return nil, fmt.Errorf("Validation failed (%s) is not a valid username", validRequest.Username)
	}

	_, err := mail.ParseAddress(validRequest.Email)
	if err != nil {
		return nil, err
	}
	if validRequest.OldPassword == "" {
		// we do not want to change the password
		return validRequest, nil
	} else if validRequest.Password == "" && validRequest.OldPassword != "" {
		return nil, errors.New("You must send a password to change the password")
	} else {
		sevenOrMore, number, upper, special := validatePassword(validRequest.Password)
		if !(sevenOrMore && number && upper && special) {
			return nil, fmt.Errorf(
				"Validation failed. Seven Or More (%t), Number (%t), Upper (%t), Special (%t)",
				sevenOrMore,
				number,
				upper,
				special)
		}
	}
	return validRequest, nil

}

func (vs ValidatorService) ValidateCreateFolderRequest(e echo.Context) (*repository.CreateFolderParams, error) {
	validRequest := new(repository.CreateFolderParams)
	if err := e.Bind(&validRequest); err != nil {
		fmt.Printf("[ERROR] ValidatorService.ValidateCreateFolderRequest{ err: %v }\n", err)
		return nil, err
	}
	if validRequest.Name == "" {
		return nil, errors.New("Folder name cannot be empty")
	}
	if strings.ContainsAny(validRequest.Name, "/\\:*?\"<>|") {
		return nil, errors.New("Folder name cannot contain any special characters")
	}
	return validRequest, nil
}

func (r ValidatorService) CreateBookmarkRequest(e echo.Context) (*repository.CreateBookmarkParams, error) {
	validRequest := new(repository.CreateBookmarkParams)
	if err := e.Bind(&validRequest); err != nil {
		return nil, err
	}

	// Validate User ID
	if validRequest.UserID == uuid.Nil {
		return nil, errors.New("User ID cannot be null")
	}

	// Validate Folder ID
	if validRequest.FolderID == uuid.Nil {
		return nil, errors.New("Folder ID cannot be null")
	}

	// Validate Name
	if validRequest.Name == "" {
		return nil, errors.New("Bookmark name cannot be empty")
	}

	// Validate Link
	if validRequest.Link == "" {
		return nil, errors.New("Bookmark link cannot be empty")
	}

	// Validate URL format
	u, err := url.Parse(validRequest.Link)
	if err != nil {
		return nil, errors.New("Invalid URL format")
	}

	// Only allow HTTP and HTTPS
	if u.Scheme != "http" && u.Scheme != "https" {
		return nil, errors.New("Only HTTP and HTTPS URLs are allowed")
	}

	// Check for emojis in link
	for _, r := range validRequest.Link {
		if unicode.Is(unicode.So, r) {
			return nil, errors.New("Link cannot contain emojis")
		}
	}

	return validRequest, nil
}

func (r ValidatorService) ValidateBacgroundImageChange(e echo.Context) (*requests.UploadUserBackgroundRequest, error) {
	var err error
	validRequest := new(requests.UploadUserBackgroundRequest)
	formFile, err := e.FormFile("file")
	if err != nil {
		return nil, err
	}
	// check to make sure file is not empty
	validRequest.File = formFile
	if validRequest.File.Size == 0 {
		return nil, errors.New("File is empty")
	}
	//check to make sure file is an image
	if validRequest.File.Header.Get("Content-Type") != "image/jpeg" &&
		validRequest.File.Header.Get("Content-Type") != "image/png" &&
		validRequest.File.Header.Get("Content-Type") != "image/gif" {
		return nil, errors.New("File is not an image")
	}
	return validRequest, nil

}

func (r ValidatorService) ValidateMoveFolderRequest(e echo.Context) (*requests.MoveFolderRequest, error) {
	validRequest := new(requests.MoveFolderRequest)
	if err := e.Bind(&validRequest); err != nil {
		return nil, err
	}

	// Validate User ID
	if validRequest.UserID == uuid.Nil {
		return nil, errors.New("User ID cannot be null")
	}

	// Validate Folder ID
	if validRequest.FolderID == uuid.Nil {
		return nil, errors.New("Folder ID cannot be null")
	}

	// Validate that folder is not being moved to itself
	if validRequest.NewParentID != nil && *validRequest.NewParentID == validRequest.FolderID {
		return nil, errors.New("Cannot move folder to itself")
	}

	return validRequest, nil
}

func (r ValidatorService) ValidateMoveBookmarkRequest(e echo.Context) (*requests.MoveBookmarkRequest, error) {
	validRequest := new(requests.MoveBookmarkRequest)
	if err := e.Bind(&validRequest); err != nil {
		return nil, err
	}
	fmt.Printf("[INFO] ValidatorService.ValidateMoveBookmarkRequest{ validRequest: %v }\n", validRequest)

	// Validate User ID
	if validRequest.UserID == uuid.Nil {
		return nil, errors.New("User ID cannot be null")
	}

	// Validate Bookmark ID
	if validRequest.BookmarkID == uuid.Nil {
		return nil, errors.New("Bookmark ID cannot be null")
	}

	// Validate New Parent ID (bookmarks cannot be moved to root, must have a parent folder)
	if validRequest.NewParentID == uuid.Nil {
		return nil, errors.New("New parent folder ID cannot be null - bookmarks must belong to a folder")
	}

	return validRequest, nil
}

func (r ValidatorService) ValidateAddUserWidgetRequest(e echo.Context) (*requests.AddUserWidgetRequst, error) {
	validRequest := new(requests.AddUserWidgetRequst)

	// Bind the request body first to populate validRequest fields
	if err := e.Bind(&validRequest); err != nil {
		return nil, err
	}

	storage, err := schemas.EmbeddedScemas()
	if err != nil {
		return nil, err
	}

	// get the schema by id from request
	widgetSchema, err := storage.Get(validRequest.SchemaID)
	if err != nil {
		return nil, err
	}

	// check that the size is less than or equal the max size
	if validRequest.Height > ((int32)(widgetSchema.Layout.MaxSize.Height)) {
		return nil, fmt.Errorf("Validation failed. Configured Size is greater than Max Size (%d > %d)", validRequest.Height, widgetSchema.Layout.MaxSize.Height)
	}
	if validRequest.Width > ((int32)(widgetSchema.Layout.MaxSize.Width)) {
		return nil, fmt.Errorf("Validation failed. Configured Size is greater than Max Size (%d > %d)", validRequest.Width, widgetSchema.Layout.MaxSize.Width)
	}
	if validRequest.Height < ((int32)(widgetSchema.Layout.MinSize.Height)) {
		return nil, fmt.Errorf("Validation failed. Configured Size is less than Min Size (%d < %d)", validRequest.Height, widgetSchema.Layout.MinSize.Height)
	}
	if validRequest.Width < ((int32)(widgetSchema.Layout.MinSize.Width)) {
		return nil, fmt.Errorf("Validation failed. Configured Size is less than Min Size (%d < %d)", validRequest.Width, widgetSchema.Layout.MinSize.Width)
	}
	// ==================================================

	return validRequest, nil
}
