/* Generated by egg v0.0.1 */

package user_handlers

import (
	"fmt"

	"github.com/adamkali/mindscape/models/handlers"
	"github.com/adamkali/mindscape/models/responses"
	"github.com/adamkali/mindscape/services"
	"github.com/golang-jwt/jwt/v5"
	"github.com/labstack/echo/v4"
)

type GetProfilePictureHandler struct {
	ctx  echo.Context
	err  error
	code int
	url  string
	Vs   services.ValidatorService
	Rs   services.IRedisService
	Ms   services.IMinioService
	As   services.IAuthService
	Us   services.IUserService
}

func NewGetProfilPictureHandler(
	ctx echo.Context,
	ValidatorService services.ValidatorService,
	RedisService services.IRedisService,
	MinioService services.IMinioService,
	AuthService services.IAuthService,
	UserService services.IUserService,
) *GetProfilePictureHandler {
	return &GetProfilePictureHandler{
		ctx:  ctx,
		err:  nil,
		code: 200,
		Vs:   ValidatorService,
		Rs:   RedisService,
		Ms:   MinioService,
		As:   AuthService,
		Us:   UserService,
	}
}

func (h *GetProfilePictureHandler) Handle() handlers.IHandler {
	jwt_token := h.ctx.Get("user").(*jwt.Token)
	claims := jwt_token.Claims.(*services.CustomJwt)
	userID := claims.UserId
	profilePictureName := ""
	err := h.As.CheckToken(jwt_token.Raw)
	if err != nil {
		return handlers.Lock(h, 401, err)
	}
	user, err := h.Us.Get(userID)
	if user.ProfilePicUrl != nil {
		if profilePictureName != *user.ProfilePicUrl {
			profilePictureName = *user.ProfilePicUrl
			h.url = ""
		}
	}
	if err != nil {
		return handlers.Lock(h, 404, err)
	}
	fmt.Printf("[INFO] GetProfilePictureHandler.Handle{ userID: %v, profilePictureName: %s }\n", userID, profilePictureName)
	h.url, h.err = h.Ms.GetPresigned(
		userID,
		"profile-pic",
		profilePictureName,
	)
	if h.err != nil {
		fmt.Printf("[ERROR] GetProfilePictureHandler.Handle::MinioService.GetPresigned{ userID: %v, profilePictureName: %s }\n", userID, profilePictureName)
		return handlers.Lock(h, 500, h.err)
	}
	return h
}

func (h *GetProfilePictureHandler) JSON() error {
	if h.err != nil {
		return responses.NewStringResponse().Fail(h.ctx, h.code, h.err)
	}
	return responses.NewStringResponse().Successful(h.ctx, h.url)

}
func (h *GetProfilePictureHandler) SetCode(code int) handlers.IHandler {
	h.code = code
	return h
}

func (h *GetProfilePictureHandler) Code() int {
	return h.code
}

func (h *GetProfilePictureHandler) Data() any {
	return h.url
}

func (h *GetProfilePictureHandler) Error() error {
	return h.err
}
func (h *GetProfilePictureHandler) SetError(err error) handlers.IHandler {
	h.err = err
	return h
}
