/* Generated by egg v0.0.1 */

package user_handlers

import (
	"fmt"
	
	"github.com/adamkali/mindscape/db/repository"
	"github.com/adamkali/mindscape/models/handlers"
	"github.com/adamkali/mindscape/models/responses"
	"github.com/adamkali/mindscape/services"
	"github.com/golang-jwt/jwt/v5"
	"github.com/labstack/echo/v4"
)

type GetUsersHandler struct {
	Users      []repository.User
	Context     echo.Context
	err         error
	code        int
	AuthService services.IAuthService
	UserService services.IUserService
}

func NewGetUsersHandler(ctx echo.Context, authService services.IAuthService, userService services.IUserService) *GetUsersHandler {
	return &GetUsersHandler{
		Context:     ctx,
		err:         nil,
		code:        200,
		AuthService: authService,
		UserService: userService,
	}
}

func (h *GetUsersHandler) Handle() handlers.IHandler {
	jwt_token := h.Context.Get("user").(*jwt.Token)
	claims := jwt_token.Claims.(*services.CustomJwt)
	admin := claims.IsAdmin
	err := h.AuthService.CheckToken(jwt_token.Raw)
	if err != nil {
		return handlers.Lock(h, 401, err)
	}
	if !admin {
		return handlers.Lock(h, 403, fmt.Errorf("access denied: admin privileges required"))
	}
	h.Users, err = h.UserService.GetAll()
	if err != nil {
		return handlers.Lock(h, 404, err)
	}
	return h
}

func (h *GetUsersHandler) JSON() error {
	if h.err != nil {
		return responses.NewUsersResponse().Fail(h.Context, h.code, h.err)
	}
	return responses.NewUsersResponse().Successful(h.Context, h.Users)
}

func (h *GetUsersHandler) SetCode(code int) handlers.IHandler {
	h.code = code
	return h
}

func (h *GetUsersHandler) Code() int {
	return h.code
}

func (h *GetUsersHandler) Data() any {
	return h.Users
}

func (h *GetUsersHandler) Error() error {
	return h.err
}

func (h *GetUsersHandler) SetError(err error) handlers.IHandler {
	h.err = err
	return h
}
