version: "3.8"
services:
  mindscape-site:
    build:
      context: .
      dockerfile: Production.Dockerfile
      target: dev
    container_name: mindscape-site
    ports:
      - "${EGG_SERVER_PORT:-60000}:${EGG_SERVER_PORT:-60000}"
    volumes:
      - ./config:/usr/src/config:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${EGG_SERVER_PORT:-60000}/api/_health"]
      interval: 10s
      timeout: 20s
      retries: 5
  mindscape-db:
    image: postgres:14
    container_name: mindscape-db
    ports:
      - "${EGG_DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${EGG_DATABASE_USERNAME:-mindscape}
      POSTGRES_PASSWORD: ${EGG_DATABASE_PASSWORD:-mindscape}
      POSTGRES_DB: ${EGG_DATABASE_DBNAME:-mindscape}
      POSTGRES_HOST: ${EGG_DATABASE_HOST:-mindscape-db}
      POSTGRES_PORT: ${EGG_DATABASE_PORT:-5432}
    restart: unless-stopped
    volumes:
      - mindscape-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${EGG_DATABASE_USERNAME:-mindscape} -d ${EGG_DATABASE_DBNAME:-mindscape}"]
      interval: 10s
      timeout: 20s
      retries: 5
  mindscape-cache:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: mindscape-cache
    ports:
      - "${EGG_CACHE_PORT:-6379}:6379"
    restart: unless-stopped
    environment:
      - DRAGONFLYDB_USER=${EGG_CACHE_USERNAME:-mindscape}
      - DRAGONFLYDB_PASSWORD=${EGG_CACHE_PASSWORD:-mindscape}
      - DRAGONFLYDB_HOST=${EGG_CACHE_HOST:-mindscape-cache}
      - DRAGONFLYDB_PORT=${EGG_CACHE_PORT:-6379}
      - DRAGONFLYDB_DB=${EGG_CACHE_DB:-mindscape}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 20s
      retries: 5
  mindscape-s3:
    image: "quay.io/minio/minio:latest"
    command: 'server /data --console-address ":9001"'
    environment:
      - MINIO_SERVER_URL="localhost:9001"
      - MINIO_BROWSER_REDIRECT_URL="${EGG_S3_URL:-http://localhost:9000}"
      - MINIO_ROOT_USER="${EGG_S3_USERNAME:-6242f04a-ea36-4778-a181-4a58065a0624}"
      - MINIO_ROOT_PASSWORD="${EGG_S3_PASSWORD:-8a9020bd-3795-4b4f-93ef-34c810c177cc}
    volumes:
      - "minio-data:/data"
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      interval: 10s
      timeout: 20s
      retries: 5
volumes:
  mindscape-db-data:
