// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bookmarks.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (
    user_id, folder_id, name, link
) VALUES ( $1, $2, $3, $4 )
RETURNING id, user_id, folder_id, name, link, icon, description, created_datetime, updated_datetime
`

type CreateBookmarkParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FolderID uuid.UUID `json:"folder_id"`
	Name     string    `json:"name"`
	Link     string    `json:"link"`
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRow(ctx, createBookmark,
		arg.UserID,
		arg.FolderID,
		arg.Name,
		arg.Link,
	)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FolderID,
		&i.Name,
		&i.Link,
		&i.Icon,
		&i.Description,
		&i.CreatedDatetime,
		&i.UpdatedDatetime,
	)
	return i, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks WHERE id = $1
`

func (q *Queries) DeleteBookmark(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBookmark, id)
	return err
}

const findBookmarkById = `-- name: FindBookmarkById :one
SELECT id, user_id, folder_id, name, link, icon, description, created_datetime, updated_datetime
FROM bookmarks 
WHERE id = $1
`

func (q *Queries) FindBookmarkById(ctx context.Context, id uuid.UUID) (Bookmark, error) {
	row := q.db.QueryRow(ctx, findBookmarkById, id)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FolderID,
		&i.Name,
		&i.Link,
		&i.Icon,
		&i.Description,
		&i.CreatedDatetime,
		&i.UpdatedDatetime,
	)
	return i, err
}

const findBookmarkByUserIdMostRecent = `-- name: FindBookmarkByUserIdMostRecent :one
SELECT id, user_id, folder_id, name, link, icon, description, created_datetime, updated_datetime
FROM bookmarks 
WHERE user_id = $1
ORDER BY updated_datetime DESC
LIMIT 1
`

func (q *Queries) FindBookmarkByUserIdMostRecent(ctx context.Context, userID uuid.UUID) (Bookmark, error) {
	row := q.db.QueryRow(ctx, findBookmarkByUserIdMostRecent, userID)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FolderID,
		&i.Name,
		&i.Link,
		&i.Icon,
		&i.Description,
		&i.CreatedDatetime,
		&i.UpdatedDatetime,
	)
	return i, err
}

const findBookmarksAll = `-- name: FindBookmarksAll :many
SELECT id, user_id, folder_id, name, link, icon, description, created_datetime, updated_datetime
FROM bookmarks
`

func (q *Queries) FindBookmarksAll(ctx context.Context) ([]Bookmark, error) {
	rows, err := q.db.Query(ctx, findBookmarksAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bookmark
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FolderID,
			&i.Name,
			&i.Link,
			&i.Icon,
			&i.Description,
			&i.CreatedDatetime,
			&i.UpdatedDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findBookmarksByFolderId = `-- name: FindBookmarksByFolderId :many
SELECT id, user_id, folder_id, name, link, icon, description, created_datetime, updated_datetime
FROM bookmarks 
WHERE folder_id = $1
`

func (q *Queries) FindBookmarksByFolderId(ctx context.Context, folderID uuid.UUID) ([]Bookmark, error) {
	rows, err := q.db.Query(ctx, findBookmarksByFolderId, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bookmark
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FolderID,
			&i.Name,
			&i.Link,
			&i.Icon,
			&i.Description,
			&i.CreatedDatetime,
			&i.UpdatedDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findBookmarksByUserIDDateTimeRange = `-- name: FindBookmarksByUserIDDateTimeRange :many
SELECT id, user_id, folder_id, name, link, icon, description, created_datetime, updated_datetime
FROM bookmarks 
WHERE user_id = $1
AND updated_datetime BETWEEN $2 AND $3
`

type FindBookmarksByUserIDDateTimeRangeParams struct {
	UserID            uuid.UUID  `json:"user_id"`
	UpdatedDatetime   *time.Time `json:"updated_datetime"`
	UpdatedDatetime_2 *time.Time `json:"updated_datetime_2"`
}

func (q *Queries) FindBookmarksByUserIDDateTimeRange(ctx context.Context, arg FindBookmarksByUserIDDateTimeRangeParams) ([]Bookmark, error) {
	rows, err := q.db.Query(ctx, findBookmarksByUserIDDateTimeRange, arg.UserID, arg.UpdatedDatetime, arg.UpdatedDatetime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bookmark
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FolderID,
			&i.Name,
			&i.Link,
			&i.Icon,
			&i.Description,
			&i.CreatedDatetime,
			&i.UpdatedDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findBookmarksByUserId = `-- name: FindBookmarksByUserId :many
SELECT id, user_id, folder_id, name, link, icon, description, created_datetime, updated_datetime
FROM bookmarks 
WHERE user_id = $1
`

func (q *Queries) FindBookmarksByUserId(ctx context.Context, userID uuid.UUID) ([]Bookmark, error) {
	rows, err := q.db.Query(ctx, findBookmarksByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bookmark
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FolderID,
			&i.Name,
			&i.Link,
			&i.Icon,
			&i.Description,
			&i.CreatedDatetime,
			&i.UpdatedDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findBookmarksByUserIdMostRecent = `-- name: FindBookmarksByUserIdMostRecent :many
SELECT id, user_id, folder_id, name, link, icon, description, created_datetime, updated_datetime
FROM bookmarks 
WHERE user_id = $1
ORDER BY updated_datetime DESC
`

func (q *Queries) FindBookmarksByUserIdMostRecent(ctx context.Context, userID uuid.UUID) ([]Bookmark, error) {
	rows, err := q.db.Query(ctx, findBookmarksByUserIdMostRecent, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bookmark
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FolderID,
			&i.Name,
			&i.Link,
			&i.Icon,
			&i.Description,
			&i.CreatedDatetime,
			&i.UpdatedDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveBookmark = `-- name: MoveBookmark :exec
UPDATE bookmarks 
SET folder_id = $2, updated_datetime = now()
WHERE id = $1
`

type MoveBookmarkParams struct {
	ID       uuid.UUID `json:"id"`
	FolderID uuid.UUID `json:"folder_id"`
}

func (q *Queries) MoveBookmark(ctx context.Context, arg MoveBookmarkParams) error {
	_, err := q.db.Exec(ctx, moveBookmark, arg.ID, arg.FolderID)
	return err
}

const updateBookmark = `-- name: UpdateBookmark :exec
UPDATE bookmarks 
SET folder_id = $2, name = $3, link = $4, updated_datetime = now()
WHERE id = $1
`

type UpdateBookmarkParams struct {
	ID       uuid.UUID `json:"id"`
	FolderID uuid.UUID `json:"folder_id"`
	Name     string    `json:"name"`
	Link     string    `json:"link"`
}

func (q *Queries) UpdateBookmark(ctx context.Context, arg UpdateBookmarkParams) error {
	_, err := q.db.Exec(ctx, updateBookmark,
		arg.ID,
		arg.FolderID,
		arg.Name,
		arg.Link,
	)
	return err
}
