// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: households.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMember = `-- name: AddMember :one
INSERT INTO household_members (
    household_id, user_id, role
) VALUES ( $1, $2, $3 )
RETURNING id, household_id, user_id, role, joined_at
`

type AddMemberParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (HouseholdMember, error) {
	row := q.db.QueryRow(ctx, addMember, arg.HouseholdID, arg.UserID, arg.Role)
	var i HouseholdMember
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (
    name, owner_id
) VALUES ( $1, $2 )
RETURNING id, name, owner_id, created_at
`

type CreateHouseholdParams struct {
	Name    string    `json:"name"`
	OwnerID uuid.UUID `json:"owner_id"`
}

// POST queries
func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold, arg.Name, arg.OwnerID)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO household_invites (
    household_id, invited_user_id, code, expires_at, created_by
) VALUES ( $1, $2, $3, $4, $5 )
RETURNING id, household_id, invited_user_id, code, expires_at, accepted_at, created_by, created_at
`

type CreateInviteParams struct {
	HouseholdID   uuid.UUID  `json:"household_id"`
	InvitedUserID uuid.UUID  `json:"invited_user_id"`
	Code          string     `json:"code"`
	ExpiresAt     *time.Time `json:"expires_at"`
	CreatedBy     uuid.UUID  `json:"created_by"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.HouseholdID,
		arg.InvitedUserID,
		arg.Code,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i HouseholdInvite
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.InvitedUserID,
		&i.Code,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHousehold = `-- name: DeleteHousehold :exec
DELETE FROM households WHERE id = $1
`

func (q *Queries) DeleteHousehold(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHousehold, id)
	return err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM household_invites WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvite, id)
	return err
}

const getHouseholdByID = `-- name: GetHouseholdByID :one
SELECT id, name, owner_id, created_at
FROM households
WHERE id = $1
`

// GET queries
func (q *Queries) GetHouseholdByID(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByID, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getHouseholdsByUserID = `-- name: GetHouseholdsByUserID :many
SELECT h.id, h.name, h.owner_id, h.created_at
FROM households h
JOIN household_members m ON m.household_id = h.id
WHERE m.user_id = $1
ORDER BY h.created_at DESC
`

func (q *Queries) GetHouseholdsByUserID(ctx context.Context, userID uuid.UUID) ([]Household, error) {
	rows, err := q.db.Query(ctx, getHouseholdsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Household
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, household_id, invited_user_id, code, expires_at, accepted_at, created_by, created_at
FROM household_invites
WHERE code = $1
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByCode, code)
	var i HouseholdInvite
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.InvitedUserID,
		&i.Code,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitesByUserID = `-- name: GetInvitesByUserID :many
SELECT i.id, i.household_id, i.invited_user_id, i.code, i.expires_at, i.created_by, i.created_at, h.name AS household_name
FROM household_invites i
JOIN households h ON h.id = i.household_id
WHERE i.invited_user_id = $1 AND i.accepted_at IS NULL AND i.expires_at > now()
ORDER BY i.created_at DESC
`

type GetInvitesByUserIDRow struct {
	ID            uuid.UUID  `json:"id"`
	HouseholdID   uuid.UUID  `json:"household_id"`
	InvitedUserID uuid.UUID  `json:"invited_user_id"`
	Code          string     `json:"code"`
	ExpiresAt     *time.Time `json:"expires_at"`
	CreatedBy     uuid.UUID  `json:"created_by"`
	CreatedAt     *time.Time `json:"created_at"`
	HouseholdName string     `json:"household_name"`
}

func (q *Queries) GetInvitesByUserID(ctx context.Context, invitedUserID uuid.UUID) ([]GetInvitesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getInvitesByUserID, invitedUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInvitesByUserIDRow
	for rows.Next() {
		var i GetInvitesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.InvitedUserID,
			&i.Code,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.HouseholdName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMember = `-- name: GetMember :one
SELECT id, household_id, user_id, role, joined_at
FROM household_members
WHERE household_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (HouseholdMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.HouseholdID, arg.UserID)
	var i HouseholdMember
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getMembersByHouseholdID = `-- name: GetMembersByHouseholdID :many
SELECT m.id, m.household_id, m.user_id, m.role, m.joined_at, u.username
FROM household_members m
JOIN users u ON u.id = m.user_id
WHERE m.household_id = $1
ORDER BY m.joined_at ASC
`

type GetMembersByHouseholdIDRow struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UserID      uuid.UUID  `json:"user_id"`
	Role        string     `json:"role"`
	JoinedAt    *time.Time `json:"joined_at"`
	Username    string     `json:"username"`
}

func (q *Queries) GetMembersByHouseholdID(ctx context.Context, householdID uuid.UUID) ([]GetMembersByHouseholdIDRow, error) {
	rows, err := q.db.Query(ctx, getMembersByHouseholdID, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembersByHouseholdIDRow
	for rows.Next() {
		var i GetMembersByHouseholdIDRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteAccepted = `-- name: MarkInviteAccepted :exec
UPDATE household_invites
SET accepted_at = now()
WHERE id = $1
`

// PUT queries
func (q *Queries) MarkInviteAccepted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInviteAccepted, id)
	return err
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM household_members
WHERE household_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
}

// DELETE queries
func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.HouseholdID, arg.UserID)
	return err
}
