// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Bookmark struct {
	ID              uuid.UUID  `json:"id"`
	UserID          uuid.UUID  `json:"user_id"`
	FolderID        uuid.UUID  `json:"folder_id"`
	Name            string     `json:"name"`
	Link            string     `json:"link"`
	Icon            *string    `json:"icon"`
	Description     *string    `json:"description"`
	CreatedDatetime *time.Time `json:"created_datetime"`
	UpdatedDatetime *time.Time `json:"updated_datetime"`
}

type Folder struct {
	ID              uuid.UUID   `json:"id"`
	ParentID        pgtype.UUID `json:"parent_id"`
	UserID          uuid.UUID   `json:"user_id"`
	Name            string      `json:"name"`
	Description     *string     `json:"description"`
	CreatedDatetime *time.Time  `json:"created_datetime"`
	UpdatedDatetime *time.Time  `json:"updated_datetime"`
}

type Note struct {
	ID              uuid.UUID  `json:"id"`
	UserID          uuid.UUID  `json:"user_id"`
	FolderID        uuid.UUID  `json:"folder_id"`
	Name            string     `json:"name"`
	Description     *string    `json:"description"`
	Content         string     `json:"content"`
	CreatedDatetime *time.Time `json:"created_datetime"`
	UpdatedDatetime *time.Time `json:"updated_datetime"`
}

type Task struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	TaskTypeID  uuid.UUID          `json:"task_type_id"`
	Name        *string            `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   *time.Time         `json:"created_at"`
	DueAt       pgtype.Timestamptz `json:"due_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type TaskType struct {
	ID              uuid.UUID  `json:"id"`
	Name            *string    `json:"name"`
	ShowInScheduled bool       `json:"show_in_scheduled"`
	ShowInCompleted bool       `json:"show_in_completed"`
	ShowInAvailable bool       `json:"show_in_available"`
	ShowInCancelled bool       `json:"show_in_cancelled"`
	CreatedAt       *time.Time `json:"created_at"`
}

type Token struct {
	ID                 uuid.UUID  `json:"id"`
	UserID             uuid.UUID  `json:"user_id"`
	ExpirationDatetime *time.Time `json:"expiration_datetime"`
	Token              *string    `json:"token"`
}

type User struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	Username        string     `json:"username"`
	CreatedDatetime *time.Time `json:"created_datetime"`
	UpdatedDatetime *time.Time `json:"updated_datetime"`
	ProfilePicUrl   *string    `json:"profile_pic_url"`
	BCryptHash      string     `json:"b_crypt_hash"`
	Admin           bool       `json:"admin"`
	Background      *string    `json:"background"`
}

type UserWidget struct {
	ID              uuid.UUID  `json:"id"`
	UserID          uuid.UUID  `json:"user_id"`
	SchemaID        uuid.UUID  `json:"schema_id"`
	Config          []byte     `json:"config"`
	PositionX       int32      `json:"position_x"`
	PositionY       int32      `json:"position_y"`
	Width           int32      `json:"width"`
	Height          int32      `json:"height"`
	ZIndex          int32      `json:"z_index"`
	IsVisible       bool       `json:"is_visible"`
	CreatedDatetime *time.Time `json:"created_datetime"`
	UpdatedDatetime *time.Time `json:"updated_datetime"`
	SchemaTitle     *string    `json:"schema_title"`
}
