// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Bookmark struct {
	ID              uuid.UUID  `json:"id"`
	UserID          uuid.UUID  `json:"user_id"`
	FolderID        uuid.UUID  `json:"folder_id"`
	Name            string     `json:"name"`
	Link            string     `json:"link"`
	Icon            *string    `json:"icon"`
	Description     *string    `json:"description"`
	CreatedDatetime *time.Time `json:"created_datetime"`
	UpdatedDatetime *time.Time `json:"updated_datetime"`
}

type Folder struct {
	ID              uuid.UUID   `json:"id"`
	ParentID        pgtype.UUID `json:"parent_id"`
	UserID          uuid.UUID   `json:"user_id"`
	Name            string      `json:"name"`
	Description     *string     `json:"description"`
	CreatedDatetime *time.Time  `json:"created_datetime"`
	UpdatedDatetime *time.Time  `json:"updated_datetime"`
}

type Note struct {
	ID              uuid.UUID  `json:"id"`
	UserID          uuid.UUID  `json:"user_id"`
	FolderID        uuid.UUID  `json:"folder_id"`
	Name            string     `json:"name"`
	Description     *string    `json:"description"`
	Content         string     `json:"content"`
	CreatedDatetime *time.Time `json:"created_datetime"`
	UpdatedDatetime *time.Time `json:"updated_datetime"`
}

type Token struct {
	ID                 uuid.UUID  `json:"id"`
	UserID             uuid.UUID  `json:"user_id"`
	ExpirationDatetime *time.Time `json:"expiration_datetime"`
	Token              *string    `json:"token"`
}

type User struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	Username        string     `json:"username"`
	CreatedDatetime *time.Time `json:"created_datetime"`
	UpdatedDatetime *time.Time `json:"updated_datetime"`
	ProfilePicUrl   *string    `json:"profile_pic_url"`
	BCryptHash      string     `json:"b_crypt_hash"`
	Admin           bool       `json:"admin"`
	Background      *string    `json:"background"`
}
