// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id, refresh_token_hash, user_agent, expires_at
) VALUES ( $1, $2, $3, $4 )
RETURNING id, user_id, refresh_token_hash, user_agent, expires_at, created_at, last_used_at
`

type CreateSessionParams struct {
	UserID           uuid.UUID  `json:"user_id"`
	RefreshTokenHash *string    `json:"refresh_token_hash"`
	UserAgent        *string    `json:"user_agent"`
	ExpiresAt        *time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionByHash = `-- name: DeleteSessionByHash :exec
DELETE FROM sessions WHERE refresh_token_hash = $1
`

func (q *Queries) DeleteSessionByHash(ctx context.Context, refreshTokenHash *string) error {
	_, err := q.db.Exec(ctx, deleteSessionByHash, refreshTokenHash)
	return err
}

const deleteSessionsByUserId = `-- name: DeleteSessionsByUserId :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserId(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUserId, userID)
	return err
}

const findSessionByHash = `-- name: FindSessionByHash :one
SELECT id, user_id, refresh_token_hash, user_agent, expires_at, created_at, last_used_at
    FROM sessions
    WHERE refresh_token_hash = $1
    AND expires_at > now()
`

func (q *Queries) FindSessionByHash(ctx context.Context, refreshTokenHash *string) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const rotateSession = `-- name: RotateSession :one
UPDATE sessions
    SET refresh_token_hash = $1, expires_at = $2, last_used_at = now()
    WHERE refresh_token_hash = $3
    AND expires_at > now()
RETURNING id, user_id, refresh_token_hash, user_agent, expires_at, created_at, last_used_at
`

type RotateSessionParams struct {
	RefreshTokenHash   *string    `json:"refresh_token_hash"`
	ExpiresAt          *time.Time `json:"expires_at"`
	RefreshTokenHash_2 *string    `json:"refresh_token_hash_2"`
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSession, arg.RefreshTokenHash, arg.ExpiresAt, arg.RefreshTokenHash_2)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
