// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_widget.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createUserWidget = `-- name: CreateUserWidget :one
INSERT INTO user_widgets (
	user_id,
	schema_title,
	schema_id,
	config,
	position_x,
	position_y,
	width,
	height,
	z_index,
	is_visible
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, user_id, schema_id, config, position_x, position_y, width, height, z_index, is_visible, created_datetime, updated_datetime, schema_title
`

type CreateUserWidgetParams struct {
	UserID      uuid.UUID `json:"user_id"`
	SchemaTitle *string   `json:"schema_title"`
	SchemaID    uuid.UUID `json:"schema_id"`
	Config      []byte    `json:"config"`
	PositionX   int32     `json:"position_x"`
	PositionY   int32     `json:"position_y"`
	Width       int32     `json:"width"`
	Height      int32     `json:"height"`
	ZIndex      int32     `json:"z_index"`
	IsVisible   bool      `json:"is_visible"`
}

func (q *Queries) CreateUserWidget(ctx context.Context, arg CreateUserWidgetParams) (UserWidget, error) {
	row := q.db.QueryRow(ctx, createUserWidget,
		arg.UserID,
		arg.SchemaTitle,
		arg.SchemaID,
		arg.Config,
		arg.PositionX,
		arg.PositionY,
		arg.Width,
		arg.Height,
		arg.ZIndex,
		arg.IsVisible,
	)
	var i UserWidget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SchemaID,
		&i.Config,
		&i.PositionX,
		&i.PositionY,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.IsVisible,
		&i.CreatedDatetime,
		&i.UpdatedDatetime,
		&i.SchemaTitle,
	)
	return i, err
}

const deleteUserWidget = `-- name: DeleteUserWidget :exec
DELETE FROM user_widgets WHERE id = $1
`

func (q *Queries) DeleteUserWidget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserWidget, id)
	return err
}

const findUserWidgetByID = `-- name: FindUserWidgetByID :one
SELECT id, user_id, schema_id, config, position_x, position_y, width, height, z_index, is_visible, created_datetime, updated_datetime, schema_title FROM user_widgets WHERE id = $1
`

func (q *Queries) FindUserWidgetByID(ctx context.Context, id uuid.UUID) (UserWidget, error) {
	row := q.db.QueryRow(ctx, findUserWidgetByID, id)
	var i UserWidget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SchemaID,
		&i.Config,
		&i.PositionX,
		&i.PositionY,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.IsVisible,
		&i.CreatedDatetime,
		&i.UpdatedDatetime,
		&i.SchemaTitle,
	)
	return i, err
}

const findUserWidgetsByUserID = `-- name: FindUserWidgetsByUserID :many
SELECT id, user_id, schema_id, config, position_x, position_y, width, height, z_index, is_visible, created_datetime, updated_datetime, schema_title FROM user_widgets WHERE user_id = $1
`

func (q *Queries) FindUserWidgetsByUserID(ctx context.Context, userID uuid.UUID) ([]UserWidget, error) {
	rows, err := q.db.Query(ctx, findUserWidgetsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserWidget
	for rows.Next() {
		var i UserWidget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SchemaID,
			&i.Config,
			&i.PositionX,
			&i.PositionY,
			&i.Width,
			&i.Height,
			&i.ZIndex,
			&i.IsVisible,
			&i.CreatedDatetime,
			&i.UpdatedDatetime,
			&i.SchemaTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserWidget = `-- name: UpdateUserWidget :one
UPDATE user_widgets SET
	config = $2,
	position_x = $3,
	position_y = $4,
	width = $5,
	height = $6,
	z_index = $7,
	is_visible = $8
WHERE id = $1 RETURNING id, user_id, schema_id, config, position_x, position_y, width, height, z_index, is_visible, created_datetime, updated_datetime, schema_title
`

type UpdateUserWidgetParams struct {
	ID        uuid.UUID `json:"id"`
	Config    []byte    `json:"config"`
	PositionX int32     `json:"position_x"`
	PositionY int32     `json:"position_y"`
	Width     int32     `json:"width"`
	Height    int32     `json:"height"`
	ZIndex    int32     `json:"z_index"`
	IsVisible bool      `json:"is_visible"`
}

func (q *Queries) UpdateUserWidget(ctx context.Context, arg UpdateUserWidgetParams) (UserWidget, error) {
	row := q.db.QueryRow(ctx, updateUserWidget,
		arg.ID,
		arg.Config,
		arg.PositionX,
		arg.PositionY,
		arg.Width,
		arg.Height,
		arg.ZIndex,
		arg.IsVisible,
	)
	var i UserWidget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SchemaID,
		&i.Config,
		&i.PositionX,
		&i.PositionY,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.IsVisible,
		&i.CreatedDatetime,
		&i.UpdatedDatetime,
		&i.SchemaTitle,
	)
	return i, err
}
