/* Generated by egg v0.0.1 */

package responses

import (
	"github.com/adamkali/mindscape/db/repository"
	"github.com/labstack/echo/v4"
)

type UsersResponse struct {
	Data    []UserData        `json:"data"`
	Success bool              `json:"success"`
	Message string            `json:"message"`
} // @name UsersResponse

func NewUsersResponse() *UsersResponse {
	return &UsersResponse{Success: false, Message: ""}
}


func (UsersResponse *UsersResponse) Fail(ctx echo.Context, code int, err error) error {
	UsersResponse.Message = err.Error()
	return ctx.JSON(code, UsersResponse)
}

func (UsersResponse *UsersResponse) Successful(ctx echo.Context, users []repository.User) error {
	UsersResponse.Data = make([]UserData, len(users))
	for i, val := range users {
		 UsersResponse.Data[i] = *UserDataFromRepository(&val)
	}
	UsersResponse.Success = true
	return ctx.JSON(200, UsersResponse)
}
