/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AddUserWidgetRequest
 */
export interface AddUserWidgetRequest {
	/**
	 *
	 * @type {Array<number>}
	 * @memberof AddUserWidgetRequest
	 */
	config?: Array<number>;
	/**
	 *
	 * @type {number}
	 * @memberof AddUserWidgetRequest
	 */
	height?: number;
	/**
	 *
	 * @type {boolean}
	 * @memberof AddUserWidgetRequest
	 */
	isVisible?: boolean;
	/**
	 *
	 * @type {number}
	 * @memberof AddUserWidgetRequest
	 */
	positionX?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AddUserWidgetRequest
	 */
	positionY?: number;
	/**
	 *
	 * @type {string}
	 * @memberof AddUserWidgetRequest
	 */
	schemaId?: string;
	/**
	 *
	 * @type {number}
	 * @memberof AddUserWidgetRequest
	 */
	width?: number;
	/**
	 *
	 * @type {number}
	 * @memberof AddUserWidgetRequest
	 */
	zIndex?: number;
}

/**
 * Check if a given object implements the AddUserWidgetRequest interface.
 */
export function instanceOfAddUserWidgetRequest(
	value: object,
): value is AddUserWidgetRequest {
	return true;
}

export function AddUserWidgetRequestFromJSON(json: any): AddUserWidgetRequest {
	return AddUserWidgetRequestFromJSONTyped(json, false);
}

export function AddUserWidgetRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): AddUserWidgetRequest {
	if (json == null) {
		return json;
	}
	return {
		config: json['config'] == null ? undefined : json['config'],
		height: json['height'] == null ? undefined : json['height'],
		isVisible: json['is_visible'] == null ? undefined : json['is_visible'],
		positionX: json['position_x'] == null ? undefined : json['position_x'],
		positionY: json['position_y'] == null ? undefined : json['position_y'],
		schemaId: json['schema_id'] == null ? undefined : json['schema_id'],
		width: json['width'] == null ? undefined : json['width'],
		zIndex: json['z_index'] == null ? undefined : json['z_index'],
	};
}

export function AddUserWidgetRequestToJSON(json: any): AddUserWidgetRequest {
	return AddUserWidgetRequestToJSONTyped(json, false);
}

export function AddUserWidgetRequestToJSONTyped(
	value?: AddUserWidgetRequest | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		config: value['config'],
		height: value['height'],
		is_visible: value['isVisible'],
		position_x: value['positionX'],
		position_y: value['positionY'],
		schema_id: value['schemaId'],
		width: value['width'],
		z_index: value['zIndex'],
	};
}
