/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BackgroundData } from './BackgroundData';
import {
    BackgroundDataFromJSON,
    BackgroundDataFromJSONTyped,
    BackgroundDataToJSON,
    BackgroundDataToJSONTyped,
} from './BackgroundData';

/**
 * 
 * @export
 * @interface BackgroundResponse
 */
export interface BackgroundResponse {
    /**
     * 
     * @type {Array<BackgroundData>}
     * @memberof BackgroundResponse
     */
    data?: Array<BackgroundData>;
    /**
     * 
     * @type {string}
     * @memberof BackgroundResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BackgroundResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the BackgroundResponse interface.
 */
export function instanceOfBackgroundResponse(value: object): value is BackgroundResponse {
    return true;
}

export function BackgroundResponseFromJSON(json: any): BackgroundResponse {
    return BackgroundResponseFromJSONTyped(json, false);
}

export function BackgroundResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackgroundResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(BackgroundDataFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function BackgroundResponseToJSON(json: any): BackgroundResponse {
    return BackgroundResponseToJSONTyped(json, false);
}

export function BackgroundResponseToJSONTyped(value?: BackgroundResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(BackgroundDataToJSON)),
        'message': value['message'],
        'success': value['success'],
    };
}

