/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepositoryBookmark } from './RepositoryBookmark';
import {
	RepositoryBookmarkFromJSON,
	RepositoryBookmarkFromJSONTyped,
	RepositoryBookmarkToJSON,
	RepositoryBookmarkToJSONTyped,
} from './RepositoryBookmark';

/**
 *
 * @export
 * @interface BookmarksResponse
 */
export interface BookmarksResponse {
	/**
	 *
	 * @type {Array<RepositoryBookmark>}
	 * @memberof BookmarksResponse
	 */
	data?: Array<RepositoryBookmark>;
	/**
	 *
	 * @type {string}
	 * @memberof BookmarksResponse
	 */
	message?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof BookmarksResponse
	 */
	success?: boolean;
}

/**
 * Check if a given object implements the BookmarksResponse interface.
 */
export function instanceOfBookmarksResponse(
	value: object,
): value is BookmarksResponse {
	return true;
}

export function BookmarksResponseFromJSON(json: any): BookmarksResponse {
	return BookmarksResponseFromJSONTyped(json, false);
}

export function BookmarksResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): BookmarksResponse {
	if (json == null) {
		return json;
	}
	return {
		data:
			json['data'] == null
				? undefined
				: (json['data'] as Array<any>).map(RepositoryBookmarkFromJSON),
		message: json['message'] == null ? undefined : json['message'],
		success: json['success'] == null ? undefined : json['success'],
	};
}

export function BookmarksResponseToJSON(json: any): BookmarksResponse {
	return BookmarksResponseToJSONTyped(json, false);
}

export function BookmarksResponseToJSONTyped(
	value?: BookmarksResponse | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		data:
			value['data'] == null
				? undefined
				: (value['data'] as Array<any>).map(RepositoryBookmarkToJSON),
		message: value['message'],
		success: value['success'],
	};
}
