/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepositoryBookmark } from './RepositoryBookmark';
import {
	RepositoryBookmarkFromJSON,
	RepositoryBookmarkFromJSONTyped,
	RepositoryBookmarkToJSON,
	RepositoryBookmarkToJSONTyped,
} from './RepositoryBookmark';

/**
 *
 * @export
 * @interface BookmarkResponse
 */
export interface BookmarkResponse {
	/**
	 *
	 * @type {RepositoryBookmark}
	 * @memberof BookmarkResponse
	 */
	data?: RepositoryBookmark;
	/**
	 *
	 * @type {string}
	 * @memberof BookmarkResponse
	 */
	message?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof BookmarkResponse
	 */
	success?: boolean;
}

/**
 * Check if a given object implements the BookmarkResponse interface.
 */
export function instanceOfBookmarkResponse(
	value: object,
): value is BookmarkResponse {
	return true;
}

export function BookmarkResponseFromJSON(json: any): BookmarkResponse {
	return BookmarkResponseFromJSONTyped(json, false);
}

export function BookmarkResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): BookmarkResponse {
	if (json == null) {
		return json;
	}
	return {
		data:
			json['data'] == null
				? undefined
				: RepositoryBookmarkFromJSON(json['data']),
		message: json['message'] == null ? undefined : json['message'],
		success: json['success'] == null ? undefined : json['success'],
	};
}

export function BookmarkResponseToJSON(json: any): BookmarkResponse {
	return BookmarkResponseToJSONTyped(json, false);
}

export function BookmarkResponseToJSONTyped(
	value?: BookmarkResponse | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		data: RepositoryBookmarkToJSON(value['data']),
		message: value['message'],
		success: value['success'],
	};
}
