/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesCoolifyActionData } from './ResponsesCoolifyActionData';
import {
	ResponsesCoolifyActionDataFromJSON,
	ResponsesCoolifyActionDataFromJSONTyped,
	ResponsesCoolifyActionDataToJSON,
	ResponsesCoolifyActionDataToJSONTyped,
} from './ResponsesCoolifyActionData';

/**
 *
 * @export
 * @interface CoolifyActionResponse
 */
export interface CoolifyActionResponse {
	/**
	 *
	 * @type {ResponsesCoolifyActionData}
	 * @memberof CoolifyActionResponse
	 */
	data?: ResponsesCoolifyActionData;
	/**
	 *
	 * @type {string}
	 * @memberof CoolifyActionResponse
	 */
	message?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof CoolifyActionResponse
	 */
	success?: boolean;
}

/**
 * Check if a given object implements the CoolifyActionResponse interface.
 */
export function instanceOfCoolifyActionResponse(
	value: object,
): value is CoolifyActionResponse {
	return true;
}

export function CoolifyActionResponseFromJSON(
	json: any,
): CoolifyActionResponse {
	return CoolifyActionResponseFromJSONTyped(json, false);
}

export function CoolifyActionResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): CoolifyActionResponse {
	if (json == null) {
		return json;
	}
	return {
		data:
			json['data'] == null
				? undefined
				: ResponsesCoolifyActionDataFromJSON(json['data']),
		message: json['message'] == null ? undefined : json['message'],
		success: json['success'] == null ? undefined : json['success'],
	};
}

export function CoolifyActionResponseToJSON(json: any): CoolifyActionResponse {
	return CoolifyActionResponseToJSONTyped(json, false);
}

export function CoolifyActionResponseToJSONTyped(
	value?: CoolifyActionResponse | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		data: ResponsesCoolifyActionDataToJSON(value['data']),
		message: value['message'],
		success: value['success'],
	};
}
