/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoolifyWidgetApplication } from './CoolifyWidgetApplication';
import {
    CoolifyWidgetApplicationFromJSON,
    CoolifyWidgetApplicationFromJSONTyped,
    CoolifyWidgetApplicationToJSON,
    CoolifyWidgetApplicationToJSONTyped,
} from './CoolifyWidgetApplication';
import type { CoolifyWidgetService } from './CoolifyWidgetService';
import {
    CoolifyWidgetServiceFromJSON,
    CoolifyWidgetServiceFromJSONTyped,
    CoolifyWidgetServiceToJSON,
    CoolifyWidgetServiceToJSONTyped,
} from './CoolifyWidgetService';

/**
 * 
 * @export
 * @interface CoolifyWidgetData
 */
export interface CoolifyWidgetData {
    /**
     * 
     * @type {Array<CoolifyWidgetApplication>}
     * @memberof CoolifyWidgetData
     */
    applications?: Array<CoolifyWidgetApplication>;
    /**
     * 
     * @type {Array<CoolifyWidgetService>}
     * @memberof CoolifyWidgetData
     */
    services?: Array<CoolifyWidgetService>;
}

/**
 * Check if a given object implements the CoolifyWidgetData interface.
 */
export function instanceOfCoolifyWidgetData(value: object): value is CoolifyWidgetData {
    return true;
}

export function CoolifyWidgetDataFromJSON(json: any): CoolifyWidgetData {
    return CoolifyWidgetDataFromJSONTyped(json, false);
}

export function CoolifyWidgetDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoolifyWidgetData {
    if (json == null) {
        return json;
    }
    return {
        
        'applications': json['applications'] == null ? undefined : ((json['applications'] as Array<any>).map(CoolifyWidgetApplicationFromJSON)),
        'services': json['services'] == null ? undefined : ((json['services'] as Array<any>).map(CoolifyWidgetServiceFromJSON)),
    };
}

export function CoolifyWidgetDataToJSON(json: any): CoolifyWidgetData {
    return CoolifyWidgetDataToJSONTyped(json, false);
}

export function CoolifyWidgetDataToJSONTyped(value?: CoolifyWidgetData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'applications': value['applications'] == null ? undefined : ((value['applications'] as Array<any>).map(CoolifyWidgetApplicationToJSON)),
        'services': value['services'] == null ? undefined : ((value['services'] as Array<any>).map(CoolifyWidgetServiceToJSON)),
    };
}

