/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoolifyMemoryMetric
 */
export interface CoolifyMemoryMetric {
    /**
     * 
     * @type {number}
     * @memberof CoolifyMemoryMetric
     */
    available?: number;
    /**
     * 
     * @type {number}
     * @memberof CoolifyMemoryMetric
     */
    free?: number;
    /**
     * 
     * @type {string}
     * @memberof CoolifyMemoryMetric
     */
    time?: string;
    /**
     * 
     * @type {number}
     * @memberof CoolifyMemoryMetric
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof CoolifyMemoryMetric
     */
    used?: number;
    /**
     * 
     * @type {number}
     * @memberof CoolifyMemoryMetric
     */
    usedPercent?: number;
}

/**
 * Check if a given object implements the CoolifyMemoryMetric interface.
 */
export function instanceOfCoolifyMemoryMetric(value: object): value is CoolifyMemoryMetric {
    return true;
}

export function CoolifyMemoryMetricFromJSON(json: any): CoolifyMemoryMetric {
    return CoolifyMemoryMetricFromJSONTyped(json, false);
}

export function CoolifyMemoryMetricFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoolifyMemoryMetric {
    if (json == null) {
        return json;
    }
    return {
        
        'available': json['available'] == null ? undefined : json['available'],
        'free': json['free'] == null ? undefined : json['free'],
        'time': json['time'] == null ? undefined : json['time'],
        'total': json['total'] == null ? undefined : json['total'],
        'used': json['used'] == null ? undefined : json['used'],
        'usedPercent': json['used_percent'] == null ? undefined : json['used_percent'],
    };
}

export function CoolifyMemoryMetricToJSON(json: any): CoolifyMemoryMetric {
    return CoolifyMemoryMetricToJSONTyped(json, false);
}

export function CoolifyMemoryMetricToJSONTyped(value?: CoolifyMemoryMetric | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'available': value['available'],
        'free': value['free'],
        'time': value['time'],
        'total': value['total'],
        'used': value['used'],
        'used_percent': value['usedPercent'],
    };
}

