/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoolifyWidgetApplication } from './CoolifyWidgetApplication';
import {
    CoolifyWidgetApplicationFromJSON,
    CoolifyWidgetApplicationFromJSONTyped,
    CoolifyWidgetApplicationToJSON,
    CoolifyWidgetApplicationToJSONTyped,
} from './CoolifyWidgetApplication';

/**
 * 
 * @export
 * @interface CoolifyWidgetApplicationResponse
 */
export interface CoolifyWidgetApplicationResponse {
    /**
     * 
     * @type {Array<CoolifyWidgetApplication>}
     * @memberof CoolifyWidgetApplicationResponse
     */
    data?: Array<CoolifyWidgetApplication>;
    /**
     * 
     * @type {string}
     * @memberof CoolifyWidgetApplicationResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CoolifyWidgetApplicationResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the CoolifyWidgetApplicationResponse interface.
 */
export function instanceOfCoolifyWidgetApplicationResponse(value: object): value is CoolifyWidgetApplicationResponse {
    return true;
}

export function CoolifyWidgetApplicationResponseFromJSON(json: any): CoolifyWidgetApplicationResponse {
    return CoolifyWidgetApplicationResponseFromJSONTyped(json, false);
}

export function CoolifyWidgetApplicationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoolifyWidgetApplicationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CoolifyWidgetApplicationFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function CoolifyWidgetApplicationResponseToJSON(json: any): CoolifyWidgetApplicationResponse {
    return CoolifyWidgetApplicationResponseToJSONTyped(json, false);
}

export function CoolifyWidgetApplicationResponseToJSONTyped(value?: CoolifyWidgetApplicationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CoolifyWidgetApplicationToJSON)),
        'message': value['message'],
        'success': value['success'],
    };
}

