/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateApiKeyRequest
 */
export interface CreateApiKeyRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateApiKeyRequest
     */
    expiration?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateApiKeyRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateApiKeyRequest
     */
    notBefore?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateApiKeyRequest
     */
    readAccess?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateApiKeyRequest
     */
    writeAccess?: boolean;
}

/**
 * Check if a given object implements the CreateApiKeyRequest interface.
 */
export function instanceOfCreateApiKeyRequest(value: object): value is CreateApiKeyRequest {
    return true;
}

export function CreateApiKeyRequestFromJSON(json: any): CreateApiKeyRequest {
    return CreateApiKeyRequestFromJSONTyped(json, false);
}

export function CreateApiKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApiKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'expiration': json['expiration'] == null ? undefined : json['expiration'],
        'name': json['name'] == null ? undefined : json['name'],
        'notBefore': json['not_before'] == null ? undefined : json['not_before'],
        'readAccess': json['read_access'] == null ? undefined : json['read_access'],
        'writeAccess': json['write_access'] == null ? undefined : json['write_access'],
    };
}

export function CreateApiKeyRequestToJSON(json: any): CreateApiKeyRequest {
    return CreateApiKeyRequestToJSONTyped(json, false);
}

export function CreateApiKeyRequestToJSONTyped(value?: CreateApiKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expiration': value['expiration'],
        'name': value['name'],
        'not_before': value['notBefore'],
        'read_access': value['readAccess'],
        'write_access': value['writeAccess'],
    };
}

