/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateHouseholdRequest
 */
export interface CreateHouseholdRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateHouseholdRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the CreateHouseholdRequest interface.
 */
export function instanceOfCreateHouseholdRequest(value: object): value is CreateHouseholdRequest {
    return true;
}

export function CreateHouseholdRequestFromJSON(json: any): CreateHouseholdRequest {
    return CreateHouseholdRequestFromJSONTyped(json, false);
}

export function CreateHouseholdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateHouseholdRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CreateHouseholdRequestToJSON(json: any): CreateHouseholdRequest {
    return CreateHouseholdRequestToJSONTyped(json, false);
}

export function CreateHouseholdRequestToJSONTyped(value?: CreateHouseholdRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

