/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GithubPRsWidgetData } from './GithubPRsWidgetData';
import {
    GithubPRsWidgetDataFromJSON,
    GithubPRsWidgetDataFromJSONTyped,
    GithubPRsWidgetDataToJSON,
    GithubPRsWidgetDataToJSONTyped,
} from './GithubPRsWidgetData';

/**
 * 
 * @export
 * @interface GithubPRsWidgetResponse
 */
export interface GithubPRsWidgetResponse {
    /**
     * 
     * @type {GithubPRsWidgetData}
     * @memberof GithubPRsWidgetResponse
     */
    data?: GithubPRsWidgetData;
    /**
     * 
     * @type {string}
     * @memberof GithubPRsWidgetResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GithubPRsWidgetResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the GithubPRsWidgetResponse interface.
 */
export function instanceOfGithubPRsWidgetResponse(value: object): value is GithubPRsWidgetResponse {
    return true;
}

export function GithubPRsWidgetResponseFromJSON(json: any): GithubPRsWidgetResponse {
    return GithubPRsWidgetResponseFromJSONTyped(json, false);
}

export function GithubPRsWidgetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubPRsWidgetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : GithubPRsWidgetDataFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function GithubPRsWidgetResponseToJSON(json: any): GithubPRsWidgetResponse {
    return GithubPRsWidgetResponseToJSONTyped(json, false);
}

export function GithubPRsWidgetResponseToJSONTyped(value?: GithubPRsWidgetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GithubPRsWidgetDataToJSON(value['data']),
        'message': value['message'],
        'success': value['success'],
    };
}

