/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesGithubWidgetData } from './ResponsesGithubWidgetData';
import {
    ResponsesGithubWidgetDataFromJSON,
    ResponsesGithubWidgetDataFromJSONTyped,
    ResponsesGithubWidgetDataToJSON,
    ResponsesGithubWidgetDataToJSONTyped,
} from './ResponsesGithubWidgetData';

/**
 * 
 * @export
 * @interface GithubResponse
 */
export interface GithubResponse {
    /**
     * 
     * @type {ResponsesGithubWidgetData}
     * @memberof GithubResponse
     */
    data?: ResponsesGithubWidgetData;
    /**
     * 
     * @type {string}
     * @memberof GithubResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GithubResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the GithubResponse interface.
 */
export function instanceOfGithubResponse(value: object): value is GithubResponse {
    return true;
}

export function GithubResponseFromJSON(json: any): GithubResponse {
    return GithubResponseFromJSONTyped(json, false);
}

export function GithubResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ResponsesGithubWidgetDataFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function GithubResponseToJSON(json: any): GithubResponse {
    return GithubResponseToJSONTyped(json, false);
}

export function GithubResponseToJSONTyped(value?: GithubResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ResponsesGithubWidgetDataToJSON(value['data']),
        'message': value['message'],
        'success': value['success'],
    };
}

