/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesGithubWidgetCommitsData } from './ResponsesGithubWidgetCommitsData';
import {
    ResponsesGithubWidgetCommitsDataFromJSON,
    ResponsesGithubWidgetCommitsDataFromJSONTyped,
    ResponsesGithubWidgetCommitsDataToJSON,
    ResponsesGithubWidgetCommitsDataToJSONTyped,
} from './ResponsesGithubWidgetCommitsData';

/**
 * 
 * @export
 * @interface GithubCommitsResponse
 */
export interface GithubCommitsResponse {
    /**
     * 
     * @type {ResponsesGithubWidgetCommitsData}
     * @memberof GithubCommitsResponse
     */
    data?: ResponsesGithubWidgetCommitsData;
    /**
     * 
     * @type {string}
     * @memberof GithubCommitsResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GithubCommitsResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the GithubCommitsResponse interface.
 */
export function instanceOfGithubCommitsResponse(value: object): value is GithubCommitsResponse {
    return true;
}

export function GithubCommitsResponseFromJSON(json: any): GithubCommitsResponse {
    return GithubCommitsResponseFromJSONTyped(json, false);
}

export function GithubCommitsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubCommitsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ResponsesGithubWidgetCommitsDataFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function GithubCommitsResponseToJSON(json: any): GithubCommitsResponse {
    return GithubCommitsResponseToJSONTyped(json, false);
}

export function GithubCommitsResponseToJSONTyped(value?: GithubCommitsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ResponsesGithubWidgetCommitsDataToJSON(value['data']),
        'message': value['message'],
        'success': value['success'],
    };
}

