/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesGithubWidgetProfileData } from './ResponsesGithubWidgetProfileData';
import {
	ResponsesGithubWidgetProfileDataFromJSON,
	ResponsesGithubWidgetProfileDataFromJSONTyped,
	ResponsesGithubWidgetProfileDataToJSON,
	ResponsesGithubWidgetProfileDataToJSONTyped,
} from './ResponsesGithubWidgetProfileData';

/**
 *
 * @export
 * @interface GithubProfileResponse
 */
export interface GithubProfileResponse {
	/**
	 *
	 * @type {ResponsesGithubWidgetProfileData}
	 * @memberof GithubProfileResponse
	 */
	data?: ResponsesGithubWidgetProfileData;
	/**
	 *
	 * @type {string}
	 * @memberof GithubProfileResponse
	 */
	message?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof GithubProfileResponse
	 */
	success?: boolean;
}

/**
 * Check if a given object implements the GithubProfileResponse interface.
 */
export function instanceOfGithubProfileResponse(
	value: object,
): value is GithubProfileResponse {
	return true;
}

export function GithubProfileResponseFromJSON(
	json: any,
): GithubProfileResponse {
	return GithubProfileResponseFromJSONTyped(json, false);
}

export function GithubProfileResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): GithubProfileResponse {
	if (json == null) {
		return json;
	}
	return {
		data:
			json['data'] == null
				? undefined
				: ResponsesGithubWidgetProfileDataFromJSON(json['data']),
		message: json['message'] == null ? undefined : json['message'],
		success: json['success'] == null ? undefined : json['success'],
	};
}

export function GithubProfileResponseToJSON(json: any): GithubProfileResponse {
	return GithubProfileResponseToJSONTyped(json, false);
}

export function GithubProfileResponseToJSONTyped(
	value?: GithubProfileResponse | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		data: ResponsesGithubWidgetProfileDataToJSON(value['data']),
		message: value['message'],
		success: value['success'],
	};
}
