/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepositoryHousehold } from './RepositoryHousehold';
import {
    RepositoryHouseholdFromJSON,
    RepositoryHouseholdFromJSONTyped,
    RepositoryHouseholdToJSON,
    RepositoryHouseholdToJSONTyped,
} from './RepositoryHousehold';

/**
 * 
 * @export
 * @interface HouseholdResponse
 */
export interface HouseholdResponse {
    /**
     * 
     * @type {RepositoryHousehold}
     * @memberof HouseholdResponse
     */
    data?: RepositoryHousehold;
    /**
     * 
     * @type {string}
     * @memberof HouseholdResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof HouseholdResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the HouseholdResponse interface.
 */
export function instanceOfHouseholdResponse(value: object): value is HouseholdResponse {
    return true;
}

export function HouseholdResponseFromJSON(json: any): HouseholdResponse {
    return HouseholdResponseFromJSONTyped(json, false);
}

export function HouseholdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HouseholdResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : RepositoryHouseholdFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function HouseholdResponseToJSON(json: any): HouseholdResponse {
    return HouseholdResponseToJSONTyped(json, false);
}

export function HouseholdResponseToJSONTyped(value?: HouseholdResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': RepositoryHouseholdToJSON(value['data']),
        'message': value['message'],
        'success': value['success'],
    };
}

