/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepositoryGetInvitesByUserIDRow } from './RepositoryGetInvitesByUserIDRow';
import {
    RepositoryGetInvitesByUserIDRowFromJSON,
    RepositoryGetInvitesByUserIDRowFromJSONTyped,
    RepositoryGetInvitesByUserIDRowToJSON,
    RepositoryGetInvitesByUserIDRowToJSONTyped,
} from './RepositoryGetInvitesByUserIDRow';

/**
 * 
 * @export
 * @interface InvitesResponse
 */
export interface InvitesResponse {
    /**
     * 
     * @type {Array<RepositoryGetInvitesByUserIDRow>}
     * @memberof InvitesResponse
     */
    data?: Array<RepositoryGetInvitesByUserIDRow>;
    /**
     * 
     * @type {string}
     * @memberof InvitesResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InvitesResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the InvitesResponse interface.
 */
export function instanceOfInvitesResponse(value: object): value is InvitesResponse {
    return true;
}

export function InvitesResponseFromJSON(json: any): InvitesResponse {
    return InvitesResponseFromJSONTyped(json, false);
}

export function InvitesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(RepositoryGetInvitesByUserIDRowFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function InvitesResponseToJSON(json: any): InvitesResponse {
    return InvitesResponseToJSONTyped(json, false);
}

export function InvitesResponseToJSONTyped(value?: InvitesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(RepositoryGetInvitesByUserIDRowToJSON)),
        'message': value['message'],
        'success': value['success'],
    };
}

