/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesUserData } from './ResponsesUserData';
import {
	ResponsesUserDataFromJSON,
	ResponsesUserDataFromJSONTyped,
	ResponsesUserDataToJSON,
	ResponsesUserDataToJSONTyped,
} from './ResponsesUserData';

/**
 *
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
	/**
	 *
	 * @type {ResponsesUserData}
	 * @memberof LoginResponse
	 */
	data?: ResponsesUserData;
	/**
	 *
	 * @type {string}
	 * @memberof LoginResponse
	 */
	jwt?: string;
	/**
	 *
	 * @type {string}
	 * @memberof LoginResponse
	 */
	message?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof LoginResponse
	 */
	success?: boolean;
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): value is LoginResponse {
	return true;
}

export function LoginResponseFromJSON(json: any): LoginResponse {
	return LoginResponseFromJSONTyped(json, false);
}

export function LoginResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): LoginResponse {
	if (json == null) {
		return json;
	}
	return {
		data:
			json['data'] == null
				? undefined
				: ResponsesUserDataFromJSON(json['data']),
		jwt: json['jwt'] == null ? undefined : json['jwt'],
		message: json['message'] == null ? undefined : json['message'],
		success: json['success'] == null ? undefined : json['success'],
	};
}

export function LoginResponseToJSON(json: any): LoginResponse {
	return LoginResponseToJSONTyped(json, false);
}

export function LoginResponseToJSONTyped(
	value?: LoginResponse | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		data: ResponsesUserDataToJSON(value['data']),
		jwt: value['jwt'],
		message: value['message'],
		success: value['success'],
	};
}
