/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewUserRequest
 */
export interface NewUserRequest {
    /**
     * 
     * @type {string}
     * @memberof NewUserRequest
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NewUserRequest
     */
    isAdmin?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NewUserRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof NewUserRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the NewUserRequest interface.
 */
export function instanceOfNewUserRequest(value: object): value is NewUserRequest {
    return true;
}

export function NewUserRequestFromJSON(json: any): NewUserRequest {
    return NewUserRequestFromJSONTyped(json, false);
}

export function NewUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'isAdmin': json['isAdmin'] == null ? undefined : json['isAdmin'],
        'password': json['password'] == null ? undefined : json['password'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function NewUserRequestToJSON(json: any): NewUserRequest {
    return NewUserRequestToJSONTyped(json, false);
}

export function NewUserRequestToJSONTyped(value?: NewUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'isAdmin': value['isAdmin'],
        'password': value['password'],
        'username': value['username'],
    };
}

