/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlexMediaItemData } from './PlexMediaItemData';
import {
    PlexMediaItemDataFromJSON,
    PlexMediaItemDataFromJSONTyped,
    PlexMediaItemDataToJSON,
    PlexMediaItemDataToJSONTyped,
} from './PlexMediaItemData';

/**
 * 
 * @export
 * @interface PlexRecentlyAddedResponse
 */
export interface PlexRecentlyAddedResponse {
    /**
     * 
     * @type {Array<PlexMediaItemData>}
     * @memberof PlexRecentlyAddedResponse
     */
    data?: Array<PlexMediaItemData>;
    /**
     * 
     * @type {string}
     * @memberof PlexRecentlyAddedResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PlexRecentlyAddedResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the PlexRecentlyAddedResponse interface.
 */
export function instanceOfPlexRecentlyAddedResponse(value: object): value is PlexRecentlyAddedResponse {
    return true;
}

export function PlexRecentlyAddedResponseFromJSON(json: any): PlexRecentlyAddedResponse {
    return PlexRecentlyAddedResponseFromJSONTyped(json, false);
}

export function PlexRecentlyAddedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlexRecentlyAddedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PlexMediaItemDataFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function PlexRecentlyAddedResponseToJSON(json: any): PlexRecentlyAddedResponse {
    return PlexRecentlyAddedResponseToJSONTyped(json, false);
}

export function PlexRecentlyAddedResponseToJSONTyped(value?: PlexRecentlyAddedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PlexMediaItemDataToJSON)),
        'message': value['message'],
        'success': value['success'],
    };
}

