/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RepositoryUpdateTaskContentParams
 */
export interface RepositoryUpdateTaskContentParams {
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryUpdateTaskContentParams
	 */
	description?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryUpdateTaskContentParams
	 */
	id?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryUpdateTaskContentParams
	 */
	name?: string;
}

/**
 * Check if a given object implements the RepositoryUpdateTaskContentParams interface.
 */
export function instanceOfRepositoryUpdateTaskContentParams(
	value: object,
): value is RepositoryUpdateTaskContentParams {
	return true;
}

export function RepositoryUpdateTaskContentParamsFromJSON(
	json: any,
): RepositoryUpdateTaskContentParams {
	return RepositoryUpdateTaskContentParamsFromJSONTyped(json, false);
}

export function RepositoryUpdateTaskContentParamsFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): RepositoryUpdateTaskContentParams {
	if (json == null) {
		return json;
	}
	return {
		description: json['description'] == null ? undefined : json['description'],
		id: json['id'] == null ? undefined : json['id'],
		name: json['name'] == null ? undefined : json['name'],
	};
}

export function RepositoryUpdateTaskContentParamsToJSON(
	json: any,
): RepositoryUpdateTaskContentParams {
	return RepositoryUpdateTaskContentParamsToJSONTyped(json, false);
}

export function RepositoryUpdateTaskContentParamsToJSONTyped(
	value?: RepositoryUpdateTaskContentParams | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		description: value['description'],
		id: value['id'],
		name: value['name'],
	};
}
