/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RepositoryNote
 */
export interface RepositoryNote {
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryNote
	 */
	content?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryNote
	 */
	createdDatetime?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryNote
	 */
	description?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryNote
	 */
	folderId?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryNote
	 */
	id?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryNote
	 */
	name?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryNote
	 */
	updatedDatetime?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryNote
	 */
	userId?: string;
}

/**
 * Check if a given object implements the RepositoryNote interface.
 */
export function instanceOfRepositoryNote(
	value: object,
): value is RepositoryNote {
	return true;
}

export function RepositoryNoteFromJSON(json: any): RepositoryNote {
	return RepositoryNoteFromJSONTyped(json, false);
}

export function RepositoryNoteFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): RepositoryNote {
	if (json == null) {
		return json;
	}
	return {
		content: json['content'] == null ? undefined : json['content'],
		createdDatetime:
			json['created_datetime'] == null ? undefined : json['created_datetime'],
		description: json['description'] == null ? undefined : json['description'],
		folderId: json['folder_id'] == null ? undefined : json['folder_id'],
		id: json['id'] == null ? undefined : json['id'],
		name: json['name'] == null ? undefined : json['name'],
		updatedDatetime:
			json['updated_datetime'] == null ? undefined : json['updated_datetime'],
		userId: json['user_id'] == null ? undefined : json['user_id'],
	};
}

export function RepositoryNoteToJSON(json: any): RepositoryNote {
	return RepositoryNoteToJSONTyped(json, false);
}

export function RepositoryNoteToJSONTyped(
	value?: RepositoryNote | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		content: value['content'],
		created_datetime: value['createdDatetime'],
		description: value['description'],
		folder_id: value['folderId'],
		id: value['id'],
		name: value['name'],
		updated_datetime: value['updatedDatetime'],
		user_id: value['userId'],
	};
}
