/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RepositoryTaskType
 */
export interface RepositoryTaskType {
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryTaskType
	 */
	createdAt?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryTaskType
	 */
	id?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryTaskType
	 */
	name?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof RepositoryTaskType
	 */
	showInAvailable?: boolean;
	/**
	 *
	 * @type {boolean}
	 * @memberof RepositoryTaskType
	 */
	showInCancelled?: boolean;
	/**
	 *
	 * @type {boolean}
	 * @memberof RepositoryTaskType
	 */
	showInCompleted?: boolean;
	/**
	 *
	 * @type {boolean}
	 * @memberof RepositoryTaskType
	 */
	showInScheduled?: boolean;
}

/**
 * Check if a given object implements the RepositoryTaskType interface.
 */
export function instanceOfRepositoryTaskType(
	value: object,
): value is RepositoryTaskType {
	return true;
}

export function RepositoryTaskTypeFromJSON(json: any): RepositoryTaskType {
	return RepositoryTaskTypeFromJSONTyped(json, false);
}

export function RepositoryTaskTypeFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): RepositoryTaskType {
	if (json == null) {
		return json;
	}
	return {
		createdAt: json['created_at'] == null ? undefined : json['created_at'],
		id: json['id'] == null ? undefined : json['id'],
		name: json['name'] == null ? undefined : json['name'],
		showInAvailable:
			json['show_in_available'] == null ? undefined : json['show_in_available'],
		showInCancelled:
			json['show_in_cancelled'] == null ? undefined : json['show_in_cancelled'],
		showInCompleted:
			json['show_in_completed'] == null ? undefined : json['show_in_completed'],
		showInScheduled:
			json['show_in_scheduled'] == null ? undefined : json['show_in_scheduled'],
	};
}

export function RepositoryTaskTypeToJSON(json: any): RepositoryTaskType {
	return RepositoryTaskTypeToJSONTyped(json, false);
}

export function RepositoryTaskTypeToJSONTyped(
	value?: RepositoryTaskType | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		created_at: value['createdAt'],
		id: value['id'],
		name: value['name'],
		show_in_available: value['showInAvailable'],
		show_in_cancelled: value['showInCancelled'],
		show_in_completed: value['showInCompleted'],
		show_in_scheduled: value['showInScheduled'],
	};
}
