/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RepositoryCreateFolderParams
 */
export interface RepositoryCreateFolderParams {
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryCreateFolderParams
	 */
	description?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryCreateFolderParams
	 */
	name?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryCreateFolderParams
	 */
	parentId?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryCreateFolderParams
	 */
	userId?: string;
}

/**
 * Check if a given object implements the RepositoryCreateFolderParams interface.
 */
export function instanceOfRepositoryCreateFolderParams(
	value: object,
): value is RepositoryCreateFolderParams {
	return true;
}

export function RepositoryCreateFolderParamsFromJSON(
	json: any,
): RepositoryCreateFolderParams {
	return RepositoryCreateFolderParamsFromJSONTyped(json, false);
}

export function RepositoryCreateFolderParamsFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): RepositoryCreateFolderParams {
	if (json == null) {
		return json;
	}
	return {
		description: json['description'] == null ? undefined : json['description'],
		name: json['name'] == null ? undefined : json['name'],
		parentId: json['parent_id'] == null ? undefined : json['parent_id'],
		userId: json['user_id'] == null ? undefined : json['user_id'],
	};
}

export function RepositoryCreateFolderParamsToJSON(
	json: any,
): RepositoryCreateFolderParams {
	return RepositoryCreateFolderParamsToJSONTyped(json, false);
}

export function RepositoryCreateFolderParamsToJSONTyped(
	value?: RepositoryCreateFolderParams | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		description: value['description'],
		name: value['name'],
		parent_id: value['parentId'],
		user_id: value['userId'],
	};
}
