/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepositoryGetInvitesByUserIDRow
 */
export interface RepositoryGetInvitesByUserIDRow {
    /**
     * 
     * @type {string}
     * @memberof RepositoryGetInvitesByUserIDRow
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof RepositoryGetInvitesByUserIDRow
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof RepositoryGetInvitesByUserIDRow
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof RepositoryGetInvitesByUserIDRow
     */
    expiresAt?: string;
    /**
     * 
     * @type {string}
     * @memberof RepositoryGetInvitesByUserIDRow
     */
    householdId?: string;
    /**
     * 
     * @type {string}
     * @memberof RepositoryGetInvitesByUserIDRow
     */
    householdName?: string;
    /**
     * 
     * @type {string}
     * @memberof RepositoryGetInvitesByUserIDRow
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RepositoryGetInvitesByUserIDRow
     */
    invitedUserId?: string;
}

/**
 * Check if a given object implements the RepositoryGetInvitesByUserIDRow interface.
 */
export function instanceOfRepositoryGetInvitesByUserIDRow(value: object): value is RepositoryGetInvitesByUserIDRow {
    return true;
}

export function RepositoryGetInvitesByUserIDRowFromJSON(json: any): RepositoryGetInvitesByUserIDRow {
    return RepositoryGetInvitesByUserIDRowFromJSONTyped(json, false);
}

export function RepositoryGetInvitesByUserIDRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepositoryGetInvitesByUserIDRow {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'householdId': json['household_id'] == null ? undefined : json['household_id'],
        'householdName': json['household_name'] == null ? undefined : json['household_name'],
        'id': json['id'] == null ? undefined : json['id'],
        'invitedUserId': json['invited_user_id'] == null ? undefined : json['invited_user_id'],
    };
}

export function RepositoryGetInvitesByUserIDRowToJSON(json: any): RepositoryGetInvitesByUserIDRow {
    return RepositoryGetInvitesByUserIDRowToJSONTyped(json, false);
}

export function RepositoryGetInvitesByUserIDRowToJSONTyped(value?: RepositoryGetInvitesByUserIDRow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'created_at': value['createdAt'],
        'created_by': value['createdBy'],
        'expires_at': value['expiresAt'],
        'household_id': value['householdId'],
        'household_name': value['householdName'],
        'id': value['id'],
        'invited_user_id': value['invitedUserId'],
    };
}

