/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RepositoryCreateBookmarkParams
 */
export interface RepositoryCreateBookmarkParams {
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryCreateBookmarkParams
	 */
	folderId?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryCreateBookmarkParams
	 */
	link?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryCreateBookmarkParams
	 */
	name?: string;
	/**
	 *
	 * @type {string}
	 * @memberof RepositoryCreateBookmarkParams
	 */
	userId?: string;
}

/**
 * Check if a given object implements the RepositoryCreateBookmarkParams interface.
 */
export function instanceOfRepositoryCreateBookmarkParams(
	value: object,
): value is RepositoryCreateBookmarkParams {
	return true;
}

export function RepositoryCreateBookmarkParamsFromJSON(
	json: any,
): RepositoryCreateBookmarkParams {
	return RepositoryCreateBookmarkParamsFromJSONTyped(json, false);
}

export function RepositoryCreateBookmarkParamsFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): RepositoryCreateBookmarkParams {
	if (json == null) {
		return json;
	}
	return {
		folderId: json['folder_id'] == null ? undefined : json['folder_id'],
		link: json['link'] == null ? undefined : json['link'],
		name: json['name'] == null ? undefined : json['name'],
		userId: json['user_id'] == null ? undefined : json['user_id'],
	};
}

export function RepositoryCreateBookmarkParamsToJSON(
	json: any,
): RepositoryCreateBookmarkParams {
	return RepositoryCreateBookmarkParamsToJSONTyped(json, false);
}

export function RepositoryCreateBookmarkParamsToJSONTyped(
	value?: RepositoryCreateBookmarkParams | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		folder_id: value['folderId'],
		link: value['link'],
		name: value['name'],
		user_id: value['userId'],
	};
}
