/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestsMoveFolderRequest
 */
export interface RequestsMoveFolderRequest {
    /**
     * 
     * @type {string}
     * @memberof RequestsMoveFolderRequest
     */
    folderId?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsMoveFolderRequest
     */
    newParentId?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestsMoveFolderRequest
     */
    userId?: string;
}

/**
 * Check if a given object implements the RequestsMoveFolderRequest interface.
 */
export function instanceOfRequestsMoveFolderRequest(value: object): value is RequestsMoveFolderRequest {
    return true;
}

export function RequestsMoveFolderRequestFromJSON(json: any): RequestsMoveFolderRequest {
    return RequestsMoveFolderRequestFromJSONTyped(json, false);
}

export function RequestsMoveFolderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestsMoveFolderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'folderId': json['folderId'] == null ? undefined : json['folderId'],
        'newParentId': json['newParentId'] == null ? undefined : json['newParentId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function RequestsMoveFolderRequestToJSON(json: any): RequestsMoveFolderRequest {
    return RequestsMoveFolderRequestToJSONTyped(json, false);
}

export function RequestsMoveFolderRequestToJSONTyped(value?: RequestsMoveFolderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'folderId': value['folderId'],
        'newParentId': value['newParentId'],
        'userId': value['userId'],
    };
}

