/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesFolderData } from './ResponsesFolderData';
import {
    ResponsesFolderDataFromJSON,
    ResponsesFolderDataFromJSONTyped,
    ResponsesFolderDataToJSON,
    ResponsesFolderDataToJSONTyped,
} from './ResponsesFolderData';

/**
 * 
 * @export
 * @interface ResponsesFoldersResponse
 */
export interface ResponsesFoldersResponse {
    /**
     * 
     * @type {Array<ResponsesFolderData>}
     * @memberof ResponsesFoldersResponse
     */
    data?: Array<ResponsesFolderData>;
    /**
     * 
     * @type {string}
     * @memberof ResponsesFoldersResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsesFoldersResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the ResponsesFoldersResponse interface.
 */
export function instanceOfResponsesFoldersResponse(value: object): value is ResponsesFoldersResponse {
    return true;
}

export function ResponsesFoldersResponseFromJSON(json: any): ResponsesFoldersResponse {
    return ResponsesFoldersResponseFromJSONTyped(json, false);
}

export function ResponsesFoldersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesFoldersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ResponsesFolderDataFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function ResponsesFoldersResponseToJSON(json: any): ResponsesFoldersResponse {
    return ResponsesFoldersResponseToJSONTyped(json, false);
}

export function ResponsesFoldersResponseToJSONTyped(value?: ResponsesFoldersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ResponsesFolderDataToJSON)),
        'message': value['message'],
        'success': value['success'],
    };
}

