/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesGithubWidgetCommitsData } from './ResponsesGithubWidgetCommitsData';
import {
	ResponsesGithubWidgetCommitsDataFromJSON,
	ResponsesGithubWidgetCommitsDataFromJSONTyped,
	ResponsesGithubWidgetCommitsDataToJSON,
	ResponsesGithubWidgetCommitsDataToJSONTyped,
} from './ResponsesGithubWidgetCommitsData';
import type { ResponsesGithubWidgetProfileData } from './ResponsesGithubWidgetProfileData';
import {
	ResponsesGithubWidgetProfileDataFromJSON,
	ResponsesGithubWidgetProfileDataFromJSONTyped,
	ResponsesGithubWidgetProfileDataToJSON,
	ResponsesGithubWidgetProfileDataToJSONTyped,
} from './ResponsesGithubWidgetProfileData';

/**
 *
 * @export
 * @interface ResponsesGithubWidgetData
 */
export interface ResponsesGithubWidgetData {
	/**
	 *
	 * @type {ResponsesGithubWidgetCommitsData}
	 * @memberof ResponsesGithubWidgetData
	 */
	commits?: ResponsesGithubWidgetCommitsData;
	/**
	 *
	 * @type {ResponsesGithubWidgetProfileData}
	 * @memberof ResponsesGithubWidgetData
	 */
	profile?: ResponsesGithubWidgetProfileData;
}

/**
 * Check if a given object implements the ResponsesGithubWidgetData interface.
 */
export function instanceOfResponsesGithubWidgetData(
	value: object,
): value is ResponsesGithubWidgetData {
	return true;
}

export function ResponsesGithubWidgetDataFromJSON(
	json: any,
): ResponsesGithubWidgetData {
	return ResponsesGithubWidgetDataFromJSONTyped(json, false);
}

export function ResponsesGithubWidgetDataFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ResponsesGithubWidgetData {
	if (json == null) {
		return json;
	}
	return {
		commits:
			json['commits'] == null
				? undefined
				: ResponsesGithubWidgetCommitsDataFromJSON(json['commits']),
		profile:
			json['profile'] == null
				? undefined
				: ResponsesGithubWidgetProfileDataFromJSON(json['profile']),
	};
}

export function ResponsesGithubWidgetDataToJSON(
	json: any,
): ResponsesGithubWidgetData {
	return ResponsesGithubWidgetDataToJSONTyped(json, false);
}

export function ResponsesGithubWidgetDataToJSONTyped(
	value?: ResponsesGithubWidgetData | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		commits: ResponsesGithubWidgetCommitsDataToJSON(value['commits']),
		profile: ResponsesGithubWidgetProfileDataToJSON(value['profile']),
	};
}
