/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesWidgetData } from './ResponsesWidgetData';
import {
	ResponsesWidgetDataFromJSON,
	ResponsesWidgetDataFromJSONTyped,
	ResponsesWidgetDataToJSON,
	ResponsesWidgetDataToJSONTyped,
} from './ResponsesWidgetData';

/**
 *
 * @export
 * @interface ResponsesWidgetsResponse
 */
export interface ResponsesWidgetsResponse {
	/**
	 *
	 * @type {Array<ResponsesWidgetData>}
	 * @memberof ResponsesWidgetsResponse
	 */
	data?: Array<ResponsesWidgetData>;
	/**
	 *
	 * @type {string}
	 * @memberof ResponsesWidgetsResponse
	 */
	message?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof ResponsesWidgetsResponse
	 */
	success?: boolean;
}

/**
 * Check if a given object implements the ResponsesWidgetsResponse interface.
 */
export function instanceOfResponsesWidgetsResponse(
	value: object,
): value is ResponsesWidgetsResponse {
	return true;
}

export function ResponsesWidgetsResponseFromJSON(
	json: any,
): ResponsesWidgetsResponse {
	return ResponsesWidgetsResponseFromJSONTyped(json, false);
}

export function ResponsesWidgetsResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ResponsesWidgetsResponse {
	if (json == null) {
		return json;
	}
	return {
		data:
			json['data'] == null
				? undefined
				: (json['data'] as Array<any>).map(ResponsesWidgetDataFromJSON),
		message: json['message'] == null ? undefined : json['message'],
		success: json['success'] == null ? undefined : json['success'],
	};
}

export function ResponsesWidgetsResponseToJSON(
	json: any,
): ResponsesWidgetsResponse {
	return ResponsesWidgetsResponseToJSONTyped(json, false);
}

export function ResponsesWidgetsResponseToJSONTyped(
	value?: ResponsesWidgetsResponse | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		data:
			value['data'] == null
				? undefined
				: (value['data'] as Array<any>).map(ResponsesWidgetDataToJSON),
		message: value['message'],
		success: value['success'],
	};
}
