/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepositoryFolder } from './RepositoryFolder';
import {
    RepositoryFolderFromJSON,
    RepositoryFolderFromJSONTyped,
    RepositoryFolderToJSON,
    RepositoryFolderToJSONTyped,
} from './RepositoryFolder';
import type { RepositoryBookmark } from './RepositoryBookmark';
import {
    RepositoryBookmarkFromJSON,
    RepositoryBookmarkFromJSONTyped,
    RepositoryBookmarkToJSON,
    RepositoryBookmarkToJSONTyped,
} from './RepositoryBookmark';
import type { RepositoryNote } from './RepositoryNote';
import {
    RepositoryNoteFromJSON,
    RepositoryNoteFromJSONTyped,
    RepositoryNoteToJSON,
    RepositoryNoteToJSONTyped,
} from './RepositoryNote';

/**
 * 
 * @export
 * @interface ResponsesFolderData
 */
export interface ResponsesFolderData {
    /**
     * 
     * @type {Array<RepositoryBookmark>}
     * @memberof ResponsesFolderData
     */
    bookmarks?: Array<RepositoryBookmark>;
    /**
     * 
     * @type {Array<RepositoryFolder>}
     * @memberof ResponsesFolderData
     */
    children?: Array<RepositoryFolder>;
    /**
     * 
     * @type {string}
     * @memberof ResponsesFolderData
     */
    createdDatetime?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesFolderData
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesFolderData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesFolderData
     */
    name?: string;
    /**
     * 
     * @type {Array<RepositoryNote>}
     * @memberof ResponsesFolderData
     */
    notes?: Array<RepositoryNote>;
    /**
     * 
     * @type {string}
     * @memberof ResponsesFolderData
     */
    parentId?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesFolderData
     */
    updatedDatetime?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponsesFolderData
     */
    userId?: string;
}

/**
 * Check if a given object implements the ResponsesFolderData interface.
 */
export function instanceOfResponsesFolderData(value: object): value is ResponsesFolderData {
    return true;
}

export function ResponsesFolderDataFromJSON(json: any): ResponsesFolderData {
    return ResponsesFolderDataFromJSONTyped(json, false);
}

export function ResponsesFolderDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesFolderData {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmarks': json['bookmarks'] == null ? undefined : ((json['bookmarks'] as Array<any>).map(RepositoryBookmarkFromJSON)),
        'children': json['children'] == null ? undefined : ((json['children'] as Array<any>).map(RepositoryFolderFromJSON)),
        'createdDatetime': json['created_datetime'] == null ? undefined : json['created_datetime'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'notes': json['notes'] == null ? undefined : ((json['notes'] as Array<any>).map(RepositoryNoteFromJSON)),
        'parentId': json['parent_id'] == null ? undefined : json['parent_id'],
        'updatedDatetime': json['updated_datetime'] == null ? undefined : json['updated_datetime'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function ResponsesFolderDataToJSON(json: any): ResponsesFolderData {
    return ResponsesFolderDataToJSONTyped(json, false);
}

export function ResponsesFolderDataToJSONTyped(value?: ResponsesFolderData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmarks': value['bookmarks'] == null ? undefined : ((value['bookmarks'] as Array<any>).map(RepositoryBookmarkToJSON)),
        'children': value['children'] == null ? undefined : ((value['children'] as Array<any>).map(RepositoryFolderToJSON)),
        'created_datetime': value['createdDatetime'],
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'notes': value['notes'] == null ? undefined : ((value['notes'] as Array<any>).map(RepositoryNoteToJSON)),
        'parent_id': value['parentId'],
        'updated_datetime': value['updatedDatetime'],
        'user_id': value['userId'],
    };
}

