/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServicesTaskDTO } from './ServicesTaskDTO';
import {
    ServicesTaskDTOFromJSON,
    ServicesTaskDTOFromJSONTyped,
    ServicesTaskDTOToJSON,
    ServicesTaskDTOToJSONTyped,
} from './ServicesTaskDTO';

/**
 * 
 * @export
 * @interface ResponsesTaskResponse
 */
export interface ResponsesTaskResponse {
    /**
     * 
     * @type {ServicesTaskDTO}
     * @memberof ResponsesTaskResponse
     */
    data?: ServicesTaskDTO;
    /**
     * 
     * @type {string}
     * @memberof ResponsesTaskResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsesTaskResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the ResponsesTaskResponse interface.
 */
export function instanceOfResponsesTaskResponse(value: object): value is ResponsesTaskResponse {
    return true;
}

export function ResponsesTaskResponseFromJSON(json: any): ResponsesTaskResponse {
    return ResponsesTaskResponseFromJSONTyped(json, false);
}

export function ResponsesTaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesTaskResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ServicesTaskDTOFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function ResponsesTaskResponseToJSON(json: any): ResponsesTaskResponse {
    return ResponsesTaskResponseToJSONTyped(json, false);
}

export function ResponsesTaskResponseToJSONTyped(value?: ResponsesTaskResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ServicesTaskDTOToJSON(value['data']),
        'message': value['message'],
        'success': value['success'],
    };
}

