/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResponsesUserData
 */
export interface ResponsesUserData {
	/**
	 *
	 * @type {boolean}
	 * @memberof ResponsesUserData
	 */
	admin?: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof ResponsesUserData
	 */
	background?: string;
	/**
	 *
	 * @type {string}
	 * @memberof ResponsesUserData
	 */
	createdDatetime?: string;
	/**
	 *
	 * @type {string}
	 * @memberof ResponsesUserData
	 */
	email?: string;
	/**
	 *
	 * @type {string}
	 * @memberof ResponsesUserData
	 */
	id?: string;
	/**
	 *
	 * @type {string}
	 * @memberof ResponsesUserData
	 */
	profilePicUrl?: string;
	/**
	 *
	 * @type {string}
	 * @memberof ResponsesUserData
	 */
	updatedDatetime?: string;
	/**
	 *
	 * @type {string}
	 * @memberof ResponsesUserData
	 */
	username?: string;
}

/**
 * Check if a given object implements the ResponsesUserData interface.
 */
export function instanceOfResponsesUserData(
	value: object,
): value is ResponsesUserData {
	return true;
}

export function ResponsesUserDataFromJSON(json: any): ResponsesUserData {
	return ResponsesUserDataFromJSONTyped(json, false);
}

export function ResponsesUserDataFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ResponsesUserData {
	if (json == null) {
		return json;
	}
	return {
		admin: json['admin'] == null ? undefined : json['admin'],
		background: json['background'] == null ? undefined : json['background'],
		createdDatetime:
			json['created_datetime'] == null ? undefined : json['created_datetime'],
		email: json['email'] == null ? undefined : json['email'],
		id: json['id'] == null ? undefined : json['id'],
		profilePicUrl:
			json['profile_pic_url'] == null ? undefined : json['profile_pic_url'],
		updatedDatetime:
			json['updated_datetime'] == null ? undefined : json['updated_datetime'],
		username: json['username'] == null ? undefined : json['username'],
	};
}

export function ResponsesUserDataToJSON(json: any): ResponsesUserData {
	return ResponsesUserDataToJSONTyped(json, false);
}

export function ResponsesUserDataToJSONTyped(
	value?: ResponsesUserData | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		admin: value['admin'],
		background: value['background'],
		created_datetime: value['createdDatetime'],
		email: value['email'],
		id: value['id'],
		profile_pic_url: value['profilePicUrl'],
		updated_datetime: value['updatedDatetime'],
		username: value['username'],
	};
}
