/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SchemasWidgetProperty } from './SchemasWidgetProperty';
import {
	SchemasWidgetPropertyFromJSON,
	SchemasWidgetPropertyFromJSONTyped,
	SchemasWidgetPropertyToJSON,
	SchemasWidgetPropertyToJSONTyped,
} from './SchemasWidgetProperty';

/**
 *
 * @export
 * @interface SchemasWidgetProperties
 */
export interface SchemasWidgetProperties {
	/**
	 *
	 * @type {{ [key: string]: SchemasWidgetProperty; }}
	 * @memberof SchemasWidgetProperties
	 */
	properties?: { [key: string]: SchemasWidgetProperty };
}

/**
 * Check if a given object implements the SchemasWidgetProperties interface.
 */
export function instanceOfSchemasWidgetProperties(
	value: object,
): value is SchemasWidgetProperties {
	return true;
}

export function SchemasWidgetPropertiesFromJSON(
	json: any,
): SchemasWidgetProperties {
	return SchemasWidgetPropertiesFromJSONTyped(json, false);
}

export function SchemasWidgetPropertiesFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): SchemasWidgetProperties {
	if (json == null) {
		return json;
	}
	return {
		properties:
			json['properties'] == null
				? undefined
				: mapValues(json['properties'], SchemasWidgetPropertyFromJSON),
	};
}

export function SchemasWidgetPropertiesToJSON(
	json: any,
): SchemasWidgetProperties {
	return SchemasWidgetPropertiesToJSONTyped(json, false);
}

export function SchemasWidgetPropertiesToJSONTyped(
	value?: SchemasWidgetProperties | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		properties:
			value['properties'] == null
				? undefined
				: mapValues(value['properties'], SchemasWidgetPropertyToJSON),
	};
}
