/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchemasWidgetSize
 */
export interface SchemasWidgetSize {
    /**
     * 
     * @type {number}
     * @memberof SchemasWidgetSize
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof SchemasWidgetSize
     */
    width?: number;
}

/**
 * Check if a given object implements the SchemasWidgetSize interface.
 */
export function instanceOfSchemasWidgetSize(value: object): value is SchemasWidgetSize {
    return true;
}

export function SchemasWidgetSizeFromJSON(json: any): SchemasWidgetSize {
    return SchemasWidgetSizeFromJSONTyped(json, false);
}

export function SchemasWidgetSizeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemasWidgetSize {
    if (json == null) {
        return json;
    }
    return {
        
        'height': json['height'] == null ? undefined : json['height'],
        'width': json['width'] == null ? undefined : json['width'],
    };
}

export function SchemasWidgetSizeToJSON(json: any): SchemasWidgetSize {
    return SchemasWidgetSizeToJSONTyped(json, false);
}

export function SchemasWidgetSizeToJSONTyped(value?: SchemasWidgetSize | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'height': value['height'],
        'width': value['width'],
    };
}

