/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SchemasWidgetSize } from './SchemasWidgetSize';
import {
    SchemasWidgetSizeFromJSON,
    SchemasWidgetSizeFromJSONTyped,
    SchemasWidgetSizeToJSON,
    SchemasWidgetSizeToJSONTyped,
} from './SchemasWidgetSize';

/**
 * 
 * @export
 * @interface SchemasWidgetLayout
 */
export interface SchemasWidgetLayout {
    /**
     * 
     * @type {SchemasWidgetSize}
     * @memberof SchemasWidgetLayout
     */
    defaultSize?: SchemasWidgetSize;
    /**
     * 
     * @type {SchemasWidgetSize}
     * @memberof SchemasWidgetLayout
     */
    maxSize?: SchemasWidgetSize;
    /**
     * 
     * @type {SchemasWidgetSize}
     * @memberof SchemasWidgetLayout
     */
    minSize?: SchemasWidgetSize;
    /**
     * 
     * @type {boolean}
     * @memberof SchemasWidgetLayout
     */
    resizable?: boolean;
}

/**
 * Check if a given object implements the SchemasWidgetLayout interface.
 */
export function instanceOfSchemasWidgetLayout(value: object): value is SchemasWidgetLayout {
    return true;
}

export function SchemasWidgetLayoutFromJSON(json: any): SchemasWidgetLayout {
    return SchemasWidgetLayoutFromJSONTyped(json, false);
}

export function SchemasWidgetLayoutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemasWidgetLayout {
    if (json == null) {
        return json;
    }
    return {
        
        'defaultSize': json['defaultSize'] == null ? undefined : SchemasWidgetSizeFromJSON(json['defaultSize']),
        'maxSize': json['maxSize'] == null ? undefined : SchemasWidgetSizeFromJSON(json['maxSize']),
        'minSize': json['minSize'] == null ? undefined : SchemasWidgetSizeFromJSON(json['minSize']),
        'resizable': json['resizable'] == null ? undefined : json['resizable'],
    };
}

export function SchemasWidgetLayoutToJSON(json: any): SchemasWidgetLayout {
    return SchemasWidgetLayoutToJSONTyped(json, false);
}

export function SchemasWidgetLayoutToJSONTyped(value?: SchemasWidgetLayout | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'defaultSize': SchemasWidgetSizeToJSON(value['defaultSize']),
        'maxSize': SchemasWidgetSizeToJSON(value['maxSize']),
        'minSize': SchemasWidgetSizeToJSON(value['minSize']),
        'resizable': value['resizable'],
    };
}

