/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface StringResponse
 */
export interface StringResponse {
	/**
	 *
	 * @type {string}
	 * @memberof StringResponse
	 */
	data?: string;
	/**
	 *
	 * @type {string}
	 * @memberof StringResponse
	 */
	message?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof StringResponse
	 */
	success?: boolean;
}

/**
 * Check if a given object implements the StringResponse interface.
 */
export function instanceOfStringResponse(
	value: object,
): value is StringResponse {
	return true;
}

export function StringResponseFromJSON(json: any): StringResponse {
	return StringResponseFromJSONTyped(json, false);
}

export function StringResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): StringResponse {
	if (json == null) {
		return json;
	}
	return {
		data: json['data'] == null ? undefined : json['data'],
		message: json['message'] == null ? undefined : json['message'],
		success: json['success'] == null ? undefined : json['success'],
	};
}

export function StringResponseToJSON(json: any): StringResponse {
	return StringResponseToJSONTyped(json, false);
}

export function StringResponseToJSONTyped(
	value?: StringResponse | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		data: value['data'],
		message: value['message'],
		success: value['success'],
	};
}
