/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateBookmarkRequest
 */
export interface UpdateBookmarkRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateBookmarkRequest
     */
    bookmarkId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBookmarkRequest
     */
    link?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBookmarkRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBookmarkRequest
     */
    userId?: string;
}

/**
 * Check if a given object implements the UpdateBookmarkRequest interface.
 */
export function instanceOfUpdateBookmarkRequest(value: object): value is UpdateBookmarkRequest {
    return true;
}

export function UpdateBookmarkRequestFromJSON(json: any): UpdateBookmarkRequest {
    return UpdateBookmarkRequestFromJSONTyped(json, false);
}

export function UpdateBookmarkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBookmarkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmarkId': json['bookmarkId'] == null ? undefined : json['bookmarkId'],
        'link': json['link'] == null ? undefined : json['link'],
        'name': json['name'] == null ? undefined : json['name'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function UpdateBookmarkRequestToJSON(json: any): UpdateBookmarkRequest {
    return UpdateBookmarkRequestToJSONTyped(json, false);
}

export function UpdateBookmarkRequestToJSONTyped(value?: UpdateBookmarkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmarkId': value['bookmarkId'],
        'link': value['link'],
        'name': value['name'],
        'userId': value['userId'],
    };
}

