/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepositorySearchUsersByUsernameRow } from './RepositorySearchUsersByUsernameRow';
import {
    RepositorySearchUsersByUsernameRowFromJSON,
    RepositorySearchUsersByUsernameRowFromJSONTyped,
    RepositorySearchUsersByUsernameRowToJSON,
    RepositorySearchUsersByUsernameRowToJSONTyped,
} from './RepositorySearchUsersByUsernameRow';

/**
 * 
 * @export
 * @interface UsersSearchResponse
 */
export interface UsersSearchResponse {
    /**
     * 
     * @type {Array<RepositorySearchUsersByUsernameRow>}
     * @memberof UsersSearchResponse
     */
    data?: Array<RepositorySearchUsersByUsernameRow>;
    /**
     * 
     * @type {string}
     * @memberof UsersSearchResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UsersSearchResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the UsersSearchResponse interface.
 */
export function instanceOfUsersSearchResponse(value: object): value is UsersSearchResponse {
    return true;
}

export function UsersSearchResponseFromJSON(json: any): UsersSearchResponse {
    return UsersSearchResponseFromJSONTyped(json, false);
}

export function UsersSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(RepositorySearchUsersByUsernameRowFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function UsersSearchResponseToJSON(json: any): UsersSearchResponse {
    return UsersSearchResponseToJSONTyped(json, false);
}

export function UsersSearchResponseToJSONTyped(value?: UsersSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(RepositorySearchUsersByUsernameRowToJSON)),
        'message': value['message'],
        'success': value['success'],
    };
}

