/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesUserData } from './ResponsesUserData';
import {
    ResponsesUserDataFromJSON,
    ResponsesUserDataFromJSONTyped,
    ResponsesUserDataToJSON,
    ResponsesUserDataToJSONTyped,
} from './ResponsesUserData';

/**
 * 
 * @export
 * @interface UsersResponse
 */
export interface UsersResponse {
    /**
     * 
     * @type {Array<ResponsesUserData>}
     * @memberof UsersResponse
     */
    data?: Array<ResponsesUserData>;
    /**
     * 
     * @type {string}
     * @memberof UsersResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UsersResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the UsersResponse interface.
 */
export function instanceOfUsersResponse(value: object): value is UsersResponse {
    return true;
}

export function UsersResponseFromJSON(json: any): UsersResponse {
    return UsersResponseFromJSONTyped(json, false);
}

export function UsersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ResponsesUserDataFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function UsersResponseToJSON(json: any): UsersResponse {
    return UsersResponseToJSONTyped(json, false);
}

export function UsersResponseToJSONTyped(value?: UsersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ResponsesUserDataToJSON)),
        'message': value['message'],
        'success': value['success'],
    };
}

