/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesUserData } from './ResponsesUserData';
import {
    ResponsesUserDataFromJSON,
    ResponsesUserDataFromJSONTyped,
    ResponsesUserDataToJSON,
    ResponsesUserDataToJSONTyped,
} from './ResponsesUserData';

/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {ResponsesUserData}
     * @memberof UserResponse
     */
    data?: ResponsesUserData;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the UserResponse interface.
 */
export function instanceOfUserResponse(value: object): value is UserResponse {
    return true;
}

export function UserResponseFromJSON(json: any): UserResponse {
    return UserResponseFromJSONTyped(json, false);
}

export function UserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ResponsesUserDataFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function UserResponseToJSON(json: any): UserResponse {
    return UserResponseToJSONTyped(json, false);
}

export function UserResponseToJSONTyped(value?: UserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ResponsesUserDataToJSON(value['data']),
        'message': value['message'],
        'success': value['success'],
    };
}

