/* tslint:disable */
/* eslint-disable */
/**
 * mindscape
 * This is the swagger page for the Project mindscape generated with Egg-go. use this to test your database connection
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsesWidgetData } from './ResponsesWidgetData';
import {
    ResponsesWidgetDataFromJSON,
    ResponsesWidgetDataFromJSONTyped,
    ResponsesWidgetDataToJSON,
    ResponsesWidgetDataToJSONTyped,
} from './ResponsesWidgetData';

/**
 * 
 * @export
 * @interface WidgetResponse
 */
export interface WidgetResponse {
    /**
     * 
     * @type {ResponsesWidgetData}
     * @memberof WidgetResponse
     */
    data?: ResponsesWidgetData;
    /**
     * 
     * @type {string}
     * @memberof WidgetResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WidgetResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the WidgetResponse interface.
 */
export function instanceOfWidgetResponse(value: object): value is WidgetResponse {
    return true;
}

export function WidgetResponseFromJSON(json: any): WidgetResponse {
    return WidgetResponseFromJSONTyped(json, false);
}

export function WidgetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ResponsesWidgetDataFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function WidgetResponseToJSON(json: any): WidgetResponse {
    return WidgetResponseToJSONTyped(json, false);
}

export function WidgetResponseToJSONTyped(value?: WidgetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ResponsesWidgetDataToJSON(value['data']),
        'message': value['message'],
        'success': value['success'],
    };
}

