/* Generated by egg v0.0.1 */

package configuration

import (
	"errors"
	"os"
	"time"

	"gopkg.in/yaml.v3"
)

const (
	// DefaultAccessTokenTTL is used when server.access_token_ttl is unset or invalid.
	DefaultAccessTokenTTL = 15 * time.Minute
	// DefaultRefreshTokenTTL is used when server.refresh_token_ttl is unset or invalid.
	DefaultRefreshTokenTTL = 30 * 24 * time.Hour
)

type Configuration struct {
	Namespace string `yaml:"namespace"`
	Name      string `yaml:"name"`
	Semver    string `yaml:"semver"`
	License   string `yaml:"license"`
	Copyright struct {
		Year   int    `yaml:"year"`
		Author string `yaml:"author"`
	} `yaml:"copyright"`
	Server struct {
		JWT      string `yaml:"jwt"`
		Port     int    `yaml:"port"`
		Frontend struct {
			Dir string `yaml:"dir"`
			Api string `yaml:"api"`
		} `yaml:"frontend"`
		// AccessTokenTTL is the lifetime of the short-lived access JWT
		// (go duration string, e.g. "15m"). Defaults to 15 minutes.
		AccessTokenTTL string `yaml:"access_token_ttl"`
		// RefreshTokenTTL is the lifetime of the refresh-token session
		// (go duration string, e.g. "720h"). Defaults to 30 days.
		RefreshTokenTTL string `yaml:"refresh_token_ttl"`
		Cookie          struct {
			// Secure marks the refresh cookie HTTPS-only. Enable in production.
			Secure bool `yaml:"secure"`
		} `yaml:"cookie"`
	} `yaml:"server"`
	Database struct {
		URL                    string `yaml:"url"`
		Sqlc struct {
			RepositoryLocation string `yaml:"repository"`
			Schema             string `yaml:"schema"`
			SqlOrGo            string `yaml:"sql_or_go"`
		} `yaml:"sqlc"`
		QueriesLocation        string `yaml:"queries"`
		Migration              struct {
			Protocol    string `yaml:"protocol"`
			Destination string `yaml:"destination"`
		} `yaml:"migration"`
	} `yaml:"database"`
	Cache struct {
		URL string `yaml:"url"`
	} `yaml:"cache"`
	S3 struct {
		URL    string `yaml:"url"`
		Access string `yaml:"access"`
		Secret string `yaml:"secret"`
		Secure bool   `yaml:"secure"`
	} `yaml:"s3"`
	ApiKey struct {
		DefaultExpiration string `yaml:"default_expiration"`
	} `yaml:"apikey"`
}

// AccessTokenDuration parses server.access_token_ttl, falling back to
// DefaultAccessTokenTTL when the key is missing or malformed.
func (configuration *Configuration) AccessTokenDuration() time.Duration {
	if d, err := time.ParseDuration(configuration.Server.AccessTokenTTL); err == nil && d > 0 {
		return d
	}
	return DefaultAccessTokenTTL
}

// RefreshTokenDuration parses server.refresh_token_ttl, falling back to
// DefaultRefreshTokenTTL when the key is missing or malformed.
func (configuration *Configuration) RefreshTokenDuration() time.Duration {
	if d, err := time.ParseDuration(configuration.Server.RefreshTokenTTL); err == nil && d > 0 {
		return d
	}
	return DefaultRefreshTokenTTL
}

const ConfigurationDir = "./config/"

func LoadConfiguration(environment string) (*Configuration, error) {
	configuration := new(Configuration)
	configurationFile := ConfigurationDir + environment + ".yaml"
	file, err := os.ReadFile(configurationFile)
	if err != nil {
		return configuration, err
	}
	if err = yaml.Unmarshal(file, configuration); err != nil {
		return configuration, err
	}
	return configuration, nil
}

func SaveConfiguration(configBytes []byte, environment string) error {
	configurationFile := ConfigurationDir + environment + ".yaml"
	if _, err := os.Stat(configurationFile); errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err := os.WriteFile(configurationFile, configBytes, 0777); err != nil {
		return err
	}
	return nil
}

func (configuration *Configuration) GenerateConfigurationFile(environment string) error {
	// create the config directory if not exists config/
	if _, err := os.Stat(ConfigurationDir); errors.Is(err, os.ErrNotExist) {
		if err := os.Mkdir(ConfigurationDir, 0777); err != nil {
			return err
		}
	}
	if _, err := os.Stat(ConfigurationDir + environment + ".yaml"); errors.Is(err, os.ErrNotExist) {
		if _, err := os.Create(ConfigurationDir + environment + ".yaml"); err != nil {
			return err
		}
	}
	// write to the file with the yaml content as the configuration
	configBytes, err := yaml.Marshal(configuration)
	if err != nil {
		return err
	}
	if err := SaveConfiguration(configBytes, environment); err != nil {
		return err
	}
	return nil
}
