basePath: /api
definitions:
  BookmarkResponse:
    properties:
      data:
        $ref: '#/definitions/repository.Bookmark'
      message:
        type: string
      success:
        type: boolean
    type: object
  BookmarksResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/repository.Bookmark'
        type: array
      message:
        type: string
      success:
        type: boolean
    type: object
  DeleteUserResponse:
    properties:
      data:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  LoginResponse:
    properties:
      data:
        $ref: '#/definitions/responses.UserData'
      jwt:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  NewUserRequest:
    properties:
      email:
        type: string
      isAdmin:
        type: boolean
      password:
        type: string
      username:
        type: string
    type: object
  StringResponse:
    properties:
      data:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  UpdateCredentialsRequest:
    properties:
      email:
        type: string
      id:
        type: string
      oldPassword:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  UpdateUserResponse:
    properties:
      data:
        $ref: '#/definitions/responses.UserData'
      jwt:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  UserResponse:
    properties:
      data:
        $ref: '#/definitions/responses.UserData'
      message:
        type: string
      success:
        type: boolean
    type: object
  UsersResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/responses.UserData'
        type: array
      message:
        type: string
      success:
        type: boolean
    type: object
  repository.Bookmark:
    properties:
      created_datetime:
        type: string
      description:
        type: string
      folder_id:
        type: string
      icon:
        type: string
      id:
        type: string
      link:
        type: string
      name:
        type: string
      updated_datetime:
        type: string
      user_id:
        type: string
    type: object
  repository.CreateBookmarkParams:
    properties:
      folder_id:
        type: string
      link:
        type: string
      name:
        type: string
      user_id:
        type: string
    type: object
  repository.CreateFolderParams:
    properties:
      description:
        type: string
      name:
        type: string
      parent_id:
        type: string
      user_id:
        type: string
    type: object
  repository.Folder:
    properties:
      created_datetime:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      parent_id:
        type: string
      updated_datetime:
        type: string
      user_id:
        type: string
    type: object
  repository.Note:
    properties:
      content:
        type: string
      created_datetime:
        type: string
      description:
        type: string
      folder_id:
        type: string
      id:
        type: string
      name:
        type: string
      updated_datetime:
        type: string
      user_id:
        type: string
    type: object
  responses.FolderData:
    properties:
      bookmarks:
        items:
          $ref: '#/definitions/repository.Bookmark'
        type: array
      children:
        items:
          $ref: '#/definitions/repository.Folder'
        type: array
      created_datetime:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      notes:
        items:
          $ref: '#/definitions/repository.Note'
        type: array
      parent_id:
        type: string
      updated_datetime:
        type: string
      user_id:
        type: string
    type: object
  responses.FolderResponse:
    properties:
      data:
        $ref: '#/definitions/responses.FolderData'
      message:
        type: string
      success:
        type: boolean
    type: object
  responses.FoldersResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/responses.FolderData'
        type: array
      message:
        type: string
      success:
        type: boolean
    type: object
  responses.UserData:
    properties:
      admin:
        type: boolean
      created_datetime:
        type: string
      email:
        type: string
      id:
        type: string
      profile_pic_url:
        type: string
      updated_datetime:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    name: Adam Kalinowski
    url: https://github.com/adamkali/mindscape
  description: This is the swagger page for the Project mindscape generated with Egg-go.
    use this to test your database connection
  license:
    name: MIT
  title: mindscape
  version: 0.0.1
paths:
  /bookmarks:
    post:
      consumes:
      - application/json
      description: Create a new Bookmark by Authorization Header
      operationId: CreateBookmark
      parameters:
      - description: CreateBookmarkRequest
        in: body
        name: CreateBookmarkRequest
        required: true
        schema:
          $ref: '#/definitions/repository.CreateBookmarkParams'
      - default: '"Bearer token"'
        description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/BookmarkResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/BookmarkResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/BookmarkResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/BookmarkResponse'
      summary: Create a new Bookmark
      tags:
      - Bookmarks
  /bookmarks/folder/{parent_id}:
    get:
      consumes:
      - application/json
      description: |-
        Get all Bookmarks by Authorization Header and by the
        ParentFolderId [parent_id]
      operationId: GetBookmarks
      parameters:
      - default: '"Bearer token"'
        description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      - default: '"e38e78a4-2ca3-4c59-a3ea-a2019866e593"'
        description: Parent Folder ID
        in: path
        name: parent_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/BookmarksResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/BookmarksResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/BookmarksResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/BookmarksResponse'
      summary: Get Bookmarks By Folder ID
      tags:
      - Bookmarks
  /folders:
    get:
      consumes:
      - application/json
      description: |-
        Get the Root Folders associated with the user by Authorization Header
        and will also try to get the children of the folder as well
      operationId: GetRootFolders
      parameters:
      - default: '"Bearer token"'
        description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.FoldersResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responses.FoldersResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.FoldersResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.FoldersResponse'
      summary: Get the Root Folders associated with the user
      tags:
      - Folders
    post:
      consumes:
      - application/json
      description: Create a new Folder by Authorization Header
      operationId: CreateFolder
      parameters:
      - description: Create Folder Request
        in: body
        name: CreateFolderRequest
        required: true
        schema:
          $ref: '#/definitions/repository.CreateFolderParams'
      - default: '"Bearer token"'
        description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.FolderResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responses.FolderResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.FolderResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.FolderResponse'
      summary: Create a new Folder
      tags:
      - Folders
  /folders/{folder_id}:
    delete:
      consumes:
      - application/json
      description: Delete a Folder by Authorization Header and tries to cascade delete
      operationId: DeleteFolder
      parameters:
      - default: '"e38e78a4-2ca3-4c59-a3ea-a2019866e593"'
        description: Folder ID
        in: path
        name: folder_id
        required: true
        type: string
      - default: '"Bearer token"'
        description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.FolderResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.FolderResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.FolderResponse'
      summary: Delete a Folder
      tags:
      - Folders
    get:
      consumes:
      - application/json
      description: |-
        Get the Folders associated with the user under A Parent Folder by Authorization Header
        and will also try to get the children of the folder as well
      operationId: GetFolders
      parameters:
      - default: '"e38e78a4-2ca3-4c59-a3ea-a2019866e593"'
        description: Folder ID
        in: path
        name: folder_id
        required: true
        type: string
      - default: '"Bearer token"'
        description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.FolderResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responses.FolderResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.FolderResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.FolderResponse'
      summary: Get the Folders associated with the user under A Parent Folder
      tags:
      - Folders
  /users/:
    get:
      description: Get All Users. Must be Admin using the new mediator pattern
      operationId: GetUsers
      parameters:
      - default: Bearer token
        description: admin header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/UsersResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/UsersResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/UsersResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/UsersResponse'
      summary: Get All Users
      tags:
      - Users
  /users/{user_id}:
    delete:
      description: get string by ID
      operationId: DeleteUserByUUID
      parameters:
      - default: '"e38e78a4-2ca3-4c59-a3ea-a2019866e593"'
        description: User Id
        in: path
        name: user_id
        required: true
        type: string
      - default: '"Bearer token"'
        description: admin header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/DeleteUserResponse'
      summary: Delete User by their UUID
      tags:
      - Users
  /users/creds:
    post:
      consumes:
      - application/json
      description: |-
        Update User Credentials by id, Must be the same user in the jwt
        that is being updated
      operationId: UpdateUser
      parameters:
      - description: Update User Credentials Request
        in: body
        name: UpdateCredentialsRequest
        required: true
        schema:
          $ref: '#/definitions/UpdateCredentialsRequest'
      - default: Bearer token
        description: admin header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/UpdateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/UpdateUserResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/UpdateUserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/UpdateUserResponse'
      summary: Update User Credentials
      tags:
      - Users
  /users/current:
    get:
      description: Get the Current User by the uuid storred in the Claims header
      operationId: GetCurrentLoggedInUser
      parameters:
      - default: Bearer token
        description: admin header
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/UserResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/UserResponse'
      summary: Get Current User
      tags:
      - Users
  /users/login:
    post:
      consumes:
      - application/json
      description: to a user account with either email or username
      operationId: Login
      parameters:
      - description: Log in request
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/LoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/LoginResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/LoginResponse'
      summary: Login
      tags:
      - Users
  /users/profile:
    get:
      description: Get User Profile by Authorization Header
      operationId: GetProfilePicture
      parameters:
      - default: Bearer token
        description: admin header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/StringResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/StringResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/StringResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/StringResponse'
      summary: Get User Profile by Authorization Header
      tags:
      - Users
    post:
      consumes:
      - multipart/form-data
      description: Upload file
      operationId: UploadProfilePicture
      parameters:
      - description: this is a test file
        in: formData
        name: file
        required: true
        type: file
      - default: Bearer token
        description: admin header
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/UserResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/UserResponse'
      summary: Upload file
      tags:
      - Users
  /users/signup:
    post:
      consumes:
      - application/json
      description: Signup using the requests.NewUserRequest
      operationId: Signup
      parameters:
      - description: Signup Request
        in: body
        name: SignupRequest
        required: true
        schema:
          $ref: '#/definitions/NewUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/LoginResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/LoginResponse'
      summary: Signup to the app
      tags:
      - Users
schemes:
- http
swagger: "2.0"
