/* Generated by egg v0.0.1 */

package configs

import (
	"strings"

	"github.com/golang-jwt/jwt/v5"
	echojwt "github.com/labstack/echo-jwt/v4"
	"github.com/labstack/echo/v4"
	"github.com/adamkali/mindscape/services"
	"github.com/adamkali/mindscape/cmd/configuration"
)

func AuthMiddlewareConfig(config *configuration.Configuration) echojwt.Config {
	return echojwt.Config {
		SuccessHandler: func(c echo.Context) {
			logger := c.Logger()
			logger.Info("Success Recognized Token")
		},
		ErrorHandler: func(c echo.Context, err error) error {
			logger := c.Logger()
			logger.Error(err.Error())
			return c.JSON(401, map[string]string{"message": err.Error()})
		},
		SigningKey: []byte(config.Server.JWT),
		Skipper: func(c echo.Context) bool {
			if strings.Contains(c.Path(), "swagger") {
				return true
			} else {
				return false
			}
		},
		NewClaimsFunc: func(c echo.Context) jwt.Claims {
			return new(services.CustomJwt)
		},
	}
}
