/* Generated by egg v0.0.1 */

package configs

import (
	"strings"

	"github.com/adamkali/mindscape/cmd/configuration"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)

func StaticMiddlewareConfig(config *configuration.Configuration) middleware.StaticConfig {
	return middleware.StaticConfig{
		Root:       config.Server.Frontend.Dir,
		HTML5:      true,
		Browse:     false,
		IgnoreBase: false,
		Filesystem: nil,
		Skipper: func(c echo.Context) bool {
			if strings.Contains(c.Path(), "swagger") ||
			   strings.Contains(c.Path(), "api") {
				return true
			} else {
				return false
			}
		},
	}
}
